### ISSUE TITLE
packages missing from melpa

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10244]
I get the following on startup, e.g. `rtags` is currently not on melpa:

```
Found 7 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: company-rtags@c-c++... [1/7]
Package rtags is unavailable. Is the package name misspelled?
--> installing package: counsel-projectile@spacemacs-layouts... [2/7]
Package swiper is unavailable. Is the package name misspelled?

Package swiper is unavailable. Is the package name misspelled?
--> installing package: flycheck-rtags@c-c++... [3/7]
Package rtags is unavailable. Is the package name misspelled?
--> installing package: helm-rtags@c-c++... [4/7]
Package rtags is unavailable. Is the package name misspelled?
--> installing package: rtags@c-c++... [6/7]
Package rtags is unavailable. Is the package name misspelled?
--> installing package: spaceline-all-the-icons@spacemacs-modeline... [7/7]
Package spaceline-all-the-icons is unavailable. Is the package name misspelled?
```

**Comment by jonathanschmitz** [comment]
Seems like melpa is currently being rebuilt: <blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">MELPA is down rebuilding all packages. Sorry for the issue. Things should be back after a full rebuild.</p>&mdash; MELPA (@melpa_emacs) <a href="https://twitter.com/melpa_emacs/status/956031413085724672?ref_src=twsrc%5Etfw">January 24, 2018</a></blockquote>

Hopefully back up soon.

**Comment by gdkrmr** [comment]
ok, that was the reason, now only `font-lock+` is missing. 

```
--> installing package: spaceline-all-the-icons@spacemacs-modeline... [1/1]
Package font-lock+ is unavailable. Is the package name misspelled?
```
The following recipe wont help, because font-lock+.el specifies that it is version `0` and won't install:
```
     ;; (font-lock+
     ;;  :location
     ;;  (recipe :fetcher url
     ;;          :url "https://github.com/emacsmirror/emacswiki.org/blob/master/font-lock+.el"))
```

**Comment by dsnipe** [comment]
Melpa has finished the rebuild, but I still can't install all packages properly.
Getting this:
```
(Spacemacs) Error: 
An error occurred while installing eval-sexp-fu (error: (error Package ‘highlight-0’ is unavailable))
(Spacemacs) --> installing package: evil-search-highlight-persist@spacemacs-evil... [2/6]
(Spacemacs) Error: 
An error occurred while installing evil-search-highlight-persist (error: (error Package ‘highlight-0’ is unavailable))

<strip>

Spacemacs) Error: 
An error occurred while installing spaceline-all-the-icons (error: (error Package ‘font-lock+-0’ is unavailable))
```

**Comment by dsnipe** [comment]
Looks like some libraries disappeared from Melpa, because they have `Version: 0`. Probably, the only workaround is to manually copy them.

**Comment by kommen** [comment]
Same here, people starting from a fresh install getting error messages that "highlight" is unavailable.

**Comment by srid** [comment]
> Probably, the only workaround is to manually copy them.

Yup, this is what I did as a workaround. Copy the missing package directories from `~/.emacs.d/elpa/25.2/develop` of an existing working Spacemacs installation.

**Comment by dsnipe** [comment]
@srid this doesn't work for me unfortunately. Should I require packages manually?

**Comment by srid** [comment]
@dsnipe Did you copy over each and every missing package? Maybe try copying over the entire `~/.emacs.d/elpa/25.2/develop` directory.

**Comment by dsnipe** [comment]
Unfortunately, I removed my old `develop` folder. I copied just `highlight.el` file into the directory, also tried to create `highlight-0/highlight.el`. No success :( So I have no idea what structure should I create.

**Comment by srid** [comment]
Feel free to try with my backup of develop.zip: http://beaunix.srid.ca/tmp/develop.zip (comes with no guarantees whatsoever).

**Comment by dsnipe** [comment]
@srid you saved my day! Thanks a lot!

**Comment by gdkrmr** [comment]
I tried to copy `font-lock+.el` into `~/.emacs.d/private/local` and spacemacs does not find it, am I doing anything wrong? The README in that folder says to put packages there.

**Comment by Fenton-Fenton** [comment]
@srid appreciate the suggestion but this doesn't seem to have fixed the problem for me. I definitely  picked the wrong day to do a fresh reinstall!

**Comment by milkypostman** [comment]
Every package at the top of this issue seems to be available. Are there specific packages that are missing?

**Comment by gdkrmr** [comment]
they all got installed after the melpa finished building, the one that does not work is `font-lock+` because of the version number issue

**Comment by jonathanschmitz** [comment]
Also `help-fns+`, `hide-comnt`, and `info+` for me.

**Comment by Fenton-Fenton** [comment]
@milkypostman seems to be eval-sexp-fu for me

**Comment by jonathanschmitz** [comment]
@Fenton-Fenton I think the install of `eval-sexp-fu` fails because `highlight` is not available

**Comment by kommen** [comment]
@milkypostman `highlight` seems to have been missing for us.

**Comment by Fenton-Fenton** [comment]
@jonathanschmitz I just checked this and you are correct it is `highlight` thats the root of this problem for me.

**Comment by kommen** [comment]
For reference: the issue is that packages from the emacs wiki are not being rebuilt. `highlight` is one of them. See https://github.com/melpa/melpa/pull/5008#issuecomment-360103510 for a discussion

**Comment by milkypostman** [comment]
Highlight is a wiki package. This is going to be an issue. 

@tarsius is there anyways we can get the highlight package moved to the mirror quickly and updated?

**Comment by milkypostman** [comment]
Temp solution to get you unblocked is to manually install this package from emacs wiki. 


I am not sure how we will resolve this timely. Is there a way to put this package directly into spacemacs and push a new version. 

Wiki packages have been on the chopping block for 3 years. And I really think Spacemacs should avoid depending on something from the wiki anyways  

But it’s also not ok for Melpa to break Spacemacs.

**Comment by syl20bnr** [comment]
np, I will fix the wiki packages by pushing their code to spacemacs repo this evening.
When those packages are back into MELPA from the mirror we will switch back to MELPA.

**Comment by syl20bnr** [comment]
Make me think we should have been pro-active on this, lots of us knew that wiki packages were being removed from MELPA.

**Comment by tarsius** [comment]
I have pushed a temporary fix for `highlight` to Melpa.

**Comment by milkypostman** [comment]
@syl20bnr I don’t think we will add back wiki packages unless they go to the emacsmirror.

**Comment by milkypostman** [comment]
^^^ so just a heads up ;)

**Comment by Fedreg** [comment]
@srid Saved my day with your develop backup!  Thanks!!

**Comment by Blaisorblade** [comment]
So my new spacemacs install (from master) is still not working, even after @tarsius  fix (not sure if deployed). Switching to `spacemacs-base` during the install wizard fixed things (the remaining failures are not critical). That is, when selecting vim/spacemacs-base/helm in the wizard, only help-fns+ fails installing but Spacemacs is by and large usable.
```
Found 5 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: eval-sexp-fu@spacemacs-editing... [1/5]
Package highlight is unavailable. Is the package name misspelled?

An error occurred while installing eval-sexp-fu (error: (error Package `highlight-0' is unavailable))
--> installing package: evil-search-highlight-persist@spacemacs-evil... [2/5]
Package highlight is unavailable. Is the package name misspelled?

An error occurred while installing evil-search-highlight-persist (error: (error Package `highlight-0' is unavailable))
--> installing package: help-fns+@spacemacs-base... [3/5]
Package help-fns+ is unavailable. Is the package name misspelled?
--> installing package: hide-comnt@spacemacs-editing-visual... [4/5]
Package hide-comnt is unavailable. Is the package name misspelled?
--> installing package: info+@spacemacs-ui... [5/5]
Package info+ is unavailable. Is the package name misspelled?
```

**Comment by CarlQLange** [comment]
Just popping in to say @milkypostman @tarsius @syl20bnr: you're all doing a great job and we ♥️ you and your work.

**Comment by tarsius** [comment]
@Blaisorblade Yeah, I had some urgent personal matter to attend to so I only quickly read the bottom of this thread and fixed the package I saw mentioned there. Could someone please provide a complete list of packages out of those listed [here](https://github.com/melpa/melpa/pull/5008#issuecomment-360103510) that Spacemacs may depend on.

I can then do the same for those as I have done for `highlight`. Please also review the package as currently found on the Emacsmirror for malicious code (just the commits since 2017-09-16).

@CarlQLange and all the likers, thanks that means a lot.

> I don’t think we will add back wiki packages unless they go to the emacsmirror.

@milkypostman Well I am temporarily adding some back, but...

> Make me think we should have been pro-active on this, lots of us knew that wiki packages were being removed from MELPA.

...going forward the Spacemacs folks and other users of these package have three options I think:

1. Stop depending on all packages from the wiki and all packages that depend on such a package.
2. Get the authors of the latter to remove these dependencies or at least make them optional.
3. Become the "package maintainer" of the necessary packages from the wiki. Periodically download new versions from the wiki, carefully review them, and then commit and push the changes. Melpa and the Emacsmirror could then get those packages from your proxy repository.

Drew is not willing to use Git or Mercurial so don't even try to fix the issue at its source. It has been tried many times.

**Comment by jsoo1** [comment]
I noticed `font-lock+` is a wiki package that is used by `all-the-icons`, which is (i think) required for `spaceline-all-the-icons`.

**Comment by Blaisorblade** [comment]
@tarsius Thanks for the help and don't worry.

I just wanted to point out that `highlight` *seemed* not to install despite your fix, but the problem went away and now `highlight` works. If I go back to full spacemacs, now I get the following errors (right away or on restart), and setting `dotspacemacs-excluded-packages` to `'(info+ help-fns+ hide-comnt)` in `.spacemacs` avoids the errors. I recommend for now excluding any other packages whose install fails. These three packages are missing from the list you posted, and should probably be added there.
```
Found 3 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: help-fns+@spacemacs-base... [1/3]
Package help-fns+ is unavailable. Is the package name misspelled?
--> installing package: hide-comnt@spacemacs-editing-visual... [2/3]
Package hide-comnt is unavailable. Is the package name misspelled?
--> installing package: info+@spacemacs-ui... [3/3]
Package info+ is unavailable. Is the package name misspelled?
```

They seem to come up because they are requested explicitly (not by other packages depending on them). More precisely, that's my uneducated guess (sorry) because of the following content in the *Warnings* buffer (I've seen other similar warnings earlier):

```
Error (use-package): info+/:init: Cannot open load file: no such file or directory, info+
```

**Comment by Blaisorblade** [comment]
Also FWIW: for Spacemacs needs, I suspect freezing those packages at the current versions would be enough for now (or for any amount of time).

**Comment by syl20bnr** [comment]
Done a full install of Spacemacs with `dotspacemacs-install-packages 'all` which installs 616 packages in develop branch. Found only 3/4 problematic packages as mentioned by @Blaisorblade above.

> Become the "package maintainer" of the necessary packages from the wiki. Periodically download new versions from the wiki, carefully review them, and then commit and push the changes. Melpa and the Emacsmirror could then get those packages from your proxy repository.

This is what I've done. A new release for master branch 0.200.13 has been released to fix them, imported from Emacsmirror GitHub organization for now:
- Import info+.el as local package
- Import help-fns+.el as local package
- Import hide-comnt.el as local package

For develop branch I also pushed a fix for `all-the-icons` as `font-lock+.el` is a dependency of this package. We fetch it from Emacsmirror. Opened issue here: https://github.com/domtronn/all-the-icons.el/issues/98

BTW thanks @tarsius for maintaining Emacsmirror 👍

**Comment by purcell** [comment]
Thanks for your understanding, everyone. While this is an annoying disruption in the short term, the community will be in a better place for having dropped packages that were a significant security risk.

**Comment by gdkrmr** [comment]
great, for my purposes everything seems to work again. Should I close this issue or leave it open until the 3/4 packages  get fixed? Thanks to all the maintainers for the quick fixes!!

**Comment by Blaisorblade** [comment]
Everything seems fixed here too, thanks again to everyone who contributed!

**Comment by gdkrmr** [comment]
please reopen if you feel the need to.

**Comment by tarsius** [comment]
@syl20bnr Thanks. Please do the same for `highlight.el`. There's no reason to treat that package differently from the others. (Except that I already implemented another kludge for it, but I would like to remove that.)

**Comment by tarsius** [comment]
Does Spacemacs use any of these non-wiki packages? They will have to be removed from Melpa too, so you should probably do the same for those packages as you have done for the wiki packages.

```
| non-wiki package needs        | wiki package |
|-------------------------------+--------------|
| all-the-icons                 | font-lock+   |
| cider-eval-sexp-fu            | highlight    |
| el-spice                      | thingatpt+   |
| eval-sexp-fu                  | highlight    |
| evil-search-highlight-persist | highlight    |
| exato                         | thingatpt+   |
| floobits                      | highlight    |
| nrepl-eval-sexp-fu            | highlight    |
| paper-theme                   | hexrgb       |
| php-boris-minor-mode          | highlight    |
| sonic-pi                      | highlight    |
| spiral                        | highlight    |
```

**Comment by tarsius** [comment]
@steckerhalter now proxy maintains `highlight` at https://github.com/steckerhalter/highlight.el. See https://github.com/melpa/melpa/pull/5008#issuecomment-360566662 ff.

**Comment by syl20bnr** [comment]
Spacemacs should be good if I understood correctly what will happen:

1- The non-wiki packages that depends on `highlight` won't be removed as we have now a new maintainer (thanks you @steckerhalter)
2- `all-the-icons` won't be removed as `font-lock+` is now an optional dependency and has been removed from the header (https://github.com/domtronn/all-the-icons.el/commit/52d1f2d36468146c93aaf11399f581401a233306)

If the above is true then we are fine here :-)

**Comment by syl20bnr** [comment]
@tarsius there might be transitive dependencies to consider as well. For instance `spaceline-all-the-icons` depends on `all-the-icons`.

**Comment by milkypostman** [comment]
thats correct! everything seems to be in order and highlight is building
from the new location.

thanks for all your help and understanding.

**Comment by syl20bnr** [comment]
Thank you @milkypostman

**Comment by bobberb** [comment]
On a fresh pull of develop @syl20bnr we have a similar situation with `font-lock+`
