### ISSUE TITLE
spacemacs/jump-to-definition for clojure layer broken

### ISSUE THREAD

**Issue by gzmask** [syl20bnr/spacemacs#10774]
Emacs version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.3.0, NS appkit-1561.20 Version 10.13.2 (Build 17C88)) of 2018-05-29

Spacemacs version: commit 4e3990ce524802ddb244539983fd41100f168e72 (HEAD -> develop, origin/develop)

Problem:
- started REPL
- eval buffer
- ",gg" shows "No jump handler was able to find this symbol."
- spc-j-f clj-find-var works.

**Comment by achikin** [comment]
https://github.com/syl20bnr/spacemacs/issues/10777#issuecomment-393392479 - switching to develop branch of Spacemacs fixes this issue.

**Comment by achikin** [comment]
Nope, it broke again :(
I didn't realize that Spacemacs now uses dumb jump as a go-to-definition backup option...

**Comment by achikin** [comment]
@syl20bnr  This is very serious. I've checked CIDER on raw emacs 26.1 and it works perfectly, so CIDER maintainers refuse to fix this.

**Comment by sdwolfz** [comment]
Tried playing with this a bit. From the code I understand it falls back to dumb jump when a cider connection is not established. Are you sure you have cider up and running correctly (`, '` and look at the `*nrepl-server*` buffer)?

**Comment by achikin** [comment]
@sdwolfz I am pretty sure I jacked in. I use Spacemacs every day for 8+ hours for Clojure development.

**Comment by achikin** [comment]
I have downgraded emacs back to 25.3, deleted .emacs.d and reinstalled Spacemacs.
I'm still experiencing issues, described here https://github.com/clojure-emacs/cider/issues/2303
There is something wrong with cider integration in spacemacs.
Can I downgrade cider to 0.17 in Spacemacs somehow?

**Comment by sdwolfz** [comment]
Try with the following in your `dotspacemacs/user-init`:
```emacs-lisp
(push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer-elpa-archives)
(push '(cider . "melpa-stable") package-pinned-packages)
```
(I had this for `ensime` sinnce there were simmilar problems there but I have not used it for over a year)

**Comment by syl20bnr** [comment]
Does it never work at all now ? I'm puzzled with the fact that you got
it fixed momentarily. Were you able to have the correct `cljs` in the
mode line ?

Have you kept the old .emacs.d ? Spacemacs has rollback capabilities
also MELPA packages are isolated per emacs version in the
~/.emacs.d/elpa/<version> directory so it would be possible to restore
your old config.

You seem to have encountered lots of issue with Cider, next time you can
rollback your package update with `rollback packages` in the home buffer
and then add cider packages to the `dotspacemacs-frozen-packages` in
your dotfile and Spacemacs won't update it until your remove it from
this list. This way you can be confident to test new Cider releases and
rollback to previous version while your opened issue is resolved.

**Comment by gzmask** [comment]
I tried updated to the newest develop branch and goto definition still broken, returning "No jump handler was able to find this symbol. "

**Comment by achikin** [comment]
I rolled back to master branch and Emacs 25.3 and everything works now.

**Comment by gzmask** [comment]
Nooo!!!  I am too used to having the goodies of the develop branch now.

**Comment by syl20bnr** [comment]
That's rather a weird issue we have here...

@gzmask nuke/rename the `~/.emacs.d/elpa` directory and restart
Spacemacs to reinstall everything and see how it goes.

**Comment by gzmask** [comment]
clearing elpa fixed the problem, thanks @syl20bnr !
