### ISSUE TITLE
Bug: ivy/counsel: Wrong number of arguments searching with `spacemacs/search-project-*`

### ISSUE THREAD

**Issue by jsoo1** [syl20bnr/spacemacs#11048]
#### Reproduction guide :beetle:
- Start Emacs
- Select a projectile project and enter a project buffer
- `SPC /`

*Observed behaviour:* :eyes: :broken_heart:
(wrong-number-of-arguments (0 . 0) 1) in minibuffer

*Expected behaviour:* :heart: :smile:
Usual counsel search appears

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3cbf89b4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion
  (haskell :variables haskell-completion-backend 'dante))
 c-c++ clojure coq csv dash docker
 (elm :variables elm-format-command "elm-format")
 (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
 emoji erlang evil-snipe fsharp
 (git :variables git-magit-status-fullscreen t)
 graphviz
 (gtags :variables gtags-enable-by-default t)
 (haskell :variables haskell-process-type 'stack-ghci haskell-enable-hindent-style "fundamental")
 html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 idris ivy
 (java :variables java-backend 'ensime)
 (javascript :variables tern-command
             '("node" "/usr/local/bin/tern"))
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
 lsp
 (markdown :variables markdown-live-preview-engine 'vmd)
 nginx nixos
 (org :variables org-enable-reveal-js-support t org-enable-github-support t org-projectile-file "TODOs.org")
 osx
 (python :variables python-backend 'lsp python-enable-yapf-format-on-save t)
 restclient rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 spotify sql swift syntax-checking systemd tmux treemacs twitter version-control vimscript vinegar windows-scripts yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  counsel-more-chars(3)
  (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))
  (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))(--base-cmd-- "")
  apply((lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))) --base-cmd-- "")
  (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--))("")
  ivy--reset-state(#s(ivy-state :prompt "%-4d rg from [.../john/projects/client-browser/]: " :collection (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--)) :predicate nil :require-match nil :initial-input "" :history counsel-git-grep-history :preselect nil :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :update-fn nil :sort nil :frame #<frame F4 0x10b962c30> :window #<window 1128 on Update.elm> :buffer #<buffer Update.elm> :text nil :action (1 ("o" counsel-git-grep-action "default") ("i" #f(compiled-function (x) #<bytecode 0x43f16f11>) "insert") ("w" #f(compiled-function (x) #<bytecode 0x43f16f21>) "copy")) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)) :re-builder nil :matcher nil :dynamic-collection t :display-transformer-fn counsel-git-grep-transformer :directory "/Users/john/projects/client-browser/" :caller spacemacs/counsel-search :current nil :def nil))
  ivy-read("%-4d rg from [.../john/projects/client-browser/]: " (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--)) :initial-input "" :dynamic-collection t :history counsel-git-grep-history :action counsel-git-grep-action :caller spacemacs/counsel-search :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)))
  (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory)))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))
  (let ((tool (catch 'tool (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and (assoc-string tool spacemacs--counsel-commands) (executable-find tool)) (progn (throw 'tool tool))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw 'tool "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory)))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup))))))
  (let ((initial-input (if use-initial-input (if (region-active-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol t)) ""))) (let ((tool (catch 'tool (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and (assoc-string tool spacemacs--counsel-commands) (executable-find tool)) (progn (throw 'tool tool))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw 'tool "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory)))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))))
  spacemacs/counsel-search(("rg" "ag" "pt" "ack" "grep") nil "/Users/john/projects/client-browser/")
  spacemacs/search-project-auto()
  funcall-interactively(spacemacs/search-project-auto)
  call-interactively(spacemacs/search-project-auto nil nil)
  command-execute(spacemacs/search-project-auto)
```

**Comment by jsoo1** [comment]
I just rebased to commit `https://github.com/syl20bnr/spacemacs/commit/e63a9c05bd8e6c1bc905e4c28ceb5aa0d48d5b47` which includes https://github.com/syl20bnr/spacemacs/commit/e63a9c05bd8e6c1bc905e4c28ceb5aa0d48d5b47

The issue is still there.

**Comment by bmag** [comment]
If you have updated Ivy, Counsel and Spacemacs, there should be no issues. `counsel-more-chars` was changed upstream to take no arguments, accordingly we fixed the single and only place in Spacemacs where we call `counsel-more-chars`. If you updated, the issue you're seeing does not originate from Spacemacs.

**Comment by jsoo1** [comment]
I did an update when I rebased.

**Comment by bmag** [comment]
The error you posted was fixed in latest develop. If you're still seeing the same error, it's not because of a bug in Spacemacs. Is the backtrace the same? Did you restart Spacemacs?

**Comment by jsoo1** [comment]
I did restart. However I didn’t wipe the elpa directory. I should be used to this by now. Thanks for your patience @bmag. I owe you a drink of your choice.

**Comment by jsoo1** [comment]
I just removed all ivy and counsel directories and restarted, triggering a reinstall of the packages.  The issue is still there.

**Comment by jakemcarthur** [comment]
This seems to be fixed in develop, but not in master.

**Comment by bmag** [comment]
@jakemcarthur that's true. I don't know when it will be fixed in master, that is up to syl20bnr.

**Comment by paralin** [comment]
+1 on that not being fixed in master :)

**Comment by DoaneAS** [comment]
Appears this is still not fixed?

**Comment by d12frosted** [comment]
Could you please try on `develop` branch?

**Comment by malokroman** [comment]
I tried develop and did not work for me

**Comment by d12frosted** [comment]
Ok, then I have to ask you to do the following:

1. Make sure that all your packages are up to date.
2. Make sure that you are on the latest develop.
3. Share the search tool you are using (just in case) - e.g. `ack`, `ag`, `rg` etc. 
4. Share stack trace.

The stack trace is needed because the one originally shared makes no sense to me with the current code base. 

```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  counsel-more-chars(3)
  (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))
  (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))(--base-cmd-- "")
  apply((lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))) --base-cmd-- "")
  (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--))("")
  ivy--reset-state(#s(ivy-state :prompt "%-4d rg from [.../john/projects/client-browser/]: " :collection (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--)) :predicate nil :require-match nil :initial-input "" :history counsel-git-grep-history :preselect nil :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :update-fn nil :sort nil :frame #<frame F4 0x10b962c30> :window #<window 1128 on Update.elm> :buffer #<buffer Update.elm> :text nil :action (1 ("o" counsel-git-grep-action "default") ("i" #f(compiled-function (x) #<bytecode 0x43f16f11>) "insert") ("w" #f(compiled-function (x) #<bytecode 0x43f16f21>) "copy")) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)) :re-builder nil :matcher nil :dynamic-collection t :display-transformer-fn counsel-git-grep-transformer :directory "/Users/john/projects/client-browser/" :caller spacemacs/counsel-search :current nil :def nil))
  ivy-read("%-4d rg from [.../john/projects/client-browser/]: " (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--)) :initial-input "" :dynamic-collection t :history counsel-git-grep-history :action counsel-git-grep-action :caller spacemacs/counsel-search :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)))
  (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory)))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))
  (let ((tool (catch 'tool (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and (assoc-string tool spacemacs--counsel-commands) (executable-find tool)) (progn (throw 'tool tool))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw 'tool "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory)))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup))))))
  (let ((initial-input (if use-initial-input (if (region-active-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol t)) ""))) (let ((tool (catch 'tool (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and (assoc-string tool spacemacs--counsel-commands) (executable-find tool)) (progn (throw 'tool tool))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw 'tool "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory)))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))))
  spacemacs/counsel-search(("rg" "ag" "pt" "ack" "grep") nil "/Users/john/projects/client-browser/")
  spacemacs/search-project-auto()
  funcall-interactively(spacemacs/search-project-auto)
  call-interactively(spacemacs/search-project-auto nil nil)
  command-execute(spacemacs/search-project-auto)
```

As you can see `spacemacs/counsel-search` calls ` (lambda (G0 string &optional _pred &rest _unused) ...)` which in turn calls `counsel-more-chars` with one argument. But the current implementation calls `counsel-more-chars` without arguments.

```emacs-lisp
(defun spacemacs//make-counsel-search-function (tool)
    (lexical-let ((base-cmd
                   (cdr (assoc-string tool spacemacs--counsel-commands))))
      (lambda (string &optional _pred &rest _unused)
        "Grep in the current directory for STRING."
        ;; `counsel-more-chars' returns non-nil when more chars are needed,
        ;; minimal chars count is configurable via `counsel-more-chars-alist'
        (or (counsel-more-chars)
            (let* ((default-directory (ivy-state-directory ivy-last))
                   (args (if (string-match-p " -- " string)
                             (let ((split (split-string string " -- ")))
                               (prog1 (pop split)
                                 (setq string (mapconcat #'identity split " -- "))))
                           ""))
                   (regex (counsel-unquote-regex-parens
                           (setq ivy--old-re
                                 (ivy--regex string)))))
              (setq spacemacs--counsel-search-cmd (format base-cmd args regex))
              (spacemacs//counsel-async-command spacemacs--counsel-search-cmd)
              nil)))))
```

The last commit where `counsel-more-chars` is colled with one argument is 1c78348ee6ea03ab1133ae44b9a0e0053e7e5aec (Sun Jul 8 12:42:49 2018):

```emacs-lisp
(defun spacemacs//make-counsel-search-function (tool)
    (lexical-let ((base-cmd
                   (cdr (assoc-string tool spacemacs--counsel-commands))))
      (lambda (string &optional _pred &rest _unused)
        "Grep in the current directory for STRING."
        (if (< (length string) 3)
            (counsel-more-chars 3)
          (let* ((default-directory (ivy-state-directory ivy-last))
                 (args (if (string-match-p " -- " string)
                           (let ((split (split-string string " -- ")))
                             (prog1 (pop split)
                               (setq string (mapconcat #'identity split " -- "))))
                         ""))
                 (regex (counsel-unquote-regex-parens
                         (setq ivy--old-re
                               (ivy--regex string)))))
            (setq spacemacs--counsel-search-cmd (format base-cmd args regex))
            (spacemacs//counsel-async-command spacemacs--counsel-search-cmd)
            nil)))))
```

The fix was introduced in e63a9c05bd8e6c1bc905e4c28ceb5aa0d48d5b47 (Sat Jul 14 22:40:55 2018). 

So if your stack trace is the same as the stack trace shared by OP, please do update to the latest develop branch.

---

*To make it clear* - the issue is not fixed in master, so I open this issue again. I will try to backport it to the `master`.

**Comment by longshi0** [comment]
My solution was pretty simple, although i feel it probably works because counsel got some upgrade since the last time the problem was brought up.

(defun dotspacemacs/user-config ()
  ;; ....
  (evil-leader/set-key "/" 'counsel-rg))

If you prefer to use ag or something else, that function are there too. 

Works like a charm.

**Comment by microzhao** [comment]
1. M-x
2. counsel-ag

**Comment by maxandersen** [comment]
is it still necessary to update to latest dev branch ? its august 2019 (one year later) And I have similar error with wrong number of arguments when using search-project and I literally just installed all new laptop so no leftovers of any kind..

**Comment by maxandersen** [comment]
for what it is worth here is my stacktrace:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  counsel-more-chars(3)
  (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory counsel--git-grep-dir) (args (if (string-match-p " -- " string) (let ((split ...)) (prog1 (car-safe ...) (setq string ...))) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))
  (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory counsel--git-grep-dir) (args (if (string-match-p " -- " string) (let (...) (prog1 ... ...)) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))(--base-cmd-- "")
  apply((lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory counsel--git-grep-dir) (args (if (string-match-p " -- " string) (let ... ...) "")) (regex (counsel-unquote-regex-parens (setq ivy--old-re ...)))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil))) --base-cmd-- "")
  (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* ((default-directory counsel--git-grep-dir) (args ...) (regex ...)) (setq spacemacs--counsel-search-cmd (format ... args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) (quote --base-cmd--) --cl-rest--))("")
  ivy--reset-state(#s(ivy-state :prompt "%-4d ag from [/Users/max/Dropbox/notes/]: " :collection (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< ... 3) (counsel-more-chars 3) (let* ... ... ... nil)))) (quote --base-cmd--) --cl-rest--)) :predicate nil :require-match nil :initial-input "" :history counsel-git-grep-history :preselect nil :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :update-fn nil :sort nil :frame #<frame projects.org 0x1078101b0> :window #<window 3 on projects.org> :buffer #<buffer projects.org> :text nil :action (1 ("o" counsel-git-grep-action "default") ("i" #f(compiled-function (x) #<bytecode 0x52b6baad>) "insert") ("w" #f(compiled-function (x) #<bytecode 0x52b6babd>) "copy")) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)) :re-builder nil :matcher nil :dynamic-collection t :display-transformer-fn counsel-git-grep-transformer :directory "/Users/max/Dropbox/notes/" :caller spacemacs/counsel-search :current nil :def nil :ignore t :multi-action nil))
  ivy-read("%-4d ag from [/Users/max/Dropbox/notes/]: " (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (if (< (length string) 3) (counsel-more-chars 3) (let* (... ... ...) (setq spacemacs--counsel-search-cmd ...) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) (quote --base-cmd--) --cl-rest--)) :initial-input "" :dynamic-collection t :history counsel-git-grep-history :action counsel-git-grep-action :caller spacemacs/counsel-search :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)))
  (let ((tool (catch (quote tool) (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and ... ...) (progn ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw (quote tool) "grep")))) (setq counsel--git-grep-dir (or initial-directory (read-directory-name "Start from directory: "))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length counsel--git-grep-dir) spacemacs--counsel-search-max-path-length) counsel--git-grep-dir (concat "..." (substring counsel--git-grep-dir (- ... spacemacs--counsel-search-max-path-length) (length counsel--git-grep-dir)))))) (spacemacs//make-counsel-search-function tool) :initial-input (rxt-quote-pcre initial-input) :dynamic-collection t :history (quote counsel-git-grep-history) :action (function counsel-git-grep-action) :caller (quote spacemacs/counsel-search) :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))
  (let ((initial-input (if use-initial-input (if (region-active-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point (quote symbol) t)) ""))) (let ((tool (catch (quote tool) (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool ...) (if ... ...) (setq --dolist-tail-- ...))) (throw (quote tool) "grep")))) (setq counsel--git-grep-dir (or initial-directory (read-directory-name "Start from directory: "))) (ivy-read (concat ivy-count-format (format "%s from [%s]: " tool (if (< (length counsel--git-grep-dir) spacemacs--counsel-search-max-path-length) counsel--git-grep-dir (concat "..." (substring counsel--git-grep-dir ... ...))))) (spacemacs//make-counsel-search-function tool) :initial-input (rxt-quote-pcre initial-input) :dynamic-collection t :history (quote counsel-git-grep-history) :action (function counsel-git-grep-action) :caller (quote spacemacs/counsel-search) :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup))))))
  spacemacs/counsel-search(("ag" "pt" "ack" "grep") nil "/Users/max/Dropbox/notes/")
  spacemacs/search-project-auto()
  funcall-interactively(spacemacs/search-project-auto)
  call-interactively(spacemacs/search-project-auto nil nil)
  command-execute(spacemacs/search-project-auto)
```

**Comment by duianto** [comment]
The advice until the next version is released is to use the develop branch:
Change web page to install develop instead of master #12672
