### ISSUE TITLE
IOError(24, 'Too many open files') while editing python2 on windows 10

### ISSUE THREAD

**Issue by SirJls** [syl20bnr/spacemacs#11399]
#### Description :octocat:
Server error: InvalidPythonEnvironment("Could not get version information for 'c:\\\\Users\\\\jsparreb\\\\AppData\\\\Local\\\\Continuum\\\\anaconda2\\\\python.exe': IOError(24, 'Too many open files')",) [2 times]

#### Reproduction guide :beetle:
- Start Emacs
- Enable anaconda mode
- Edit python file of you choosing

*Observed behaviour:* :eyes: :broken_heart:
No autocompletion and slow editing experience.

*Expected behaviour:* :heart: :smile:
Autcompletion, faster editing experience.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults neotree
     (spell-checking :variables spell-checking-enable-by-default nil)
     syntax-checking restclient version-control
     (git :variables global-git-commit-mode t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (auto-completion :variables company-minimum-prefix-length 1 auto-completion-return-key-behaviour 'complete auto-completion-idle-delay 0.1 auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t)
     latex bibtex emacs-lisp python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
N/A

**Comment by aronla** [comment]
I also get this on OS X using python 3.

**Comment by beyondpie** [comment]
Try to update anaconda-mode, and jedi.  I have this problem before.
You can also kill the * *anaconda-mode* * buffer for a temporary solution.

**Comment by SirJls** [comment]
@beyondpie Thanks for the heads-up, but I kept bumping into strange functionality and errors, so I got myself started over with a clean sheet. Redoing  the installation steps I stumbled upon a completely new path with other [issues](https://github.com/proofit404/anaconda-mode/issues/329) and haven't encountered this error again, dunno what to do with this issue atm as I'm not able to reproduce it myself, but seeing the comments, it's still an issue for several of us here.

**Comment by cyber65535** [comment]
i also

**Comment by cyber65535** [comment]
I also get this on OS X using python 3, too. like @aronla 

I upgrade anaconda-mode:0.1.8 to anaconda-mode:0.1.11, that problem it's ok.

There were 335 processes before, and now it is maintained at 17, and on this issue, it is not useful for me to increase ulimit.

so, try upgrade your anaconda-mode to latest @SirJls

**Comment by d12frosted** [comment]
> Question: Should we close this issue and report upstream?

@SirJls No, do not close this issue, please. Let others see it even if it's an upstream issue. The best thing to do is to report this issue to the upstream and link it here, so everyone can easily track the progress.

But do you know what is better than the best? Keeping this thread up to date 😸 Once the upstream issue is resolved, you (or anyone else) can just ping me, so we close it.

---

@iromise thanks for the link. I want to ask a dummy question - where do you think this should be fixed? In anaconda or jedi?

**Comment by CarlQLange** [comment]
Here too. Looks like this is a jedi issue - I also get it when using the LSP backend rather than Anaconda.

**Comment by iromise** [comment]
@d12frosted I can not give the idea where the problem exits..  I think maybe if both anaconda and jedi 
 deal the opened file properly, there won't  be too many files opened. But, it is hard since sometimes it may really open many files. Maybe there should be some docs about how to tweak it.

**Comment by vv111y** [comment]
ditto
Nothing works 
	- treemacs can't open node
	- autosaves fail
	- can't open files
	- 'error running timer'	
	- can't check errors 
	- etc etc

**Comment by cyber65535** [comment]
anyone knows how take work of jedi or anaconda reset to which version

**Comment by Miciah** [comment]
A recent update to Anaconda mode changes it not to use keep-alive connections: https://github.com/proofit404/anaconda-mode/commit/0f8e86f723c2ef172947a94735c970065788f39b.  This change may mitigate "Too many open files" errors related to Anaconda mode.

**Comment by samspills** [comment]
The issue of too many open files was fixed in jedi release 0.13.2

**Comment by gregnwosu** [comment]
As an aside, how did you diagnose this was coming from anaconda? I seem to be getting the same issue but am unsure whether its coming from anaconda or another package. The closest I've come is doing something like ```watch -n 40 -d 'lsof -u greg | grep Emacs'

**Comment by syl20bnr** [comment]
Found this solution by @JeremyWeed here: https://github.com/palantir/python-language-server/issues/431#issuecomment-442918906

Seems to fix it for me.
May add it as a temporary work-around in Spacemacs for now.

**Comment by syl20bnr** [comment]
Nope it does not fix it for me unfortunately I just got the error again.
Seems we need to wait for a new release of jedi to fix, marked this a `Fixed upstream` but still need to be release.

Source: https://github.com/davidhalter/jedi/pull/1308

**Comment by syl20bnr** [comment]
For now I recommend to use `anaconda` back-end until this bug is fixed.

**Comment by samspills** [comment]
I believe versions of Jedi >= 0.13.2 have fixed this issue

**Comment by TomFaulkner** [comment]
Still suffering with this issue on a Mac in May of 2020.

**Comment by lebensterben** [comment]
@TomFaulkner Please report upstream.
