### ISSUE TITLE
org-refile does not work. org-copy-subtree: Invalid function: org-preserve-local-variables

### ISSUE THREAD

**Issue by Lchyang** [syl20bnr/spacemacs#11801]
Description 
org-refile does not work.

Reproduction guide 🐞
Start Emacs
Open an .org file
Go to a headline and try to refile by  , R
select a target 
Observed behaviour: 👀 💔
I get the following message: 
Getting targets...done
Copied: Subtree(s) with 22 characters
org-copy-subtree: Invalid function: org-preserve-local-variables

Expected behaviour: ❤️ 😄
refile could be used

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(markdown
 (ibuffer :variables ibuffer-group-buffers-by ’projects)
 (chinese :variables chinese-enable-youdao-dict t)
 auto-completion emacs-lisp
 (python :variables python-sort-imports-on-save t python-enable-yapf-format-on-save t)
 django org syntax-checking)
‘‘‘

my org config:

  (with-eval-after-load 'org

      (setq org-agenda-files '("~/org/gtd/inbox.org"
                              "~/org/gtd/gtd.org"
                              "~/org/gtd/tickler.org"))

      (setq org-capture-templates '(("t" "Todo [inbox]" entry
                                    (file+headline "~/org/gtd/inbox.org" "Tasks")
                                    "* TODO %i%?")
                                    ("T" "Tickler" entry
                                    (file+headline "~/org/gtd/tickler.org" "Tickler")
                                    "* %i%? \n %U")))

      (setq org-refile-targets
              '((nil :maxlevel . 3)
              (org-agenda-files :maxlevel . 3)))

      (setq org-refile-use-outline-path 'file)

      (setq org-outline-path-complete-in-steps nil)

      (setq org-todo-keywords '((sequence "TODO(t)" "WAITING(w)" "|" "DONE(d)" "CANCELLED(c)")))

**Comment by samspills** [comment]
This is probably the same as here: https://github.com/syl20bnr/spacemacs/issues/11788

Could you try removing all org*/*.elc files from your elpa directory and recompile? I did the following:
```shell
cd ~/.emacs.d/elpa/develop
find org*/*.elc -print0 | xargs -0 rm
```
and then inside spacemacs I ran `spacemacs/recompile-elpa`.

**Comment by Lchyang** [comment]
Thank you very much, I used the master branch.
I did this:
cd ~/.emacs.d/elpa
find org*/*.elc -print0 | xargs -0 rm

and the problem is solved.

**Comment by Lchyang** [comment]
problem is solved.

**Comment by snuffop** [comment]
Just a Note: even after installing  ~/.emacs.d fresh, one needs to still follow the above after installed.

**Comment by breadncup** [comment]
I believe this is a bug in org or org-refile somewhere. Why does removing the byte compiled files resolve the issue? It's ridiculous. Shouldn't everything work fine with byte compiled one as well?

**Comment by snuffop** [comment]
Your right.  I believe that it May have something to do with load order or the recompile after update reads in previously uncompiled code.   Not sure.

**Comment by skrobul** [comment]
Had the same error, but with `org-gcal` instead. Running the commands above did not help, so I decided  to nuke all `*.elc` files in `~/.emacs.d`,  then ran `spacemacs/recompile-elpa` and the problem is gone.

**Comment by lsyoyo** [comment]
@samspills I did what you mentioned in your comment, and I even did what @skrobul suggested, I still have issue, any suggestions?

**Comment by liny01-nbsa** [comment]
I moved up one directory level (`~/.emacs.d/elpa`) and then did the steps again, after that it worked.

**Comment by lsyoyo** [comment]
I moved up one directory level (`~/.emacs.d/elpa`) and then did the steps again, after that it worked.

**Comment by sydneyweidman** [comment]
> Had the same error, but with `org-gcal` instead. Running the commands above did not help, so I decided to nuke all `*.elc` files in `~/.emacs.d`, then ran `spacemacs/recompile-elpa` and the problem is gone.

I'm running develop on Ubuntu 18.06 and this was the only thing that worked for me.
Even removing the elc files from .emacs.d/elpa didn't work. Had to do the whole tree from .emacs.d on down.

**Comment by jscott22** [comment]
> > Had the same error, but with `org-gcal` instead. Running the commands above did not help, so I decided to nuke all `*.elc` files in `~/.emacs.d`, then ran `spacemacs/recompile-elpa` and the problem is gone.
> 
> I'm running develop on Ubuntu 18.06 and this was the only thing that worked for me.
> Even removing the elc files from .emacs.d/elpa didn't work. Had to do the whole tree from .emacs.d on down.

This worked for me, thanks!!

**Comment by bleggett** [comment]
This needs to be reopened, there is a workaround, but the core issue has not been resolved in Spacemacs yet.

Looks like it was fixed in `doom-emacs` thusly:
https://github.com/hlissner/doom-emacs/commit/574dae14261d7666d99b5bea73d8d1442fbd8268

**Comment by psamim** [comment]
I completely cloned spacemacs, removed whole elpa directory and installed everything and still have this issue.

**Comment by fabrik42** [comment]
Hi! Another hint for the people that still face problems:

I am using the `emacs-plus` homebrew formula with the new version 26.2. 

I didn't find `.elc` files to delete and `spacemacs/recompile-elpa` didn't recompile anything (just warnings and skippings).

The reason was that I needed to delete the `.elc` files in another directory:

```sh
cd ~/.emacs.d/elpa/26.2/develop
find org*/*.elc -print0 | xargs -0 rm
```

Then run `spacemacs/recompile-elpa` - refile away!

**Comment by jkonecny12** [comment]
As already told in https://github.com/syl20bnr/spacemacs/issues/11801#issuecomment-483764388 cloud you please re-open this issue?

**Comment by kutsurak** [comment]
Hi all,

I removed all the `.elc` files under `~/.emacs.d/`, but `spacemacs/recompile-elpa` did not recompile anything. I had to evaluate the following s-exp: `(byte-recompile-directory "~/.emacs.d/elpa" 0 t)`. The version shown in the `*spacemacs*` buffer is  0.200.13@26.2

**Comment by kepi** [comment]
It would be great to have this resolved. Currently I'm simply updating spacemacs after every package update like this:

1. update packages
2. exit spacemacs
3. run spacemacs git update with this "oneliner":
  ```sh
  cd ~/.emacs.d && git pull --rebase; find ~/.emacs.d/elpa/2*/develop/org-plus-contrib* -name '*.elc' -delete # update spacemacs
  ```

**Comment by Technologicat** [comment]
Happens with `org-sort-entries` too.

Nuking all `.elc` files under `~/.emacs.d` and then running `M-x spacemacs/recompile-elpa` helped, as suggested by @skrobul . Incantation used: `cd ~/.emacs.d && find . -name *.elc -print0 | xargs -0 rm`

**Comment by LorenRiccie** [comment]
Worked
(Emacs 26.1, master  branch on Debian Buster)

**Comment by Zlopez** [comment]
I'm using the latest develop and wasn't able to do `org-archive-subtree` and instead got this error.

I recompiled the files and this fixed it.

**Comment by plajjan** [comment]
+1, @Technologicat incantation worked to fix the org-refile issue.

**Comment by andrewjesaitis** [comment]
Just to echo @breadncup's comment. I'm not using spacemacs, but use emacs26 and org-mode and this happens to me every once in a while. After googling, I always end up hitting this thread and just deleting all *.elc files in my elpa directory fixes it. So my guess is this isn't a spacemacs issue, something in org-mode itself.

**Comment by emacs18** [comment]
It appears that there is a potential problem when updating any elisp package.
This was recently discussed in emacs-devel list.  I quote one of he emails below.

What emacs developers seem to need is specific examples of the problems.
If folks can provide step by step detail on how to reproduce the problems and
share that with emacs developers, then this problem might get resolved once and for all.
Otherwise we all have to work around this problem.

```
From: Stefan Kangas <stefan@marxist.se>
Subject: Re: org 9.2.6 and org 9.1.9
Newsgroups: gmane.emacs.orgmode, gmane.emacs.devel
To: Tim Cross <theophilusx@gmail.com>
Cc: Jean-Christophe Helary <jean.christophe.helary@traduction-libre.org>, Org-mode <emacs-orgmode@gnu.org>, Emacs developers <emacs-devel@gnu.org>
Date: Wed, 27 Nov 2019 11:11:40 +0100 (4 days, 4 hours, 50 minutes ago)

Tim Cross <theophilusx@gmail.com> writes:

> What is really needed to fix this problem is some mechanism which
> will ensure all org related definitions are somehow purged from the
> running instance before attempting to install and compile a new
> version.

That could be one way of going about it.  Other solutions have been
discussed in Bug#10125, for example here:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=10125#59

> But I don't think the issue is with package.el per se. You get the
> same problem if you try to install org-mode manually without
> package.el.
[...]
> Provided there is no org-mode functionality loaded when you install
> a later version with package.el, it works fine.

As far as I understand, the bug in package.el is that you can't always
successfully install a later version of a package after it has been
loaded.  In this case, Org-mode fails to install properly.

Best regards,
Stefan Kangas
```

**Comment by thanhvg** [comment]
For those who are on dev branch and encounter this bug can you try this work around:

Open any org file in Spacemacs (to make sure `org-mode` is fully loaded), do `spc h p` and search for `org-plus-contrib (owner: spacemacs-org layer)`. Once you have found it: 

- `F3` or
- `C-z` choose `Recompile`

Restart Spacemace. Hope the problem is gone then. This is a convenient way to recompile a package instead of doing it manually on both command line and emacs.

**Comment by Zlopez** [comment]
@thanhvg I tried it and here is the output:
* `F3` - macro not defined
* `C-z` - does something, but not what expected

I was able to find recompile under `SPC-c-r`, but this just throws error:
```
-*- mode: compilation; default-directory: "~/.emacs.d/layers/+spacemacs/spacemacs-org/" -*-
Compilation started at Mon Dec 16 14:14:09

make -k 
/bin/bash: make: command not found

Compilation exited abnormally with code 127 at Mon Dec 16 14:14:09
```

**Comment by ambantis** [comment]
Using the current version (20191230), I get this problem both in osx and linux (arch linux). When I checkout the org-mode and use the 9.3.1 tag and compile, this error goes away (both in osx and linux).

**Comment by Jeel-Shah** [comment]
Hi all,

I encountered the same problem (Spacemacs Release 0.200.13.x). 

1. I ran `find . -name *.elc -print0 | xargs -0 rm`

It said that it didn't find any `.elc` files. But, I called `spacemacs/recompile-elpa` anyway. It successfully recompiled and the issue was resolved. I would suggest trying the second step independent of the result in the first.

**Comment by breadncup** [comment]
Unbelievable! This ticket has been a year, but it is still opened. :)

**Comment by emacs18** [comment]
@duianto  mentioned #12829 which has more details on the problem which is that updating packages in emacs is not a reliable process especially for older emacs versions and especially for org mode.

I think this is a hard problem to solve.  That I think is why emacs developers have not yet solved it.
However improvements have been made in emacs and in org mode so that the problem is less frequent in more modern versions of emacs and org-mode.

I would not expect spacemacs folks to solve this difficult problem which even emacs developers are having difficulty solving. The best bet is to use one of the many work arounds suggested by others.  My own work around is to delete org-plus-contrib package (and others), then make sure that it is installed on startup before there is any possibility of loading any org mode related files.

**Comment by LambdaP** [comment]
> @thanhvg I tried it and here is the output:
> 
>     * `F3` - macro not defined
> 
>     * `C-z` - does something, but not what expected
> 
> 
> I was able to find recompile under `SPC-c-r`, but this just throws error:
> 
> ```
> -*- mode: compilation; default-directory: "~/.emacs.d/layers/+spacemacs/spacemacs-org/" -*-
> Compilation started at Mon Dec 16 14:14:09
> 
> make -k 
> /bin/bash: make: command not found
> 
> Compilation exited abnormally with code 127 at Mon Dec 16 14:14:09
> ```

I am having the exact same problem. Did you find a way out of this error?

**Comment by thanhvg** [comment]
@LambdaP do you use `helm` or `ivy`? My solution is only available for `helm` :(

**Comment by LorenRiccie** [comment]
Got the problem again with emacs 26.3 creating a footnote in an orgmode file. 

`cd ~/.emacs.d/elpa/
find org*/*.elc -print0 | xargs -0 rm`

Then recompilation of the directory via Emacs fixed the error :)

**Comment by rafonseca** [comment]
on 0.200.13@26.3 (spacemacs),
`M-x spacemacs/recompile-elpa`
also works, at least for now.

**Comment by Zlopez** [comment]
I hit the issue again today and solution from @LorenRiccie helped.

**Comment by clyton** [comment]
I too faced the same issue. Deleting the .elc files and recompiling does not solve the error. I also tried recompiling just the org-plus-contrib package and it still does not work. Here is my system info

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 275b519f0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python
 (javascript :variables javascript-import-tool 'import-js :variables javascript-fmt-tool 'prettier :variables javascript-fmt-on-save t :variables node-add-modules-path t :variables javascript-backend 'lsp)
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 (ruby :variables ruby-backend 'lsp)
 emacs-lisp imenu-list git helm lsp dap multiple-cursors org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by jkonecny12** [comment]
Issue is still present. I hit it by updating packages from the main screen.

**Comment by Caffa** [comment]
I'm on mac, so what I did was 
`find . | grep "org*.elc"$ | while read -r line ; do rm -rf $line ;done`
then recompile in spacemacs

**Comment by undefiened** [comment]
> > @thanhvg I tried it and here is the output:
> > ```
> > * `F3` - macro not defined
> > 
> > * `C-z` - does something, but not what expected
> > ```
> > 
> > 
> > I was able to find recompile under `SPC-c-r`, but this just throws error:
> > ```
> > -*- mode: compilation; default-directory: "~/.emacs.d/layers/+spacemacs/spacemacs-org/" -*-
> > Compilation started at Mon Dec 16 14:14:09
> > 
> > make -k 
> > /bin/bash: make: command not found
> > 
> > Compilation exited abnormally with code 127 at Mon Dec 16 14:14:09
> > ```
> 
> I am having the exact same problem. Did you find a way out of this error?

A bit too late response, but still leave it in case anyone needs it: I did not press `Enter` after searching for org-plus-contrib (so I stayed in `helm` or whatever it is), just pressed `F3` and recompilation started.

**Comment by nickanderson** [comment]
Deleting all the elc files in `~/.emacs.d/elpa/VERSION/develop` restarting and running `spacemacs/recompile-elpa`  was unsuccessful for me today.

**Comment by Prometheus77** [comment]
I was able to solve in Windows with the org-plus-contrib + F3 to recompile solution; however, a workaround is only a workaround. If we have definitely traced the issue to an org-mode bug, is there an open issue on org-mode's github?

**Comment by lebensterben** [comment]
For future reference, please use the solution [here](https://github.com/syl20bnr/spacemacs/issues/11801#issuecomment-451755821).
