### ISSUE TITLE
Is it able to show the index of the recent files/projects in spacemacs home page?

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#12519]
It is more convenient to display the index of the recent files/projects in spacemacs home page (**spacemacs** buffer) like space-vim/SpaceVim, and I can just hit the index character in the home page to open the file/project directly.

![vim](https://user-images.githubusercontent.com/2135996/61017879-65029c00-a3c7-11e9-8e1c-8d1605fcc860.png)

**Comment by duianto** [comment]
There is a similar feature already.
Pressing `o` calls `spacemacs/ace-buffer-links` which shows one or two letters at the start of every link, pressing those letters opens the selected link.

**Comment by c02y** [comment]
Didn't know that, thanks.

The index displayed automatically in spacemacs buffer is more convenient, and I don't have to type another few keys to open the file like using `o`(`spacemacs/ace-buffer-links`)

**Comment by duianto** [comment]
Agreed, it would be simpler to have a visible single target key.

**Comment by duianto** [comment]
A PR has been opened with a possible solution:
Add home buffer recent files numbers #14326

**Comment by duianto** [comment]
The PR has been merged.
@c02y You can close this if it works as expected now.

**Comment by lebensterben** [comment]
@duianto 
However, if you choose to display recent files by projects, the indices are not shown.

**Comment by duianto** [comment]
How should the numbers be listed when the recent files by project is used?

Listing them from top to bottom is likely to run out of numbers before the last project, when there are several projects.

Another "tricky" case is when both the recent files and recent files by project are shown.

**Comment by duianto** [comment]
I just remember that you had a suggestion here:
https://github.com/syl20bnr/spacemacs/pull/14326#issuecomment-769296614
>For example, r N goes to N-th recent file, and p N goes to N-th project etc.

**Comment by c02y** [comment]
Thanks, the PR works, but as https://github.com/syl20bnr/spacemacs/pull/14326#issuecomment-794891496 said, there is a bug.

And just like you said, another problem is there is no index for other items when 9 number keys are run out.

**Comment by duianto** [comment]
That bug should have been fixed in:
Open home buffer recent files in expected order #14474

I don't know how we should handle shortcuts when the 9 number keys run out.

Adding a two key sequence, matches the current behavior when `o` (`spacemacs/ace-buffer-links`) is pressed.
(As stated above: https://github.com/syl20bnr/spacemacs/issues/12519#issuecomment-510564073)

**Comment by c02y** [comment]
`The home buffers recent files list is only updated when the home buffer is created/refreshed/resized.` from https://github.com/syl20bnr/spacemacs/pull/14474#issue-590916918 Yeah, but you still have to trigger it to update the list in home buffer.

> I don't know how we should handle shortcuts when the 9 number keys run out.

Maybe check the screenshot of the original post on this page?

**Comment by duianto** [comment]
>Yeah, but you still have to trigger it to update the list in home buffer.

Ok, then we probably need to refresh the home buffer when a file is saved.
I posted a WIP snippet here: https://github.com/syl20bnr/spacemacs/pull/14326#issuecomment-796609112
```elisp
    (defun spacemacs-buffer/refresh-in-other-window ()
      (when (get-buffer-window spacemacs-buffer-name)
        (save-selected-window
          (switch-to-buffer-other-window spacemacs-buffer-name)
          (spacemacs-buffer/refresh))))

    (add-hook 'after-save-hook 'spacemacs-buffer/refresh-in-other-window)
    ;; (remove-hook 'after-save-hook 'spacemacs-buffer/refresh-in-other-window)
```

>Maybe check the screenshot of the original post on this page?

Your right, that makes sense.

I was to focused on the suggestion to press `r N` and `p N`.
That would have been somewhat similar to pressing: `o` `<letter(s)>`

**Comment by c02y** [comment]
> I was to focus on the suggestion to press r N and p N.
That would have been somewhat similar to pressing: o <letter(s)>

Yeah, you can highlight an extra letter for every different type of the list in the Home buffer, and add an index for every type from 1-9, but this doesn't solve the 9-numbers-run-out issue since I can set a number bigger than 9 for a type such as I set `(recents . 10)`

Actually I can just use `o calls spacemacs/ace-buffer-links` https://github.com/syl20bnr/spacemacs/issues/12519#issuecomment-510564073 , if there is no simpler way.

**Comment by lebensterben** [comment]
@duianto 
The behaviour in `SpaceVim` is that, say there's one item indexed with `1` and another `11`,
- When you press `1`, and quickly press `1` again, it goes to `11`-th item
- If you press `1`, without additional input within a certain threshold, it goes to `1`-st item

**Comment by lebensterben** [comment]
I personally is don't even do `o <letter>`..
I either do `:e <full path>` or `SPC f r`...
Why? Because I type really fast.

**Comment by duianto** [comment]
Here's an initial attempt. Any suggestions are always welcome.

If there is a longer delay than 1 second, between key presses,
then the cursor jumps to the line that starts with that single number.

Otherwise (< 1 sec between key presses):
The cursor jumps to the two digit number.

Some testing lines:
```
1 a
2 a
3 a
...
10 a
11 a
12 a
13 a
...
20 a
21 a
22 a
23 a
...
30 a
31 a
32 a
33 a
```

```elisp
(define-key evil-normal-state-map (kbd "0")
  #'(lambda () (interactive)
      (when custom/additional-numbers-timer
        (cancel-timer custom/additional-numbers-timer))
      (cond ((and (looking-at (custom/re-line-starts-with-nr-space 1))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 10))
            ((and (looking-at (custom/re-line-starts-with-nr-space 2))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 20))
            ((and (looking-at (custom/re-line-starts-with-nr-space 3))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 30))
            ;; TODO should the 0 key alone, do something?
            ;; (t)
            )
      (setq custom/wait-for-additional-numbers t)
      (setq custom/additional-numbers-timer
            (run-with-timer 1 nil 'custom/stop-waiting-for-additional-numbers))))

(define-key evil-normal-state-map (kbd "1")
  #'(lambda () (interactive)
      (when custom/additional-numbers-timer
        (cancel-timer custom/additional-numbers-timer))
      (cond ((and (looking-at (custom/re-line-starts-with-nr-space 1))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 11))
            ((and (looking-at (custom/re-line-starts-with-nr-space 2))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 21))
            ((and (looking-at (custom/re-line-starts-with-nr-space 3))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 31))
            (t (custom/jump-to-line-starting-with-nr-space 1)))
      (setq custom/wait-for-additional-numbers t)
      (setq custom/additional-numbers-timer
            (run-with-timer 1 nil 'custom/stop-waiting-for-additional-numbers))))

(define-key evil-normal-state-map (kbd "2")
  #'(lambda () (interactive)
      (when custom/additional-numbers-timer
        (cancel-timer custom/additional-numbers-timer))
      (cond ((and (looking-at (custom/re-line-starts-with-nr-space 1))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 12))
            ((and (looking-at (custom/re-line-starts-with-nr-space 2))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 22))
            ((and (looking-at (custom/re-line-starts-with-nr-space 3))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 32))
            (t (custom/jump-to-line-starting-with-nr-space 2)))
      (setq custom/wait-for-additional-numbers t)
      (setq custom/additional-numbers-timer
            (run-with-timer 1 nil 'custom/stop-waiting-for-additional-numbers))))

(define-key evil-normal-state-map (kbd "3")
  #'(lambda () (interactive)
      (when custom/additional-numbers-timer
        (cancel-timer custom/additional-numbers-timer))
      (cond ((and (looking-at (custom/re-line-starts-with-nr-space 1))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 13))
            ((and (looking-at (custom/re-line-starts-with-nr-space 2))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 23))
            ((and (looking-at (custom/re-line-starts-with-nr-space 3))
                  custom/wait-for-additional-numbers)
             (custom/jump-to-line-starting-with-nr-space 33))
            (t (custom/jump-to-line-starting-with-nr-space 3)))
      (setq custom/wait-for-additional-numbers t)
      (setq custom/additional-numbers-timer
            (run-with-timer 1 nil 'custom/stop-waiting-for-additional-numbers))))


(defun custom/re-line-starts-with-nr-space (nr)
  (concat "^\s?*" (number-to-string nr) " "))

(defun custom/jump-to-line-starting-with-nr-space (nr)
  (goto-char (point-min))
  (re-search-forward (custom/re-line-starts-with-nr-space nr))
  (back-to-indentation)
  (custom/test-passed-or-failed
   (looking-at (custom/re-line-starts-with-nr-space nr))))

(defun custom/test-passed-or-failed (test)
  "Fill the minibuffer with a color based on the test result
green: passed
red:   failed"
  (message "%s" (propertize
                 (make-string (frame-width) (string-to-char " "))
                 'face `(:background ,(if test "green" "red")))))

(defvar custom/wait-for-additional-numbers nil)
(defvar custom/additional-numbers-timer nil)

(defun custom/stop-waiting-for-additional-numbers ()
  (setq custom/wait-for-additional-numbers nil)
  ;; clear minibuffer, it has a color if a test ran
  (message "%s" (propertize
                 (make-string (frame-width) (string-to-char " "))
                 'face `(:background (face-attribute 'default :background)))))
```

**Comment by duianto** [comment]
I figured out how to add consecutive numbers to the startup lists.

![emacs_2021-03-20_11-56-27](https://user-images.githubusercontent.com/13420573/111867325-7f01c980-8973-11eb-87df-2af961ea1c67.png)

**Comment by c02y** [comment]
It works for me.

**Comment by lebensterben** [comment]
let's make the time window as long as which-key's (which is configutable in dotspacemacs), in case some users have difficulty to press fast enough.

**Comment by duianto** [comment]
A PR has been opened:
[home] Add multi-digit numbers to the startup lists #14538

The two key delay is the same as the which-key delay: `0.4` seconds.
It can be modified with the variable: `spacemacs-buffer-multi-digit-delay`
