### ISSUE TITLE
search functionality appears to be broken in ivy.

### ISSUE THREAD

**Issue by 8i8** [syl20bnr/spacemacs#12838]
On a fresh install when using ivy, on both the master and the develop branch a similar error is occurring: All of the search realated functions seem to be having an issue, Spc s g P for example does not pick up the token at point and launches an error when characters are entered.
The following error is produced : Error in post-command-hook (ivy--queue-exhibit): (file-missing "Setting current directory" "No such file or directory" "tempFilename")

Here is an debug-on-error output created when using search-project-auto-region-or-symbol : 

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\\(.*?\\):\\([0-9]+\\):\\(.*\\)\\'" nil)
  counsel-git-grep-action(nil)
  ivy-call()
  ivy-read("grep from [/home/iain/go/src/pranava/]: " (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (or (ivy-more-chars) (let* ((default-directory (ivy-state-directory ivy-last)) (args (if (string-match-p " -- " string) (let ((split (split-string string " -- "))) (prog1 (car-safe (prog1 split (setq split (cdr split)))) (setq string (mapconcat (function identity) split " -- ")))) "")) (regex (counsel--elisp-to-pcre (setq ivy--old-re (ivy--regex string))))) (setq spacemacs--counsel-search-cmd (format (symbol-value G0) args regex)) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) '--base-cmd-- --cl-rest--)) :initial-input "Command" :dynamic-collection t :history counsel-git-grep-history :action counsel-git-grep-action :caller spacemacs/counsel-search :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)))
  (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))
  (let ((tool (catch 'tool (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and (assoc-string tool spacemacs--counsel-commands) (executable-find tool)) (progn (throw 'tool tool))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw 'tool "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup))))))
  (let ((initial-input (if use-initial-input (if (region-active-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol t)) ""))) (let ((tool (catch 'tool (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and (assoc-string tool spacemacs--counsel-commands) (executable-find tool)) (progn (throw 'tool tool))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw 'tool "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory))))) (spacemacs//make-counsel-search-function tool) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history 'counsel-git-grep-history :action (function counsel-git-grep-action) :caller 'spacemacs/counsel-search :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))))
  spacemacs/counsel-search(("rg" "ag" "pt" "ack" "grep") t "/home/iain/go/src/pranava/")
  spacemacs/search-project-auto-region-or-symbol()
  funcall-interactively(spacemacs/search-project-auto-region-or-symbol)
  call-interactively(spacemacs/search-project-auto-region-or-symbol nil nil)
  command-execute(spacemacs/search-project-auto-region-or-symbol)

**Comment by duianto** [comment]
`Spc s g P` adds the symbol under the cursor to the prompt for me on the `master` branch.

#### Reproduction steps
- open `c:/Users/username/.emacs.d/.gitignore`
- with the cursor on the first line `auto-save-list/`
- press: `SPC s g P`
The prompt shows:
```
1    git grep: auto-save-list/
```

But a lot/most of the other search commands seem to be broken on the `master` branch.
For example, pressing `SPC /` in the same `.gitignore` file, shows:
>if: Wrong number of arguments: (0 . 0), 1`

It's been reported before:
Bug: ivy/counsel: Wrong number of arguments searching with `spacemacs/search-project-*` #11048

It's marked as `fixed in develop`.

There was also a recent change to the ivy package, that removed the alias `counsel-more-chars` which was pointing to the current command `ivy-more-chars`.

That has been reported and fixed on the `develop` branch:
symbol-highlight impact (void-function counsel-more-chars) error. #12828

The `if: Wrong number of arguments: (0 . 0), 1` error message probably masks the `counsel-more-chars` error message.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git ivy html javascript markdown org python shell spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by yuhan0** [comment]
Ivy-occur functionality is also broken, `C-c C-o` produces the error

```
Debugger entered--Lisp error: (wrong-number-of-arguments (lambda nil "Generate a custom occur buffer for `counsel-git-grep'." (ivy-occur-grep-mode) (setq default-directory (ivy-state-directory ivy-last)) (insert (format "-*- mode:grep; default-directory: %S -*-\n\n\n" default-directory)) (insert (format "%d candidates:\n" (length cands))) (ivy--occur-insert-lines (mapcar (lambda (cand) (concat "./" cand)) cands))) 1)
  spacemacs//counsel-occur((#("./layers/+completion/ivy/packages.el:228:      ;;                'spacemacs//counsel-occur" 0 36 (face ivy-grep-info) 37 40 (face ivy-grep-line-number)) #("./layers/+completion/ivy/packages.el:231:        :occur 'spacemacs//counsel-occur)" 0 36 (face ivy-grep-info) 37 40 (face ivy-grep-line-number)) #("./layers/+completion/ivy/funcs.el:327:(defun spacemacs//counsel-occur (&optional cands)" 0 33 (face ivy-grep-info) 34 37 (face ivy-grep-line-number))))
  ivy-occur()
  funcall-interactively(ivy-occur)
  call-interactively(ivy-occur nil nil)
  command-execute(ivy-occur)
  read-from-minibuffer("rg from [...rnal_repos/spacemacs/.emacs.d/]: " "" (keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) keymap (escape . minibuffer-keyboard-quit) (12 . ivy-alt-done) (33554440 keymap (113 . help-quit) (118 . describe-variable) (119 . where-is) (116 . help-with-tutorial) (115 . describe-syntax) (114 . info-emacs-manual) (80 . describe-package) (112 . finder-by-keyword) (110 . view-emacs-news) (111 . describe-symbol) (109 . describe-mode) (108 . view-lossage) (107 . describe-key) (52 keymap (105 . info-other-window)) (105 . info) (104 . view-hello-file) (103 . describe-gnu-project) (102 . describe-function) (101 . view-echo-area-messages) (100 . apropos-documentation) (99 . describe-key-briefly) (98 . describe-bindings) (97 . apropos-command) (83 . info-lookup-symbol) (76 . describe-language-environment) (75 . Info-goto-emacs-key-command-node) (73 . describe-input-method) (70 . Info-goto-emacs-command-node) (67 . describe-coding-system) (28 . describe-input-method) (23 . describe-no-warranty) (20 . view-emacs-todo) (16 . view-emacs-problems) (15 . describe-distribution) (14 . view-emacs-news) (13 . view-order-manuals) (6 . view-emacs-FAQ) (5 . view-external-packages) (4 . view-emacs-debugging) (3 . describe-copying) (1 . about-emacs) (63 . help-for-help) (46 . display-local-help) (f1 . help-for-help) (help . help-for-help) (8 . help-for-help)) (8 . "\177") (11 . ivy-previous-line) (36 . ivy-magic-read-file-env) (3 keymap (19 . ivy-rotate-sort) (1 . ivy-toggle-ignore) (15 . ivy-occur)) (67108903 . ivy-avy) (33554464 . ivy-restrict-to-matches) (15 . spacemacs/ivy-transient-state/body) (22 . ivy-scroll-up-command) (prior . ivy-scroll-down-command) (next . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-forward-char) (32 . self-insert-command) (18 . ivy-reverse-i-search) (19 . ivy-next-line-or-history) (remap keymap (describe-mode . ivy-help) (kill-ring-save . ivy-kill-ring-save) (kill-whole-line . ivy-kill-whole-line) (kill-line . ivy-kill-line) (scroll-down-command . ivy-scroll-down-command) (scroll-up-command . ivy-scroll-up-command) (end-of-buffer . ivy-end-of-buffer) (beginning-of-buffer . ivy-beginning-of-buffer) (kill-word . ivy-kill-word) (forward-char . ivy-forward-char) (delete-char . ivy-delete-char) (backward-kill-word . ivy-backward-kill-word) (backward-delete-char-untabify . ivy-backward-delete-char) (delete-backward-char . ivy-backward-delete-char) (previous-line . ivy-previous-line) (next-line . ivy-next-line)) (9 . ivy-partial-or-done) (10 . ivy-next-line) (27 keymap (8388640 . spacemacs/ivy-transient-state/body) (32 . hydra-ivy/body) (1 . ivy-read-action) (15 . ivy-dispatching-call) (111 . ivy-dispatching-done) (25 . ivy-insert-current-full) (105 . ivy-insert-current) (106 . ivy-yank-word) (114 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (10 . ivy-immediate-done) (13 . ivy-call)) (mouse-3 . ivy-mouse-dispatching-done) (mouse-1 . ivy-mouse-done) (down-mouse-1 . ignore) (13 . ivy-done)) nil counsel-git-grep-history)
  ivy-read("rg from [...rnal_repos/spacemacs/.emacs.d/]: " (lambda (&rest --cl-rest--) "Grep in the current directory for STRING." (apply (function (lambda (G0 string &optional _pred &rest _unused) (or (ivy-more-chars) (let* (... ... ...) (setq spacemacs--counsel-search-cmd ...) (spacemacs//counsel-async-command spacemacs--counsel-search-cmd) nil)))) (quote --base-cmd--) --cl-rest--)) :initial-input "" :dynamic-collection t :history counsel-git-grep-history :action counsel-git-grep-action :caller spacemacs/counsel-search :keymap (keymap (3 keymap (5 . spacemacs//counsel-edit)) (f3 . spacemacs//counsel-save-in-buffer)) :unwind (lambda nil (counsel-delete-process) (swiper--cleanup)))
  (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- (length default-directory) spacemacs--counsel-search-max-path-length) (length default-directory))))) (spacemacs//make-counsel-search-function tool (if (consp current-prefix-arg) spacemacs--alt-counsel-commands spacemacs--counsel-commands)) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history (quote counsel-git-grep-history) :action (function counsel-git-grep-action) :caller (quote spacemacs/counsel-search) :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))
  (let ((tool (catch (quote tool) (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool (car --dolist-tail--)) (if (and ... ...) (progn ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (throw (quote tool) "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory (- ... spacemacs--counsel-search-max-path-length) (length default-directory))))) (spacemacs//make-counsel-search-function tool (if (consp current-prefix-arg) spacemacs--alt-counsel-commands spacemacs--counsel-commands)) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history (quote counsel-git-grep-history) :action (function counsel-git-grep-action) :caller (quote spacemacs/counsel-search) :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup))))))
  (let ((initial-input (if use-initial-input (if (region-active-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point (quote symbol) t)) ""))) (let ((tool (catch (quote tool) (let ((--dolist-tail-- tools) tool) (while --dolist-tail-- (setq tool ...) (if ... ...) (setq --dolist-tail-- ...))) (throw (quote tool) "grep")))) (let ((default-directory (or initial-directory (read-directory-name "Start from directory: ")))) (ivy-read (format "%s from [%s]: " tool (if (< (length default-directory) spacemacs--counsel-search-max-path-length) default-directory (concat "..." (substring default-directory ... ...)))) (spacemacs//make-counsel-search-function tool (if (consp current-prefix-arg) spacemacs--alt-counsel-commands spacemacs--counsel-commands)) :initial-input (if initial-input (progn (rxt-quote-pcre initial-input))) :dynamic-collection t :history (quote counsel-git-grep-history) :action (function counsel-git-grep-action) :caller (quote spacemacs/counsel-search) :keymap spacemacs--counsel-map :unwind (function (lambda nil (counsel-delete-process) (swiper--cleanup)))))))
  spacemacs/counsel-search(("rg" "ag" "pt" "ack" "grep") nil "/Users/yuhan/dotfiles/external_repos/spacemacs/.emacs.d/")
  spacemacs/search-project-auto()
  funcall-interactively(spacemacs/search-project-auto)
  call-interactively(spacemacs/search-project-auto nil nil)
  command-execute(spacemacs/search-project-auto)
```

It appears to be due to a recent change in custom occur functions, `spacemacs//counsel-occur`  should take an optional `cands` argument

**Comment by cormacc** [comment]
Hacking spacemacs//counsel-occur to take an ignored optional argument gives the following:
`let: Buffer is read-only: #<buffer *ivy-occur spacemacs/counsel-search "from flask_babel import gettext"*>`

**Comment by cormacc** [comment]
This issue isn't restricted to the master branch BTW -- I'm on develop.

**Comment by Caribpa** [comment]
In #12865 I have fixed `SPC s g P` and `ivy-occur` (@cormacc you almost got it, the only thing missing was adding `inhibit-read-only t` to ignore the read-only buffer).

@duianto unfortunately I cannot reproduce the issue with `counsel-more-chars` - `ivy-more-chars` as `SPC /` and all the `spacemacs/search-project-*` work as expected on my setup (Linux), but I'll try to test it on a clean installation to see if there's any difference.

**Comment by duianto** [comment]
@Caribpa The `counsel-more-chars` issue only occurs on the `master` branch.
It's been fixed on the `develop` branch. With this commit: https://github.com/syl20bnr/spacemacs/commit/98e7bf38ad41c535e15aca91fede2f57d3879773

**Comment by duianto** [comment]
The following PRs changes are now on the develop branch:
Ivy layer bugfixes for #12838 #12865

**Comment by 8i8** [comment]
This is great, really nice to be back on ivy; The issue is still occurring on the Spc s g P for me here though it is very functional still even with this.
I get the following error:
Error in post-command-hook (ivy--queue-exhibit): (file-missing "Setting current directory" "No such file or directory" "mux")

**Comment by duianto** [comment]
@8i8 Could you post your system info, press `SPC h d s` to copy it to the clipboard.
That might narrow down the cause.

`SPC s g P` works for me without errors in both Pop!_OS 19.10 and Windows 1903 on the Spacemacs `develop` branch with updated packages.

**Comment by Caribpa** [comment]
It seems that counsel-search is broken `SPC s f` as it ignores the directory selected by the user. I'll fix it shortly.

**Comment by duianto** [comment]
Confirmed, it was caused by the changes in this PR:
Optimize =spacemacs/counsel-search= for =ag= and =rg= #12885
I checked out the commit before it and `SPC s f` works as expected.

**Comment by Caribpa** [comment]
Fixed in this commit: https://github.com/syl20bnr/spacemacs/pull/12867/commits/177b4f8b82152437ec32f51c8e81f5bcdfe1cecf from PR #12867

**Comment by xuhdev** [comment]
You're right. `default-directory` should be the actual directory that the user selects

**Comment by 8i8** [comment]
@duianto Oh that is a neat short cut for the system info!
Here is my system description:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b25526149)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript sql python html go ivy auto-completion emacs-lisp
            (c-c++ :variables c-c++-enable-clang-support t)
            git markdown multiple-cursors org
            (spell-checking :variables enable-flyspell-auto-completion t)
            (syntax-checking :variables syntax-checking-enable-by-default t)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
The following PRs (possibly modified) changes are now on the develop branch:
[spacemacs/sudo-edit] Fix sudo-edit on TRAMP & [spacemacs/counsel-search] Fix wrong initial directory #12867

**Comment by cormacc** [comment]
May be unrelated, but counsel-edit keybinding appears to have been clobbered by some recent change. When I search project using `SPC /` <type some text>, neither of the keybindings in the ivy layer funcs.el `spacemacs--counsel-map` are available (`CTRL-C CTRL-E` to edit, or `<f3>` to save)

**Comment by madand** [comment]
Here is the offending commit: 9c613b8770e9ed191c71b3da19458502b7ddefd8. It breaks `C-c C-e` and `F3`, if you use `ag` or `rg`.

**Comment by duianto** [comment]
The following PRs (possibly modified) changes are now on the develop branch:
[ivy] Fix spacemacs/counsel-search with ag and rg #12987

**Comment by azbshiri** [comment]
I confirm `counsel-more-chars` error is still happening how can I fix it?

**Comment by duianto** [comment]
@azbshiri If your on the `master` branch, then the fix hasn't been part of a `master` branch release yet.

The `develop` branch is the recommended branch until the next version is released (I don't have any insight into when that is).

Backup your current setup, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by tian-yi** [comment]
Tried to re-clone the repo, `space /` still not working. It just hangs and displaying `1 chars more`

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a4459dd28)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp git spacemacs-modeline spacemacs-layouts spacemacs-editing-visual spacemacs-editing spacemacs-navigation spacemacs-misc spacemacs-project ibuffer org ivy lsp
     (markdown :variables markdown-live-preview-engine 'vmd)
     multiple-cursors
     (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
     osx spell-checking syntax-checking treemacs html
     (typescript :variables typescript-backend 'lsp typescript-fmt-on-save t typescript-fmt-tool 'prettier typescript-linter 'eslint)
     (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier)
     (elixir :variables elixir-backend 'lsp)
     emacs-lisp
     (reasonml :variables reason-auto-refmt t)
     (python :variables python-backend 'lsp python-formatter 'lsp python-format-on-save t)
     ocaml)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
@tian-yi Did you also update the packages?

I'm on the latest `develop` branch with updated packages and it doesn't hang for me:
- Open a `.emacs.d` dired buffer: `M-m a d` navigate to `~/.emacs.d`
- Press: `M-m /`
The minibuffer shows: `3 chars more`
- Type: `ivy` the number reduces with every typed character.
When the `y` is typed, then the 591 results are listed.

I'm using the `rg` (https://github.com/BurntSushi/ripgrep) search tool.

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fef85251e)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(auto-completion command-log emacs-lisp git ivy markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 pdf
                 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fef85251e)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go ivy imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by tian-yi** [comment]
@duianto yes. I've updated the packages. 

It actually works now for me.  I saw a warning complaining about environment variables should be put into `.zshenv` instead of `zshrc` when I started Spacemacs the other day.
Then I did so, moved all the env vars into `zshenv`. 
It started working after that, but I can not be sure though, I also tried bunch of other things I don't remember.

**Comment by dam5h** [comment]
I am having this same problem, sometimes it hangs at `1 chars more` and sometimes it is fine.  I don't actually have any environment vars in `zshrc`...

I just tried a brand new installation on `develop` as well, still having the issue.

**Comment by dam5h** [comment]
So it looks like for me this had to do with start up time of my zsh configuration.  See this issue: 
https://github.com/abo-abo/swiper/issues/2190

And the result of that issue:
https://github.com/jmccarrell/literate-emacs.d/blob/master/jeff-emacs-config.org#what-is--conorcs

This seems to work for me thus far.

**Comment by lebensterben** [comment]
Please use develop branch.

Open a new issue if it persists on develop.
