### ISSUE TITLE
Magit status gives error

### ISSUE THREAD

**Issue by mpf** [syl20bnr/spacemacs#13223]
#### Description :octocat:

Activating `magit-status` (`SPC g s`) yields the error

```
Symbol’s function definition is void: magit-restore-section-visibility-cache
```

#### Reproduction guide :beetle:
- Start Emacs
- `SPC g s`

*Observed behaviour:* :eyes: :broken_heart:

Error thrown, editor does not activate `magit-status` buffer.

*Expected behaviour:* :heart: :smile:

The `magit-status` buffer should appear.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 75cfd40d3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript yaml html rust octave gtags themes-megapack osx python helm julia auto-completion
            (latex :variables latex-enable-auto-fill t latex-enable-folding t latex-build-command "LaTeX")
            emacs-lisp git
            (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
            markdown
            (org :variables org-projectile-file "TODOs.org")
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Have you updated the packages?

The `magit-section` package is available as stand-alone package.
https://emacsair.me/2020/01/23/magit-section/

I'm not seeing any errors when opening the magit status buffer, with updated packages on the latest `develop` branch.

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 75cfd40d3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git github helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 75cfd40d3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors command-log emacs-lisp git haskell helm imenu-list markdown multiple-cursors org python
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by mpf** [comment]
Spacemacs seems to automatically update packages each time it restarts, which I've done.

How do I update `magic-section` manually?

**Comment by mpf** [comment]
I managed to find a way to update `magic-section` manually, and the problem has been resolved. Thanks!

**Comment by mput** [comment]
@mpf how did update magic-section manually?

**Comment by mpf** [comment]
@mput  I ran `package-delete` and then `package-install` on `magic-section`. I just discovered that there's a `package-reinstall` command — perhaps that would have also done the trick.

**Comment by a-berg** [comment]
Well, it seems to be still broken for me at least. Switched to develop recently, found this, did `package-delete` and `package-install`, also `package-reinstall` but I still get the error message.

**Comment by vicky08** [comment]
Nuking files in the elpa folder didnt help my case. I still see this error.

**Comment by alvis** [comment]
I have the same issue after pulling from the latest develop branch.
Both `package-reinstall` or `package-delete` then `package-install` don't work for me.

However, I made it work again by removing `/.emacs.d/elpa` and restart emacs to force reinstalling everything from scratch.

**Comment by charlag** [comment]
Same as @alvis, removing elpa magically fixes it

**Comment by cmower** [comment]
I'm still seeing this issue using Ubuntu 20, Emacs version 26.3, up-to-date on `develop` branch.

 I've tried `package-reinstall`, `package-delete` then `package-install`, and removing `.emacs.d/elpa` then restarting Emacs. Has anyone come across a fix or have an alternative suggestion?

**Comment by duianto** [comment]
The next thing to try might be to:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

Because i'm not seeing any magit (or other) errors, on the latest `develop` branch with updated packages.

<details><summary>
Manjaro, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c2fcc13c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            rust spell-checking syntax-checking version-control
            (vue :variables vue-backend 'lsp)
            treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c2fcc13c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure emacs-lisp git helm javascript
            (latex :variables latex-backend 'lsp)
            lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python
            (ranger :variables ranger-enter-with-minus nil)
            shell spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by cmower** [comment]
Thanks @duianto for your suggestion but I'm afraid this didn't work either. I still get 
```
Error (use-package): magit/:config: Wrong type argument: listp, all
```
in the `*Warnings*` buffer and `Symbol's function definition is void: magit-restore-section-visibility-cache` in the mini-buffer when I do `M-m g s` (tested in `.emacs.d` after cloning `sy120bnr/spacemacs`, starting emacs, restarting emacs, adding `git` to `.spacemacs`, restarting a couple more times). 

Would moving from Emacs 26.3 -> 27.1 be the next step? Anything else to try? Thanks again!

**Comment by cmower** [comment]
I haven't modified any of the source files in my local clone of `syl20bnr/spacemacs`, but I did as you suggested anyway as a sanity check. There's no difference, checked file myself, and also I copied raw version of `layers/+source-control/git/packages.el`to a temp file (`tmp.el`) and checked with `diff`:
```
$ diff tmp.el packages.el -s
Files tmp.el and packages.el are identical
```

System info below, will try 26.3 -> 27.1 and let you know, unless you spot something below.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c2fcc13c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python auto-completion emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by cmower** [comment]
So I made the move 26.3->27.1 and this solved the issue! New system info below.
Thanks for your help @duianto!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c2fcc13c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python auto-completion emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS PDUMPER GMP
