### ISSUE TITLE
Simple bug 8571 reappeared

### ISSUE THREAD

**Issue by Volker-Weissmann** [syl20bnr/spacemacs#13551]
This bug:
https://github.com/syl20bnr/spacemacs/issues/8571
was fixed by this pull request:
https://github.com/syl20bnr/spacemacs/pull/9309

But it reappeared in the last three years (I don't know exactly when, but the bug exists in the newest master commit).

The default value of ivy-use-selectable-prompt is nil, but it should be t.

**Comment by smile13241324** [comment]
Hi @Volker-Weissmann,

I need some more information about your system. I have quickly checked on develop with a default ivy config and `ivy-use-selectable-prompt` is `t` as expected.

Please pull latest develop and add the default spacemacs diagnostics to your issue. You can most easily see them by using the build in issue reporting, i.e. `spacemacs-report-issue`.

Right now I would assume that this is already fixed on develop.

**Comment by Volker-Weissmann** [comment]
It's fixed in the developer branch (I checked commit a0b099b54e2ebac5755a08cccfcbc17fca47ebd5)
layers/+completion/ivy/packages.el:247 is
(setq ivy-use-selectable-prompt t)


It's not fixed in the master branch ( I checked commit d46eacd83842815b24afcb2e1fee5c80c38187c5)


Note: I also found this
CHANGELOG.develop:2216:- Set =ivy-use-selectable-prompt= to =t= (thanks to Boris Buliga)

I assume that the developer branch will be merged into the master branch someday? If so, you can close this issue.

**Comment by Volker-Weissmann** [comment]
Afaik, this bug still exists, but I'm not using emacs anymore, so I don't care.
