### ISSUE TITLE
erc layer will not load...possibly an interaction with parinfer?

### ISSUE THREAD

**Issue by togakangaroo** [syl20bnr/spacemacs#13670]
#### Description :octocat:
I just added the `erc` layer and seems not to load the `erc` package.

I cannot even `describe-package` it.

#### Reproduction guide :beetle:
- on commit `origin/develop 5fcd84d8456581c50448bebe00bedee3432cc566`
- add `erc` layer
- you might need parinfer additional-package loaded?
- Start Emacs
- Note that `erc` package doesn't seem to be loaded
- note that `describe-package` of `erc` will not work

*Observed behaviour:* :eyes: :broken_heart:
When I run `describe-package` and select `erc` from helm I get the following (describe-package of other stuff works)

```
parinfer-ext::smart-tab:mount: Invalid function: evil-define-key
```

Call Stack:
```
Debugger entered--Lisp error: (invalid-function evil-define-key)
  evil-define-key(insert (keymap (remap keymap (parinfer-shift-left . parinfer-smart-tab:shift-left) (parinfer-shift-right . parinfer-smart-tab:shift-right) (parinfer-toggle-mode . parinfer-region-mode-switch-mode)) (backspace . parinfer-region-delete-region) (backtab . parinfer-shift-left) (9 . parinfer-shift-right) (S-tab . parinfer-shift-left) (tab . parinfer-shift-right)) [remap evil-shift-right-line] parinfer-smart-tab:shift-right)
  parinfer-ext::smart-tab:mount()
  parinfer--extension-funcall(smart-tab :mount)
  parinfer--extension-lifecycle(:mount)
  parinfer-mode-enable()
  parinfer-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook))
  run-mode-hooks(emacs-lisp-mode-hook)
  emacs-lisp-mode()
  lm-commentary("/Applications/Emacs.app/Contents/Resources/lisp/erc/erc.el.gz")
  describe-package-1(erc)
  describe-package(erc)
  funcall-interactively(describe-package erc)
  call-interactively(describe-package)
  lazy-helm/describe-package()
  funcall-interactively(lazy-helm/describe-package)
  call-interactively(lazy-helm/describe-package nil nil)
  command-execute(lazy-helm/describe-package)
```

Also, when I `describe-package` of `parinfer` I get 

```
parinfer is an incompatible package.

     Status: Incompatible in ‘parinfer-20180904.844/’ (unsigned).
    Version: 20180904.844
    Summary: Simpler Lisp editing
   Requires: dash-2.13.0 (not available), cl-lib-0.5
   Homepage: https://github.com/DogLooksGood/parinfer-mode
   Keywords: parinfer 
Other versions: 20180904.844 (melpa).
```

I've never seen this before and am not sure what it means.

*Expected behaviour:* :heart: :smile:
Expected erc to load and describe-package not to crash :D

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(elixir racket windows-scripts nginx typescript yaml lsp helm auto-completion better-defaults sql docker yaml rust php python csv ruby html helm auto-completion slack git better-defaults lsp colors github erc emacs-lisp markdown clojure org version-control floobits ipython-notebook react csharp themes-megapack jabber plantuml version-control syntax-checking erc evil-snipe gim-org-config kotlin)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by cmatzenbach** [comment]
I use both erc and parinfer and don't have this issue.  Just loaded up erc and connected to a channel just fine.  I first tried `describe-package` and selected erc, and it displayed the normal info.  Did the same to parinfer, all good - it didn't have the missing dash dependency.  I'm guessing this was a bug that got fixed in recent versions of 1develop`.

Here's my setup, first try this: **make sure to update packages**  (https://github.com/syl20bnr/spacemacs/#on-develop-branch), then follow the second step (git pull --rebase), and restart.  Our setups are almost identical, you're just on a way older commit in develop and your packages may be out of date.

**System Info**

- OS: gnu/linux
- Emacs: 26.3
- Spacemacs 0.300.0
- Spacemacs branch: develop (rev. [2bc80b4b4](https://github.com/syl20bnr/spacemacs/commit/2bc80b4b4258420ac20644c78cecb536f4ae5eb5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers
     `;; languages
     c-c++
     common-lisp
     emacs-lisp
     html
     (javascript :variables
                 javascript-backend 'lsp
                 javascript-lsp-server 'javascript-typescript-langserver
                 javascript-import-tool 'import-js
                 javascript-fmt-tool 'prettier
                 javascript-repl 'nodejs
                 js2-basic-offset 2
                 js-indent-level 2
                 node-add-modules-path t)
     (typescript :variables
                 typescript-backend 'lsp
                 typescript-lsp-linter nil
                 typescript-linter 'eslint
                 typescript-fmt-tool 'prettier
                 typescript-import-tool 'import-js
                 node-add-modules-path t)
     json
     jsonnet
     prettier
     import-js
     php
     (react :variables
            react-import-tool 'import-js)

     ;; highlighting/formatting

     ;; auto completion
     lsp
     (auto-completion :variables
                      auto-completion-enable-help-tooltip t
                      auto-completion-use-company-box t
                      auto-completion-complete-with-key-sequence "C-l"
                      auto-completion-private-snippets-directory t
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-enable-sort-by-usage t
                      auto-completion-idle-delay 0.0
                      auto-completion-minimum-prefix-length 1
                      auto-completion-enable-help-tooltip t)
     ;; gtags

     ;; core editor tools
     ivy
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
     git
     github ;; see how useful this is
     version-control
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     parinfer
     (colors :variables
             colors-colorize-identifiers 'variables)
     themes-megapack
     theming

     ;; messaging
     erc
     slack

     ;; documentation
     semantic
     spell-checking
     syntax-checking
     ;; dash - offline api dictionary - look into for polish maybe?
     pdf

     ;; spacemacs improvements
     spacemacs-completion
     spacemacs-defaults
     spacemacs-editing
     spacemacs-evil
     spacemacs-language
     spacemacs-layouts
     spacemacs-misc
     spacemacs-modeline
     spacemacs-navigation
     spacemacs-project
     spacemacs-visual-layer
     ;; look into - spacemacs-purpose

     ;; domain-specific languages
     major-modes ;; adds arch PKGBUILD support!
     sql
     csv
     latex
     markdown
     yaml
     shell-scripts
     vimscript
     cmake
     pandoc
     org

     ;; tooling
     docker
     ;; prodigy - maybe work for starting up vagrant, docker, etc?
     restclient
     systemd
     vagrant

     ;; random
     typography
     copy-as-format
     xkcd
     ;; save and insert URLs
     quickurl
     ;; better docstrings and help buffers
     helpful`

**Comment by cmatzenbach** [comment]
Another thing to try might be enabling dash.  I have it commented out but it's still showing in my `'(package-seleced-packages)` - maybe it was a dependency for something else, I dunno.

**Comment by smile13241324** [comment]
@togakangaroo do you still have that issue on latest develop? Can you confirm you are using evil and evil is properly installed?

**Comment by togakangaroo** [comment]
Hey sorry, I just got back to this, didn't even realize I created the issue an must have missed the thread

I recently moved to a new computer a week or two ago (ubuntu) and am still having this issue with versions `0.300.0@26.3 (spacemacs)` and yes on `develop`
```
commit 64900229a1e020d0b0b942efe112ca968e24aa05 (HEAD -> develop, origin/develop, origin/HEAD)
```

Probably related to #14308

**Comment by smile13241324** [comment]
Strange, no idea where this comes from however as it looks right now I will not have too much time to check it, so I have added the community help tags, lets see if someone else can have a look.
