### ISSUE TITLE
emmet-expand not expanding yasnippet snippets

### ISSUE THREAD

**Issue by kylesnowschwartz** [syl20bnr/spacemacs#13931]
#### Description :octocat:
`emmet-expand` function is not expanding yasnippet snippets, instead automatically wrapping the expression in angle brackets.

#### Reproduction guide :beetle:
- Start Emacs
- Enable auto-completion
- Go to an html file with web-mode on
- make sure an expression `exp` has a yasnippet associated (evil-mode, insert, type expression and `M-/` to test expansion)
- type the same expression and instead hit `TAB` while in insert mode

*Observed behaviour:* :eyes: :broken_heart:
- you will see `<exp></exp>`

*Expected behaviour:* :heart: :smile:
You should see your expanded yasnippet

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b83eb11e3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(react csv ivy
       (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rbenv ruby-backend 'robe)
       ruby-on-rails yaml javascript sql html auto-completion emacs-lisp git markdown multiple-cursors
       (haskell :variables haskell-completion-backend 'lsp)
       lsp org syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
;; layers/+lang/html/funcs.el

(defun spacemacs/emmet-expand ()
  (interactive)
  (unless (if (bound-and-true-p yas-minor-mode)
              (call-interactively 'emmet-expand-yas)
            (call-interactively 'emmet-expand-line))
    (indent-for-tab-command)))


;;elpa/26.3/develop/emmet-mode-20180613.341/emmet-mode.el

;; Emmet yasnippet integration

(defun emmet-transform-yas (input)
  (let* ((leaf-count 0)
         (emmet-leaf-function
          (lambda ()
            (format "$%d" (incf leaf-count)))))
    (emmet-transform input)))

;;;###autoload
(defun emmet-expand-yas ()
  (interactive)
  (let ((expr (emmet-expr-on-line)))
    (if expr
        (let* ((markup (emmet-transform-yas (first expr)))
               (filled (replace-regexp-in-string "><" ">\n<" markup)))
          (delete-region (second expr) (third expr))
          (insert filled)
          (indent-region (second expr) (point))
          (if (fboundp 'yas/expand-snippet)
              (yas/expand-snippet
               (buffer-substring (second expr) (point))
               (second expr) (point)))))))

```

*Help debug the elisp!* :heart: :smile:
Unfortunately while I can get the gist of the code posted above, I cannot read the code well enough to understand why `yas/expand-snippet` called is not expanding the snippet, opting for the angle bracket expansion instead. It could be because the function is obsolete, but I do not think so (I tested the obsolete function explicitly and it expanded fine).

Any help much appreciated!!!

**Comment by smile13241324** [comment]
I am not sure that this works as expected, on checking this layer I have found that emmet expand is overwriting tab for selecting completion candidates which it should not do.

However when I follow your instructions i.e.:
``` html
<!DOCTYPE html>
<html>
  <body>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
    exp_
  </body>
</html>
```
and I put my cursor in insert state after `p` in the line with `exp`, and press `tab` than `emmet-expand-yas` is called which does the completion you are seeing. `M-/` calls `hippie-expand` which seems to be what you want.

**Comment by kylesnowschwartz** [comment]
Thanks for taking a look at @smile13241324 !

Just so I can clearly understand, you have confirmed my report that `emmet-expand` does not complete yasnippets correctly?

I'm not sure if you've seen this somewhat related issue:
https://github.com/syl20bnr/spacemacs/issues/10514
Which speaks to what you noticed, which is that emmet expand overwrites tab for selecting completion candidates. I had a heck of a time trying to 'rebind' `tab` to `hippie-expand` until I found this issue, and the cause which was the layer just completely overwrites tab and it cannot be rebound.

What are your thoughts on the best way to resolve? I'm thinking that
1) emmet should give you the ability to rebind tab, or to change the keybinding for `emmet-expand` and not completely clobber your keybindings
2) `emmet-expand-yas` should expand a yasnippet correctly.

**Comment by smile13241324** [comment]
I think the layer should take care of the bindings, when the `emmet` package kills our binding we need to unbind it in the layer during the init phase.

I have had a quick look at `emmet-expand` I am not sure that this is a package we should keep. Basically it is not maintained since 2018. When I show `yas` bindings via `company-yasnippet` I find `doctype` which would complete to two different values depending on whether I select it via `company` or via `tab`
* This is what I get when entering `doc` and press tab, which calls `emmet-expand-yas`
``` html
    <html>
      <head>
        <meta charset="UTF-8"/>
        <title>Document</title>
      </head>
      <body>
        
      </body>
    </html>
```
* And `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">` is returned when I select it via `company`

I am not sure that the `yas` integration of that package is really working as expected.
https://github.com/smihica/emmet-mode/blob/master/emmet-mode.el

From a design perspective, autocompletion should be entirely controlled via the auto-completion layer this includes also a yas integration into company. In my opinion including a new snippet framework which also integrates yas in a specific layer I find rather interfering than helpful. A better approach would be to integrate a new `Company-backend` in the layer providing the completions defined by `emmet`. Then company will call emmet completions as part of its completion chain and emmet will not overwrite custom settings defined in the context of autocompletion.

**Comment by smile13241324** [comment]
I have fixed the conflict with company. Still the layer changes a key binding "Tab" which is reserved to the auto completion layer. We ought to quickly find a new binding or remove the package entirely. I'll open a discussion ticket.

**Comment by smile13241324** [comment]
I have changed the binding for emmet-expand to `C-return` not to break standard auto-completion bindings. About the quality of emmet-expand however I cannot say much more I think the package works as intended by the package author though this may be outdated as of today.

**Comment by kylesnowschwartz** [comment]
Kickass! Is that already in the develop branch and should be available if I pull down the latest version?

**Comment by smile13241324** [comment]
@kylesnowschwartz already in develop, just pull and you should have it.

**Comment by kylesnowschwartz** [comment]
While the issue of emmet-expand not expanding yasnippets still exists, I don't believe having issues open from now until the end of time benefits the project. I think emmet is externally maintained, so it would be best to raise the issue there. For now the updates to default tab bindings are a start in making this less of an issue.
