### ISSUE TITLE
ivy-occur-mode-map keybindings are shadowed by evil-mode

### ISSUE THREAD

**Issue by czqhurricnae** [syl20bnr/spacemacs#15219]
#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5bcedd191)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults ranger colors prodigy search-engine graphviz
     (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (vinegar :variables vinegar-reuse-dired-buffer t)
     (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
     (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil :disabled-for org markdown)
     (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English" osx-command-as 'super)
     restclient
     (gtags :disabled-for clojure emacs-lisp javascript latex python shell-scripts)
     (shell :variables shell-default-shell 'eshell)
     latex
     (javascript :variables javascript-disable-tern-port-files nil add-node-modules-path t)
     (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
     html react
     (python :variables python-test-runner
             '(nose pytest))
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     emacs-lisp markdown
     (org :variables org-want-to-do-binding t org-enable-github-support t org-enable-reveal-js-support t org-enable-roam-support t)
     fasd
     (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
     theming
     (chinese :variables chinese-default-input-method 'pinyin chinese-enable-youdao-dict t)
     tern hurricane)
```
- System configuration features: RSVG DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Trouble
When I am in `ivy-occur-mode` hit  `q` and try to quit the occur window, it just runs the command `evil-record-macro`, not the command `quite-window` which I want.

Then I try to check the value of `ivy-occur-wgrep-mode-map`:

![截屏2021-12-19 00 11 32](https://user-images.githubusercontent.com/20676402/146648752-b2cfde04-7198-4c37-a321-aa5efb0f59eb.png)

Just like the image shows, many ivy-occur-mode keybindings had been shadowed.

#### Troubleshooting

Then I involved troubleshooting and searched in the google, github issues. 
Hence find a post: https://emacs.stackexchange.com/questions/13130/resolving-keybinding-conflicts-with-evil-mode-troubleshooting-image-dired-bindi

Refer to the author's solution, I change the code in this line:https://github.com/syl20bnr/spacemacs/blob/5bcedd19123248bc7a6d80994784062e524ebe05/layers/%2Bcompletion/ivy/packages.el#L279

from 
```
      (evil-set-initial-state 'ivy-occur-grep-mode 'normal)

```
to 

```
      (evil-set-initial-state 'ivy-occur-grep-mode 'emacs)

```
.
Restart the emacs and check the value of `ivy-occur-wgrep-mode-map` again:

![截屏2021-12-19 00 23 45](https://user-images.githubusercontent.com/20676402/146649102-d573e01b-0149-4c23-a9ee-ea0ac6559a61.png)

The value is changed and the command `quit-window` is called rather than `evil-record-macro` when I hit `q` key in the `ivy-occur-mode`.

Because I am a newbie to emacs and spacemacs, only have basic knowledge of elisp.
I don't know why and if I am doing the right thing?

Please check the situation and give me some help. Thank you.

**Comment by dalanicolai** [comment]
Are you sure that you are looking at `ivy-occur-wgrep-mode-map`? As I can not find such map here. Anyway, I think #15222 should fix this. Thanks for reporting!

**Comment by czqhurricnae** [comment]
![截屏2021-12-21 23 34 05](https://user-images.githubusercontent.com/20676402/146956699-7ba505be-1a5a-40e0-ad67-6dad42aa6873.png)

Try to use `Describe variable` command to search.

**Comment by dalanicolai** [comment]
Ah okay, your image shows `grep` mode not `wgrep` mode, so I guess it was a typo then. Thanks for having a look...

**Comment by czqhurricnae** [comment]
Just try this commit https://github.com/dalanicolai/spacemacs/commit/9d43d002e3f0d318a7b53da576abbd784c713133,
it is still the same.

![截屏2021-12-21 23 47 05](https://user-images.githubusercontent.com/20676402/146960310-a3765353-689d-4667-a036-3d6413563df1.png)

As the fisrt image show, keybindings are shadowed too after changed the source code and restarted.

![截屏2021-12-21 23 53 14](https://user-images.githubusercontent.com/20676402/146960718-69c5f95f-9d60-4899-ba17-1a4b51002c6c.png)

In contrast to the first image, then I hit `Ctr-z` in the occur buffer, then change from evil style to emacs style? The keybindings are not been shadowed as the second image show.

**Comment by czqhurricnae** [comment]
> Just try this commit [dalanicolai@9d43d00](https://github.com/dalanicolai/spacemacs/commit/9d43d002e3f0d318a7b53da576abbd784c713133), it is still the same.
> 
> ![截屏2021-12-21 23 47 05](https://user-images.githubusercontent.com/20676402/146960310-a3765353-689d-4667-a036-3d6413563df1.png)
> 
> As the fisrt image show, keybindings are shadowed too after changed the source code and restarted.
> 
> ![截屏2021-12-21 23 53 14](https://user-images.githubusercontent.com/20676402/146960718-69c5f95f-9d60-4899-ba17-1a4b51002c6c.png)
> 
> In contrast to the first image, then I hit `Ctr-z` in the occur buffer, then change from evil style to emacs style? The keybindings are not been shadowed as the second image show.

@dalanicolai

**Comment by dalanicolai** [comment]
@czqhurricnae I looks like it opens there in `motion-state` also ([indicated by the purple color](https://www.spacemacs.org/doc/DOCUMENTATION.html#states)). I don't see the reason for that (I would expect it to open in `normal-state`). Anyway, I will simply make the keymap override in all states then. Thanks again...
