### ISSUE TITLE
Helm help "Cannot make side window the only window" on develop branch

### ISSUE THREAD

**Issue by drmikehenry** [syl20bnr/spacemacs#1611]
Hi,

When I enter helm via ```SPC b b``` and try to bring up the help via ```C-c ?```, I get the error message "Cannot make side window the only window".  Help in helm works for me using the master branch; it's only on the develop branch I see this issue.  Any ideas what's wrong?  (This happens with no ```.spacemacs``` customizations.)

Thanks,
Michael Henry

**Comment by tuhdo** [comment]
It happens because we force Helm to be always displayed at 0.4 frame height with `display-buffer-alist`, but the Helm help requires the Helm window to be full screen and the error happens for that reason.

**Comment by tuhdo** [comment]
@syl20bnr probably we should consider using `window-purpose` assign a purpose for a window to always display Helm buffers.

**Comment by syl20bnr** [comment]
@tuhdo how would that work in practice ?

**Comment by tuhdo** [comment]
@drmikehenry This issue is fixed in `develop`.

**Comment by drmikehenry** [comment]
Thanks!  This fixes the problem I was seeing.

**Comment by bapcyk** [comment]
Is not it a plugin bug: https://github.com/jaypei/emacs-neotree/issues/226  ?

**Comment by dineshbhosale** [comment]
This issue still exists, pressing "SPC feR" again and again does not feel productive at all.

**Comment by dineshbhosale** [comment]
Reinstall from develop branch fixed all errors with neotree and eshell buffer.

**Comment by unalterable** [comment]
I'm on spacemacs (master branch) and i think this has worked for me (and i think it should work with emacs too):

(setq helm-split-window-inside-p t)
I put it in my user -config() (which is a set of commands run after spacemacs loads all its layers/packages)
