### ISSUE TITLE
Contrib: org - org-indent-mode is on by default and that's a horrible default

### ISSUE THREAD

**Issue by jrmiller82** [syl20bnr/spacemacs#2732]
Subject says it all.

**Comment by sooheon** [comment]
I don't mind it. Why do you think it's horrible?

**Comment by TheBB** [comment]
> Subject says it all.

**Comment by jrmiller82** [comment]
It's a poor default mode; it makes me have to add a #+STARTUP: noindent to every file when I would prefer it to be the other way around. Further, you have it set up to do 1,3,5 stars instead of the standard 1,2,3 stars. That's just annoying and aren't 'improved' defaults. It's very annoying too when you use the terminal over the GUI version. I just don't see the need for those as 'defaults'.

**Comment by TheBB** [comment]
> it makes me have to add a #+STARTUP: noindent to every file

Can't you `(setq org-startup-indented nil)` instead?

> Further, you have it set up to do 1,3,5 stars instead of the standard 1,2,3 stars.

I don't see any problems with even-numbered levels. What's the issue?

**Comment by sooheon** [comment]
Your points are that:
1. To toggle it off, you need to add a header to every file
2. You need to set up `org-odd-levels-only` to make it work, and this is annoying
3. It's annoying when you use the terminal

Of these, 1 and 2 two are plain wrong. You can simply toggle it off with `(with-eval-after-load 'org
    (setq org-startup-indented nil))` in your config. And there is no reason for you to ever touch the odd numbered levels, because `org-indent-mode` deals with it for you. If you toggle that off, you will have the exact default with even levels that you want. 3 is a matter of taste, which is also fixed with `(setq org-startup-indented nil)`. There's no compelling argument here for a different default.

**Comment by syl20bnr** [comment]
@jrmiller82  I consider this a personnal preference, but if you are experiencing bugs with org-indent then we can reconsider it.

**Comment by CestDiego** [comment]
@syl20bnr the only thing I can see that is a little bit odd is that when you do `SPC t f` to show fill-collum indicator, it looks very weird

**Comment by jrmiller82** [comment]
I still don't think it's a sensible default. Plain old org's default is the sensible default.

**Comment by syl20bnr** [comment]
We can remove it and enable it when opening spacemacs doc. We can provide a key binding to toggle it.
Since it does no play well with some other packages, I agree to disable it by default.

**Comment by jrmiller82** [comment]
Thank you. And thank you for your work on spacemacs. I had left the emacs fold for about 6 months and went back to vim. But I needed to spend a bunch of time in org-mode recently and I decided to try spacemacs. Loving it (other than the org default) so far.

**Comment by ghitchens** [comment]
I would *beg* @syl20bnr to reconsider the change, and keep the default of `org-indented-mode` on.

Personally, I can't imagine using `org-mode` without `org-indented-mode`, and I think that given that spacemacs is intended to bring emacs out of the dark ages of UI, and given that it introduces a LOT of new defaults (most al of which are a step forward), org-indented-mode is very much a reasonable default.    To me, I rejected `org-mode` outright as a solution until I discovered `org-indented-mode`, and I worry that others might also.

`org-indented-mode` does seem to have an issue with indentation when `adaptive-wrap-prefix-mode` is enabled, but disabling `org-indented-mode` by default is a horrible solution to the incompatibility -- it just pushes the frustration further in for a new user -- first, you decide you don't like the cluttered look of org mode, then you turn on `org-indented-mode` to fix that, and decide that it's broken, and then you give up entirely.

As @sooheon mentioned, the much of the OP seems wrong in terms of justification for the change, and one line in `.spacemacs` file can give the OP the behavior he wants.  

My suggestion:

- disable `adaptive-wrap-prefix-mode` in `org-mode` to resolve the incompatibility
- leave the `org-indented-mode` on by default

And, thank you for your wonderful work on spacemacs, which I think is making Emacs cool again, at least for me!

**Comment by cpaulik** [comment]
While I really like the look of `org-indent-mode` I do have issues with it sometimes. New headlines are sometimes not indented until I reopen the file which is rather annoying. Does anybody else have this problem?

**Comment by TheBB** [comment]
Yes I do too. For me it usually suffices to turn the mode off and on again, instead of having to actually close and reopen the buffer.

**Comment by jb55** [comment]
`org-indent-mode` is super buggy for me. I have to turn it off an on again a lot. I ended up turning it off by default, which I now think is the sensible thing to do.

**Comment by incandescentman** [comment]
I have the same issue, and I too would never consider using org-mode without having org-indent-mode turned on. To solve this, I'm also excluding the `adaptive-wrap` package for now. 

And to @TheBB and @cpaulik, I sometimes do have issues with org-indent, once in a while. To resolve them, I did this, which works perfectly for me:

    (defun reflash-indentation ()
    "Fix org-indent issues, center line."
    (interactive)
    (org-indent-mode nil)
    (recenter-top-bottom)
    )
    (define-key key-minor-mode-map (kbd "C-l") 'reflash-indentation)

**Comment by syl20bnr** [comment]
We decided to disable by default. We will provide some support to enable it back easily.

**Comment by jrmiller82** [comment]
I am vindicated! ;) 

Thanks again for all your hard work. Looking forward to when that change makes it into the main release.

**Comment by NorfairKing** [comment]
Can we please just add a piece of documentation that explains how to change the default for a user? Users shouldn't have to come looking through this issue to find that.

**Comment by sooheon** [comment]
You're welcome to PR to the org layer or wherever else you think it'd be most helpful. But really, users should learn to use the self documenting features of emacs. All of this and more can be find in the info node for Org Mode, or by a little proactive look through customize or org- prefixed variables.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by divansantana** [comment]
@incandescentman 
> And to @TheBB and @cpaulik, I sometimes do have issues with org-indent, once in a while. To resolve them, I did this, which works perfectly for me:
> ```emacs-lisp
>   (defun reflash-indentation ()
>     "Fix org-indent issues, center line."
>     (interactive)
>     (org-indent-mode 1)
>     (recenter-top-bottom)
>     )
>   (define-key key-minor-mode-map (kbd "C-l") 'reflash-indentation)
> ```

The above looks pretty handy. Though I'm having an issue with getting it working.

I'm using the above with Emacs 25.1.1 and get the following error.
```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: key-minor-mode-map
```

Any ideas?

**Comment by cpaulik** [comment]
@divansantana Checkout https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#binding-keys 

Something like `(spacemacs/set-leader-keys-for-major-mode 'org-mode "C-l" 'reflash-indentation)` would make the command accessible via `SPC m C-l`

**Comment by divansantana** [comment]
@cpaulik great - thanks.

**Comment by Compro-Prasad** [comment]
@jrmiller82 I really want to know the cause of making this a default. Please share some screenshots for better clarification. org-mode provides good defaults but still I preferred to switch on org-indent-mode. If you have manually indented your code then it is your problem.

**Comment by Compro-Prasad** [comment]
@syl20bnr I don't have any adaptive wrap mode. If that was the problem then it has been removed and that shouldn't cause problems with org indent mode.

**Comment by syl20bnr** [comment]
For people still lurking here, we should add a toggle for org-indent
under `SPC m T i`. `SPC m T` is the conventional prefix for major-mode
toggles.

**Comment by syl20bnr** [comment]
PR Welcome :-)

**Comment by Anton-Latukha** [comment]
I would belabora at the end.
For someone who want to stop Org mode from aligning/indenting your notes/code blocks all the time,
so long notes can stay looking homogeneous, and changes look good in Git:
```elisp
(org :variables
          ;; Turn off all org auto indentation completely
          org-startup-indented nil
          ;; Turn off manual indentation completely,
          ;; AKA when you suddenly press TAB or =
          org-adapt-indentation nil
)
```
