### ISSUE TITLE
Pressing escape doesn't always leave insert mode

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2756]
This is on develop.

Sometimes when I press escape, or for me, `C-[`, it doesn't actually leave insert mode, and instead starts to try to consume a key combination, almost like I pressed the leader key.

This happens if I use just the regular `ESC` key, or if I press `C-[`.  I have not found a way to reliably reproduce it, but it happens enough that I knew I would be able to capture it in a screencast pretty easily.

https://www.youtube.com/watch?v=WB42kaCP3x0

Sorry about the video size.  I was going to crop it down to the size of the editor itself, but I couldn't figure out how to do that and leave the keystrokes display in the video.

**Comment by sooheon** [comment]
Pretty difficult to see what's going on, but it seems like emacs takes 3 `esc`s, then outputs "auto-trimmed 3 chars" in the mini buffer. Not sure what that is, but maybe you've managed to enter some special state which waits for commands? Could start by looking through your messages.

**Comment by justbur** [comment]
Evil emacs state doesn't interpret C-[ the same as ESC. You are most likely not in the insert state.

**Comment by synic** [comment]
Is there a way I can make it interpret it the same?  In *most* cases it seems to work. 

I'm also fine to try any other key combination - just seems like escape is too far away.

**Comment by justbur** [comment]
It will be interpreted the same in insert mode. Do you have something in
your configuration that messes with evil's insert mode?

**Comment by synic** [comment]
No, I'm using mostly stock configuration while I get my bearings.


```elisp
defun dotspacemacs/config ()
  "Configuration function.
 This function is called at the very end of Spacemacs initialization after
layers configuration."
  (global-linum-mode t) ; Show line numbers by default
  (auto-fill-mode t)
  (setq indent-tabs-mode nil)
  (setq neo-show-hidden-files nil)
  ; delete trailing whitespace on save
  (add-hook 'before-save-hook 'delete-trailing-whitespace)

  ; python hooks
  (add-hook 'python-mode-hook (lambda ()
                                (fci-mode 1)
                                (auto-fill-mode)
                                (setq fill-column 79)
                                ))
)

```

**Comment by justbur** [comment]
And the editing style is vim?

**Comment by synic** [comment]
Yes

**Comment by justbur** [comment]
Try this. Go into insert state, type `C-h v` then select `evil-esc-mode`.
It should be set to `t`.

**Comment by synic** [comment]
Yes, it is `t`.

**Comment by oppenlander** [comment]
I have also noticed this behavior. It happens for me in `js2-mode` when there is an error on the line I am operating on.
Maybe it's a weird interaction with `flycheck`?

**Comment by justbur** [comment]
There are a bunch of issues at the evil repo about `C-[` translation, some having to do with certain packages being enabled. I can't replicate what you're talking about, so here's one last thing to try looking through those issues

```elisp
(setq evil-intercept-esc 'always)
```

If that doesn't work, I think you should report this at the [evil repo](https://bitbucket.org/lyro/evil/issues)

**Comment by synic** [comment]
Yeah, doesn't seem to have helped.

**Comment by synic** [comment]
https://bitbucket.org/lyro/evil/issues/570/pressing-ctrl-doesnt-always-leave-insert

**Comment by cmccloud** [comment]
I'm seeing similar behavior with both the evil escape key sequence and the ESC key. 

Steps to reproduce:
Open .spacemacs
M-x ediff-current-file
Exit the ediff session with 'q'
ediff buffer that begins with 'FILE=..' seems to be stuck in insert mode - does not respond to either ESC or evil escape
M-x normal-mode restores both

**Comment by justbur** [comment]
@cmccloud Did you get into emacs state by chance? I think the cursor isn't changing color, but it's getting stuck in emacs state. Did you try `C-z`?

**Comment by cmccloud** [comment]
@justbur C-z doesn't work. Using M-x describe variable from bad buffer shows that the value of 'evil-state' is nil. Using M-x describe mode lists shows Evil as active.

**Comment by cmccloud** [comment]
To update. I can no longer reproduce the particular error that I mentioned. I believe I'm on the same commit as before, so maybe whatever caused it was fixed upstream.

**Comment by synic** [comment]
It hasn't happened to me in a long while either.

**Comment by TheBB** [comment]
Then I'm closing this for now. If it happens again you can reopen.

**Comment by peterhadlaw** [comment]
Hello all, I'd like to point out, on the new packages pulled from Melpa, I'm still experiencing this js2-mode related, evil state NIL errors

**Comment by andreaskern** [comment]
It just happened to me too
`M-x normal-mode` fixed it

**Comment by syl20bnr** [comment]
If you encounter this bug again it is better to open a new issue and best if you link to this thread as well.

**Comment by marcw** [comment]
It just happened to me. This was due to the fact that I use spacemacs in the terminal and that "C-z" doesn't send spacemacs in the background, but instead switch it to somekind of perpetual insert mode.

**Comment by duianto** [comment]
@marcw That's a feature of the https://github.com/emacs-evil/evil package.

When the `vim` editing style is used, then: `C-z` toggles between:
- evil emacs state where the vi keys are disabled (it uses the Emacs bindings)
- evil normal state where the vi keys are enabled

source: https://evil.readthedocs.io/en/latest/overview.html#modes-and-states)

If you want to rebind `C-z` to something else then you might have to unbind it first. There's a suggestion for how to unbind it, in this comment: 
Can't bind anything to C-z https://github.com/syl20bnr/spacemacs/issues/7372#issuecomment-253202054
```elisp
(define-key evil-emacs-state-map (kbd "C-z") nil)
```

**Comment by Paulswith** [comment]
> @cmccloud Did you get into emacs state by chance? I think the cursor isn't changing color, but it's getting stuck in emacs state. Did you try `C-z`?

thanks, u save me.
