### ISSUE TITLE
`k` doesn't go up in Magit buffer

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#3132]
This seems like a glaring floor - `j` goes down, I can't be the only one who instinctively presses `k` to go up a line

## edit 

[video](http://sendvid.com/b6rozl30)

Whenever you see the popup about discarding in that video it's from pressing `k` after `j` @syl20bnr 

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.0
- Spacemacs branch: develop (rev. 7b43896)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete)
 better-defaults c-c++ colors emacs-lisp erc evil-snipe eyebrowse git github html ipython-notebook javascript latex markdown org python semantic shell syntax-checking themes-megapack version-control)
```

[spacemacs file](http://vpaste.net/9tDs7)

**Comment by syl20bnr** [comment]
Do you have a repro step ?

**Comment by syl20bnr** [comment]
I cannot reproduce it with both 24.4.1 and 24.5.1 on OS X. Do you have magit up to date ?
I can reproduce it in visual state only and I just pushed a fix in develop.

**Comment by geo7** [comment]
Yeah I'm pretty sure that I'm up to date with things, I'm not too sure how I check the version of magit that I'm running though?

**Comment by syl20bnr** [comment]
Can you try with just the git layer enabled ? Can you try in Vim style ? I was not able to reproduce it in hybrid but I don't use it all the time.

**Comment by geo7** [comment]
Just tried it @syl20bnr , still the same 

http://sendvid.com/nl8tvu2z

**Comment by justbur** [comment]
I get the same behavior. What's interesting is that I think it's tied to the section maps, because it works fine outside of the sections (in magit-status at least)

**Comment by syl20bnr** [comment]
I cannot reproduce it and I cannot see how it could not work, this behavior does not make sense.
It is like you have magit loaded twice and keymaps got reseted to raw magit ones.
Can you `SPC h d k k` ? Also can you check that `evil-state` variable is not nil ?

**Comment by justbur** [comment]
In the stash section for example `SPC hdkk -> magit-stash-drop` and `SPC hdv evil-state RET -> evilified`

**Comment by syl20bnr** [comment]
You have something in your config that make evilify-map a noop.

**Comment by syl20bnr** [comment]
> k runs the command
magit-discard-or-evil-previous-visual-line--evilified-magit-hunk-section-map-k,
which is an interactive Lisp function.

It is bound to k.

> (magit-discard-or-evil-previous-visual-line--evilified-magit-hunk-section-map-k)

> Wrap function `magit-discard' and function `evil-previous-visual-line'.
In evilified state function `evil-previous-visual-line' is executed. Whereas in other states (i.e. emacs state) the stock function `magit-discard' is executed.

**Comment by syl20bnr** [comment]
To be more precise:

> k runs the command
magit-discard-or-evil-previous-visual-line--evilified-magit-hunk-section-map-k,
which is an interactive Lisp function.

**Comment by syl20bnr** [comment]
mmmh

**Comment by justbur** [comment]
Whoops sorry. I had the commit from #3140 on my develop branch and didn't realize it. That does seem to cause this problem fyi. 

Everything seems ok for me when I reverted that.

**Comment by syl20bnr** [comment]
Mmmmhhh weird... your PR should be OK.

**Comment by justbur** [comment]
There's this useful function in the help-fns+ package called describe-keymap. Here's what it gives me for magit-stash-section-map after that commit
```
magit-stash-section-map
-----------------------

For more information check the manuals.

Keymap for `stash' sections.

key             binding
---             -------

RET             magit-stash-show
A               magit-stash-pop
a               magit-stash-apply
k               magit-stash-drop
<evilified-state>               Prefix Command

<evilified-state> K             magit-stash-drop--evilified-magit-stash-section-map-K
<evilified-state> k             magit-stash-drop-or-evil-previous-visual-line--evilified-magit-stash-section-map-k
```

**Comment by justbur** [comment]
and before the commit
```
magit-stash-section-map
-----------------------

For more information check the manuals.

Keymap for `stash' sections.

key             binding
---             -------

RET             magit-stash-show
A               magit-stash-pop
K               magit-stash-drop--evilified-magit-stash-section-map-K
a               magit-stash-apply
k               magit-stash-drop-or-evil-previous-visual-line--evilified-magit-stash-section-map-k
```

**Comment by justbur** [comment]
The evilified-state bindings *should* apply first but they aren't for some reason

**Comment by syl20bnr** [comment]
Yep this confirms what I thought, your PR should totally work, now I don't understand why the sub-keymap is ignored.

**Comment by justbur** [comment]
My sense is that it has something to do with the sorting, but I only looked for a second

**Comment by syl20bnr** [comment]
Ohhh nice find! This is likely to be the cause, actually I don't anything else which could explain this behavior. Making the sort function to put the prefix before `k               magit-stash-drop` may do it.

**Comment by syl20bnr** [comment]
But I'm not entirely sure since Evil normalizes the keymaps. I'll to dig this a bit to better understand what it is doing.

**Comment by justbur** [comment]
You could rebind all of the standard bindings so they only appear in emacs-state, but it should be simpler than that

**Comment by syl20bnr** [comment]
There is no need for sorting, no need for wrappers etc... It will be a lot simpler, only a sub-keymap for evilified state and that's it. I planned to do it a long time ago but I guess this is now the right time to do it, I should have something ready tonight.

**Comment by justbur** [comment]
That sounds good to me

**Comment by justbur** [comment]
This is possibly a bug in evil. Try this
```elisp
(evil-define-key 'evilified magit-stashes-section-map "k" (lambda () (interactive) (message "k")))
```
It doesn't work

**Comment by geo7** [comment]
Oooooooooo I've found the problem - it's ole evil-escape 

```
  (setq-default evil-escape-key-sequence "uj")
```

works

```
  (setq-default evil-escape-key-sequence "kj")
```

doesn't work ;) 

No idea why and that, but that's the problem (here).

Any temporary hacks I can implement for this? Afaik evil-escape isn't needed for Magit modes as they use their own commands and whatnot. 

Hey ho

**Comment by syl20bnr** [comment]
@geo7 I fixed it in develop. There was a hack for evil-escape that is not necessary since the rewrite.

**Comment by justbur** [comment]
Also doesn't work
```elisp
(evil-define-key 'emacs magit-stashes-section-map "k" (lambda () (interactive) (message "k")))
```
I think this is an interaction between how magit is storing some keymaps and evil. It appears that the section maps are stored as text overlay properties, try `(get-char-property (point) 'keymap)` and the keymap shows up. Then see [here](
http://www.gnu.org/software/emacs/manual/html_node/elisp/Searching-Keymaps.html)

It looks to me like the section maps are taking priority over the evil maps (at least the ones you get using `evil-define-key`)

**Comment by syl20bnr** [comment]
Indeed, this is the usage of the keymap text property with very high priority that made me implement `core-evilify-keymap.el` when magit 2.1 was about to be released.
Now it is problematic that Evil prefixes are not working with it, in the worst case I will try with a pre-command-hook.

**Comment by syl20bnr** [comment]
More info here about the motivation for the current core-evilify-keymap.el: https://github.com/magit/magit/issues/1918

**Comment by justbur** [comment]
Ok, more info. Here's the keymap defined on the character
```elisp
(keymap
 (evilified-state keymap "Auxiliary keymap for Evilified state"
                  (75 . magit-stash-drop--evilified-magit-stash-section-map-K)
                  (107 . magit-stash-drop-or-evil-previous-visual-line--evilified-magit-stash-section-map-k))
 (107 . magit-stash-drop)
 (65 . magit-stash-pop)
 (97 . magit-stash-apply)
 (13 . magit-stash-show))
```
which almost looks right

**Comment by syl20bnr** [comment]
Cool, there is hope to make it work then but it may be not trivial. Evil has a step to normalize key maps and I bet that this step cannot see the keymaps passed as text properties :-(
But since the keymap looks right a pre-command-hook should do it :-)

**Comment by syl20bnr** [comment]
This seems to work:

```elisp
(defun spacemacs/evilify-pre-command-hook ()
  (when (evil-evilified-state-p)
    (let ((map (get-char-property (point) 'keymap)))
      (when (and map (assq 'evilified-state map))
        (let* ((submap (cdr (assq 'evilified-state map)))
               (command (when submap (lookup-key submap (this-command-keys)))))
          (when command
            (setq this-command command)))))))

(add-hook 'pre-command-hook 'spacemacs/evilify-pre-command-hook)
```

**Comment by syl20bnr** [comment]
@justbur We can setup the hook locally on evilified state entry and remove it on exit, so technically the initial state can be avoided, what do you think ?

**Comment by justbur** [comment]
It seems fine. My inclination I think would be to use wrappers for the functions that are already defined in that map, instead of trying to dynamically lookup in that map. Of course, then you would have to know whether it was a map to be tied to specific characters, but I think if you targeted the section maps that should be sufficient. 

What I'm saying is you could have a general evilify routine for regular maps that used `evil-define-key` and then one for the section maps that did this
```elisp
(keymap
 (75 . magit-stash-drop--evilified-magit-stash-section-map-K)
 (107 . magit-stash-drop-or-evil-previous-visual-line--evilified-magit-stash-section-map-k)
 (65 . magit-stash-pop)
 (97 . magit-stash-apply)
 (13 . magit-stash-show))
```

**Comment by justbur** [comment]
The auxiliary maps are kind of just stored in the mode maps and then loaded through `evil-normalize-keymaps` from what I understand. They're just loaded into too low of a priority level. They don't seem to be "meant" to be used where they're stored as you are here, but if it works I can't argue that much

**Comment by syl20bnr** [comment]
We don't need the wrappers anymore since now we dispatch based on the auxiliary maps. It will simplify everything quite drastically, for instance it won't be necessary anymore to track evilified modes to toggle holy mode.

**Comment by justbur** [comment]
Ok, you know this code way better than I do. I think it should work fine, and if it's just for evilified state I can't see it causing too many problems

**Comment by justbur** [comment]
For reference, here is the way evil checks the auxiliary maps
```elisp
(defun evil-get-auxiliary-keymap (map state &optional create)
  "Get the auxiliary keymap for MAP in STATE.
If CREATE is non-nil, create an auxiliary keymap
if MAP does not have one."
  (when state
    (let* ((key (vconcat (list (intern (format "%s-state" state)))))
           (aux (if state (lookup-key map key) map)))
      (cond
       ((evil-auxiliary-keymap-p aux)
        aux)
       (create
        (evil-set-auxiliary-keymap map state))))))

(defun evil-auxiliary-keymap-p (map)
  "Whether MAP is an auxiliary keymap."
  (and (keymapp map)
       (string-match "Auxiliary keymap"
                     (or (keymap-prompt map) "")) t))
```
The lookup step is different from yours and they also use a string match. I don't know if there's a good reason for that, but there are a couple other types of maps that evil uses

**Comment by syl20bnr** [comment]
Thank you @justbur for the help, I think we have now a clean evilified state that should work as expected.

**Comment by geo7** [comment]
updated everything, still doesn't work here unless I change the evil escape sequence.

**Comment by justbur** [comment]
@syl20bnr shouldn't evil-escape just not do anything in evilified state like it behaves in normal state?

**Comment by justbur** [comment]
@geo7 I can't replicate your issue with "kj" as the escape sequence. I think there's still something weird about your setup. Why do you have key-chord mode on at the same time for example? Also does the evil-escape delay have any affect on the issue? Also, what does this do?
```elisp
  (setq magit-last-seen-setup-instructions "1.4.0")
```

**Comment by geo7** [comment]
> I think there's still something weird about your setup.

most likely, all sorts of things are throwing errors at the moment it seems no
idea why though. I can't even `SPC f e R` at the moment because it just hits an
EOF thing somewhere, thats a new thing as of 15 minutes. 

> Why do you have key-chord mode on at the same time for example?

I have it for indentation, rather than `M-q` which is a bit awkward if one has to
keep hitting it. Didn't know that there was a problem with this.

```
  ;; fill-paragraph - instead of M-q use jf
  (require 'key-chord)
  (key-chord-mode 1)
  (key-chord-define-global "jf" 'fill-paragraph)
```

> Also does the evil-escape delay have any affect on the issue?

Dunno I'll have a test in a sec

> Also, what does this do?

No idea actually, I remember reading that I needed it ages ago.

```
  (setq magit-last-seen-setup-instructions "1.4.0")
```

**Comment by justbur** [comment]
Hm maybe try with a plain dotfile that just sets the escape sequence. I don't know if key chord is a problem. I was just asking.

**Comment by geo7** [comment]
@justbur cool i'll try that soon, cheers

**Comment by geo7** [comment]
tried with this dotfile and it works 


http://vpaste.net/Amqoo

If I change the base template from base to core then uncomment git I get more errors. I'm tired of this now i'll look later, clueless still though

**Comment by justbur** [comment]
You can disable evil escape in magit mode but I think you have other issues lurking.

What do you mean by change the base template from base to core?

**Comment by justbur** [comment]
For the hell of it, I loaded your dotfile on my system but I couldn't reproduce the problem. By the way, you should break `dotspacemacs/init` into `dotspacemacs/init` and `dotspacemacs/user-init` (check the template). Have you tried deleting the elpa directory? Maybe something got corrupted in there (that's happened to me before).

**Comment by geo7** [comment]
well I'm truly out of ideas, I've nuked elpa and all that jazz. 

> What do you mean by change the base template from base to core?

there's that spacemacs / spacemacs-base variable thing now isn't there

**Comment by geo7** [comment]
how do i remove evil escape from magit then? that seems like the easiest solution

**Comment by justbur** [comment]
Sorry I don't give up easily. Put your point in one of the problematic areas and do this

M-: (setq map (get-char-property (point) 'keymap))

Then paste the result here

**Comment by justbur** [comment]
The value of map I mean

**Comment by geo7** [comment]
> Put your point in one of the problematic areas and do this

I don't know what you mean - it just doesn't work. So run this from a magit session?

**Comment by geo7** [comment]
here's the result of that command from a magit session: 

```
(keymap (evilified-state keymap "Auxiliary keymap for Evilified state" (16 . magit-section-backward) (14 . magit-section-forward) (33554443 . magit-section-backward) (33554442 . magit-section-forward)) (22 . magit-reverse--evilified-magit-hunk-section-map-C-v) (86 . evil-visual-line--evilified-magit-hunk-section-map-V) (118 . magit-reverse-or-evil-visual-char--evilified-magit-hunk-section-map-v) (117 . magit-unstage) (115 . magit-stage) (107 . magit-discard) (67 . magit-commit-add-log) (97 . magit-apply) (13 . magit-diff-visit-file) (10 . magit-diff-visit-file-worktree) (C-return . magit-diff-visit-file-worktree))
```

**Comment by syl20bnr** [comment]
> If I change the base template from base to core then uncomment git I get more errors. 

What errors ?
The dotfile you pasted which works for you has already the git uncommented.

**Comment by justbur** [comment]
I'm guessing you have something in a private layer somewhere. That keymap is missing the right binding for k (key 107) which explains the problem.

**Comment by geo7** [comment]
I have no private layers, I have a few files that `load` from the .spacemacs, but I have commented these out and get the same error. 

Note this template doesn't work http://vpaste.net/sw9D1

pretty much everything is commented out in that or just deleted

**Comment by geo7** [comment]
this works http://vpaste.net/j2e9m

thats the template.... no idea why that does and mine doesn't :/

**Comment by justbur** [comment]
Sorry still can't replicate. Do you get errors on this dotfile? What are the errors if you do?

**Comment by geo7** [comment]
maybe relevant 

```
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-refresh-all' originally mapped on `G''
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-git-command' originally mapped on `:''
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC''
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-blame-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC''
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `scroll-up' originally mapped on `SPC''
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-read-revs-map':
   - `self-insert-command' originally mapped on `SPC''
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC''
(No files need saving)
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC''
Quit
```

**Comment by justbur** [comment]
Wait... you're on a commit that's 15 days old. Were you aware of that?

**Comment by geo7** [comment]
Wowww, apparently the unstaged changes have been messing up my update script. 

Not sure why these are in git status tho 

```
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    private/README.md
	deleted:    private/snippets/README.md
```

**Comment by justbur** [comment]
these files are tracked according to .gitignore
```
!private/README.md
!private/snippets/README.md
!private/local/README.md
```

**Comment by geo7** [comment]
i've no idea what's going on with this at the mo, I've symlinked my private directory to ~/.emacs.d from somewhere else, but then when I add these readme things back in to shut git up and allow me to update it gets rid of all my symlinked stuff

**Comment by geo7** [comment]
right I've just deleted things that complained and I'm on this now


```
commit ae475c06c40e384a60061d7e5df644bbb0065927
Author: syl20bnr <sylvain.benner@gmail.com>
Date:   Sat Sep 26 11:06:45 2015 -0400

    base: move toggles for editing styles
    
    SPC t E e -> emacs
    SPC t E h -> hybrid

M	doc/DOCUMENTATION.org
M	layers/+distribution/spacemacs-base/packages.el
```

**Comment by geo7** [comment]
Well, it's working now. What a monument of stupidity this has proven to be (keep things up to date!) 

I'm not sure how to go about symlinking my private directory from somewhere else now though, as I wanted to keep that source controlled with my dotfiles. 

thanks though, I guess I'll close this now :/

**Comment by geo7** [comment]
Just opened magit and get the following in messages buffer : 

```text
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-blame-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-read-revs-map':
   - `self-insert-command' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-blame-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-read-revs-map':
   - `self-insert-command' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-blame-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-read-revs-map':
   - `self-insert-command' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-status-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-refs-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-blame-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-diff-mode-map':
   - `scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-read-revs-map':
   - `self-insert-command' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-log-select-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-cherry-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-reflog-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-refresh-all' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-git-command' originally mapped on `:'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `magit-process-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'
Saving file /home/vco/dotfiles/emacs-misc/misc-configs/bx_functions.el...
Wrote /home/vco/dotfiles/emacs-misc/misc-configs/bx_functions.el
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `git-rebase-mode-map':
   - `magit-diff-show-or-scroll-up' originally mapped on `SPC'

```
