### ISSUE TITLE
Evil surround command doesn't repeat with dot

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4641]
The evil surround command doesn't repeat with the dot command.

1. Delete some text: `dw`
2. Surround some text: `yse"`
3. Press dot to repeat: `.`

Expected: repeats surround command.
Actual: repeats delete command.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: develop (rev. 9b77891)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 dash elfeed erc finance gtags ibuffer mu4e org ranger
 (shell :variables shell-default-shell 'shell shell-default-term-shell "/usr/bin/zsh" shell-default-height 50)
 spacemacs-layouts version-control git github c-c++ clojure common-lisp emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml evil-cleverparens mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-mpc)
```

**Comment by StreakyCobra** [comment]
Reproduced here.

**Comment by a-sk** [comment]
It is 2 years old bug in evil-surround: https://github.com/timcharper/evil-surround/issues/24
Hope somebody could help here.

**Comment by lislon** [comment]
Fixed :smile_cat:

**Comment by StreakyCobra** [comment]
Nice @lislon :+1:

**Comment by ninrod** [comment]
see #7662. I think we have some sort of reggression.

**Comment by ninrod** [comment]
@StreakyCobra have you tested this in the latest version of evil-surround? I think the error is back.

**Comment by StreakyCobra** [comment]
@ninrod Indeed it seems that this is happening again. I see you already reported it to both spacemacs and evil-surround so I can't help you more as otherwise I would had recommended you to do so :-)

**Comment by ninrod** [comment]
@StreakyCobra, thanks. it is a confirmed regression, I've indentified the offending commit and have reverted it in a pull-request. Waiting for the mantainer to show up.
