### ISSUE TITLE
pony-manage nonfunctional, gives helm error

### ISSUE THREAD

**Issue by BrianHicks** [syl20bnr/spacemacs#517]
When running pony-manage (`m j m`) helm complains "Error: trying to run helm within a running helm session"

I've [opened a discussion](https://groups.google.com/forum/#!topic/pony-mode/V60Np-aHaOM) with the pony-mode maintainers, and I will keep this issue updated.

**Comment by syl20bnr** [comment]
Be sure to verify that it is not a helm upgrade issue.
I have a lot of user issues with helm each time there is a new version. Wipe out your elpa directory and restart spacemacs. It wil likely resolve your issue.

**Comment by syl20bnr** [comment]
Keeping track of this issues here: https://github.com/emacs-helm/helm/issues/853

**Comment by BrianHicks** [comment]
Doesn't look like it is, I even wiped out `~/.emacs.d` and did a fresh install and the error still persists. I'm thinking I'm just going to have to roll up my sleeves and learn more elisp. (which is not a bad thing at all!)

**Comment by tuhdo** [comment]
Is it reproducible with `./emacs-helm.sh`? The script is inside helm installation directory in `elpa/`. I did not have problem with Helm using my Emacs configuraiton. Btw, what is that `pony-manage`? The error suggests that the command is being executed when there is an existing Helm session running. You can only have one Helm session running at a time.

**Comment by BrianHicks** [comment]
`pony-manage` is this command: https://github.com/davidmiller/pony-mode/blob/master/src/pony-mode.el#L745-L758. I don't see anything in there that would specifically cause problems, but I'm very new to this so do you?

**Comment by tuhdo** [comment]
I opened an issue  for Helm here: https://github.com/emacs-helm/helm/issues/855. You can read the details why the command fails there.

However, if this is not able to fixed in Helm, someone should create a PR for `pony-mode` to supoprt Helm. That is, if it detect `helm-mode`, don't use `minibuffer-with-setup-hook` and use `helm-comp-read` instead.

**Comment by tuhdo** [comment]
We can suggest the author of `pony-mode` to account for Helm like this:

```elisp
(minibuffer-with-setup-hook (lambda () (unless helm-mode
                                         (minibuffer-complete)))
  (completing-read "Manage: "
                   (pony-list-commands)))
```

It should be applied in this place: https://github.com/davidmiller/pony-mode/blob/master/src/pony-mode.el#L551 and this: https://github.com/davidmiller/pony-mode/blob/master/src/pony-mode.el#L613

In fact, a function named `pony-minibuffer-complete` should be created to replace the above lambda.

Someone should make a PR.

**Comment by tuhdo** [comment]
The latest commit in `pony-mode` was from `May 2014` and I doubt that even a PR is created, it would be noticed by the author soon. It would be better for Spacemacs to fix this issue in general, to avoid future packages do the same thing. 

```elisp
(defun minibuffer-complete ()
  "Complete the minibuffer contents as far as possible.
Return nil if there is no valid completion, else t.
If no characters can be completed, display a list of possible completions.
If you repeat this command after it displayed such a list,
scroll the window of possible completions."
  (interactive)
  (unless helm-mode
    (completion-in-region (minibuffer-prompt-end) (point-max)
                          minibuffer-completion-table
                          minibuffer-completion-predicate)))
```

There, from now on the code won't be executed when Helm is enabled; otherwise, behaviour is the same.

**Comment by tuhdo** [comment]
To solve this issue without modifying something, I think the only way is to use `pony-manage` as is, without Helm enable because it is intended to use that way, which conflicts with Helm. To disable a command to be used with `helm-mode`, you can customize [helm-completing-read-handlers-alist](https://github.com/emacs-helm/helm/wiki#201-customize-how-helm-mode-behave).

**Comment by CestDiego** [comment]
I still have this issue... I will try @tuhdo 's solution and update soon

**Comment by CestDiego** [comment]
ok using 
```elisp
  (add-to-list 'helm-completing-read-handlers-alist '(pony-manage . ido))
```

makes it work but feels weird and also I still get an error

**Comment by tuhdo** [comment]
That's external error and you are using Ido so it's another issue now.

**Comment by cpaulik** [comment]
Is this still a problem? I can not reproduce this.

**Comment by BrianHicks** [comment]
TBH I don't use Django anymore, so I haven't run into the problem. @CestDiego?

**Comment by CestDiego** [comment]
Never used pony myself

**Comment by BrianHicks** [comment]
Er, did I mention the wrong person then? You said you have this problem on 4/22?

**Comment by CestDiego** [comment]
Wat. My mind is betraying me somehow. I guess I gave up on this immediately and forgot everything about it.

**Comment by StreakyCobra** [comment]
As far as I tested, I can't reproduce this. As the original author is not using django anymore, and there was no complaints since April, I close it. Feel free to reopen it or open a new issue if it appears again :smiley:
