### ISSUE TITLE
quick install instruction fails if .emacs.d already exists

### ISSUE THREAD

**Issue by jwaldmann** [syl20bnr/spacemacs#5538]
README says:

```
**Quick Install:**

    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

which gives

```
fatal: destination path '/home/me/.emacs.d' already exists and is not an empty directory.
```

Then what? I can clone to someplace else and move some of the subdirs (from browsing init.el, at least core/ is needed) but that does not look right - spacemacs then sits in .emacs.d/core/ ? This path should be one level deeper, and contain the "spacemacs" name?

**Comment by d12frosted** [comment]
If it fails for you check [full installation instructions](https://github.com/syl20bnr/spacemacs#default-installation). Besides, you are talking about `init.el` file which makes me conclude that you already know a bit about Emacs. So you should know what to do with `.emacs.d` :)

**Comment by jwaldmann** [comment]
Thanks for the quick response. I see. Perhaps it'd have been more clear to me when I read very early in the docs (for new users) that this is intended as a full replacement for emacs (it is?) -- and not just another emacs lisp package, to be installed alongside.

**Comment by StreakyCobra** [comment]
PR welcome (read CONTRIBUTING.org first ;-) )

**Comment by CarlQLange** [comment]
Recommend this is marked as 'fixed in develop' since https://github.com/syl20bnr/spacemacs/commit/6c68694a43afcb6f420fdb9c68b51a7f7844d36a

**Comment by harishvishwakarma** [comment]
I had the same issue today

**Comment by duianto** [comment]
@harishvishwakarma The `develop` branch readme quick install instructions:
https://github.com/syl20bnr/spacemacs/tree/develop
describes how to avoid this issue:
>This assumes you don't have an existing Emacs setup and want to run Spacemacs as your config. If you do have one, look at the full installation instructions for other options.

The master branch readme will be updated when next version is released.

**Comment by srdjus** [comment]
I don't know if people still have the same problem, but for me, the only solution was installing a newer version of Emacs. I'm on Ubuntu and default Emacs version was 25, installing Emacs 26 fixed the problem.
