### ISSUE TITLE
MELPA persp-mode breaks opening a file in an existing frame using emacsclient 

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#5867]
#### Description

Reverting to MELPA persp-mode (859f28473b9e9d9535fcaab046ad67688c6e5a28) broke calling `emacsclient $filename` to open a file in an existing frame.
#### Reproduction guide
- Start Emacs as a daemon
- Open an emacs frame.
- Call `emacsclient -s /path/to/emacs/socket $filename`

**Observed Behavior**

```
*ERROR*: Wrong type argument: processp, nowait
```

**Expected Behavior**

The file is opened in the existing frame.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b21c71)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(spacemacs-helm better-defaults git
                (auto-completion :variables auto-completion-return-key-behavior nil)
                org spell-checking syntax-checking
                (shell :variables shell-default-shell 'ansi-term)
                emacs-lisp markdown latex yaml c-c   html haskell go javascript python
                (rust :variables rust-format-on-save nil))
```

**Comment by StreakyCobra** [comment]
Can someone try to reproduce with just `persp-mode` and `magit` enabled? (`SPC q D` is helpful for this)

**Comment by Stebalien** [comment]
This is actually unrelated to magit; it shows up even if all layers are disabled (`dotspacemacs-configuration-layers` is empty). However, I can't reproduce it by starting emacs with persp-mode only (`/usr/bin/emacs --debug-init --daemon -q --execute "(progn (package-initialize) (require 'use-package)(use-package persp-mode))"`.

**Comment by bmag** [comment]
@Stebalien that command-line doesn't activate persp-mode. Try testing with this one:
```
/usr/bin/emacs --debug-init --daemon -q --execute "(progn (package-initialize) (setq persp-auto-resume-time -1) (require 'persp-mode) (persp-mode))"
```

**Comment by Stebalien** [comment]
I still can't reproduce it.

-- 
Steven Allen
((Do Not Email <honeypot@stebalien.com>))

**Comment by hedning** [comment]
Does it work to use the --create-frame option, that seems to work for me at least.

**Comment by Stebalien** [comment]
@hedning Yes.

**Comment by krotton** [comment]
I have the exact same problem (which not only manifests itself when launching emacsclient, rendering into an existing frame, but also when trying to use any command that uses an embedded editor - most notably commit - in magit) and I've noticed that after you execute `persp-mode` in a running server session, the problem disappears. It reappears after the configuration is reloaded (or server restarted).

**Comment by bmag** [comment]
I can't reproduce the bug. I've tried these steps, and it all worked fine: (bash terminal)
```
$ emacs --daemon
$ emacsclient -c &
$ emacsclient init.el
```

persp-mode version: 20160425.2309

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. c2fc02e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(spacemacs-ivy
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 pdf-tools evil-cleverparens python command-log smex themes-megapack c-c++ ruby common-lisp ibuffer octave imenu-list window-purpose nameless)
```

**Comment by jmcarthur** [comment]
I'm running into a similar issue with an in-house package we use at work. The issue is only reproducible with `emacsclient -n -c`, not with `emacsclient -c`.

**Comment by syl20bnr** [comment]
Any news on this bug? We are using the upstream version of `persp-mode`, I think this has been fixed.

**Comment by ChShersh** [comment]
@krotton Could you please provide more details how to execute `:persp-mode`? I'm a Spacemacs beginner, I used Emacs previously and I didn't have issues with Magit there.

**Comment by krotton** [comment]
@ChShersh Honestly, I don't remember. I haven't used Spacemacs for quite a long time now. Isn't it just `:persp-mode` (and then Enter) in normal mode?

**Comment by ChShersh** [comment]
@krotton Thanks for your answer! I tried it but it didn't help me :cry:  I still get _GitError_ when trying to commit changes using `magit` :disappointed:
