### ISSUE TITLE
Startup error for python layer in fresh cloned spacemacs.

### ISSUE THREAD

**Issue by CharlesHD** [syl20bnr/spacemacs#6246]
#### Description :octocat:
Startup error for python layer in fresh cloned spacemacs.

#### Reproduction guide :beetle:
- Clone develop branch of spacemacs in .emacs.d/
- Start Emacs
- select Vim bindings, classic distribution and helm
- add python layer to the newly created .spacemacs
- restart Emacs

*Observed behaviour:* :eyes:
Raise an error at startup, see below for the debug-init backtrace.

*Expected behaviour:* :broken_heart:
Just start normaly and be happy.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 96fcce7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
    bepo
```

#### Backtrace :paw_prints:
[here the full backtrace](https://gist.github.com/CharlesHD/68d47e3bca9cd4cff5861bc10302106c)

**Comment by TheBB** [comment]
Probably introduced by @cpaulik's commit?

@CharlesHD By the way your issure report shows no python layer. You are probably setting `dotspacemacs-configuration-layers` in two different places in your dotfile. You should remove one of them. It should be set *once* within the `dotspacemacs/layers` function.

**Comment by syl20bnr** [comment]
Are the repro steps enough to see an error? The error should be at startup? I have no error when following them. What were your python layer variables ?

**Comment by syl20bnr** [comment]
Ok it should be at startup, I think we need your layer variables as well, I have no error on my config.

**Comment by whatot** [comment]
same problem.
Error shows '**wrong type argument: listp, nose**',
It should be in 'layers/+lang/python/funcs.el:77'.
Change should be in `56ee037 syl20bnr - python: prefix functions with spacemacs`

**Comment by syl20bnr** [comment]
I see the problems, it is not due to the added prefix.
@cpaulik I'll work on it tomorrow, I want to fix several things in the python layer.

**Comment by nixmaniack** [comment]
I did have that error but I added `python-test-runner '(nose pytest)` in `:variables` based on commit history to get it working.

**Comment by CharlesHD** [comment]
@nixmaniack Indeed after adding that variable to python layer it works ! Thanks for the quick fix.
@syl20bnr My python variables was all set to default (didn't change anyone)

**Comment by cpaulik** [comment]
Thanks @syl20bnr . I also noticed that the python layer variables are not set according to the variables in the `.spacemacs`.

**Comment by cpaulik** [comment]
@syl20bnr What are the problems? I would like to fix the issue with variables not being set correctly but could not yet find a difference to the other layers, in which it works correctly.

**Comment by robbyoconnor** [comment]
This seems to be only an issue in Emacs 25

**Comment by Tehnix** [comment]
@cpaulik with just `python` in the layers it will complain about `Wrong type argument: listp, nose`. The workaround that @nixmaniack posted works.

Looking at https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/python/config.el#L21 I guess it's an issue with the default value not being of the type listp (or not being able to accept both lists and a singular value)?

**Comment by cpaulik** [comment]
I can not reproduce this on the `develop` branch, even with emacs 25. Looking at https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/python/funcs.el#L97 both listsp and a singuar value should be supported.

**Comment by nixmaniack** [comment]
@cpaulik [This](https://github.com/syl20bnr/spacemacs/blob/3a5edf9f05e682d2bbb4f348d67e3cb04cbf58ec/layers/%2Blang/python/packages.el#L147) and [this](https://github.com/syl20bnr/spacemacs/blob/3a5edf9f05e682d2bbb4f348d67e3cb04cbf58ec/layers/%2Blang/python/packages.el#L233) needs a fix. 

If you have `'pytest` as `python-test-runner` then it fails to initialize spacemacs. Similarly the other case as well. Checking for `listp` in second `or` condition should fix it. Feel free to make PR as I won't be able to do it at the moment.

**Comment by cpaulik** [comment]
Hmm, @nixmaniack I just installed GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-08-20 and with this in my `.spacemacs`:

```
     (python
      :variables
      python-enable-yapf-format-on-save nil
      python-auto-set-local-pyenv-version 'on-project-switch
      python-test-runner 'pytest)
```
can still not reproduce the problem. Evaluating `(member 'pytest python-test-runner)` just evaluates to `pytest` for me.

`SPC h d v` gives me
```
python-test-runner is a variable defined in ‘config.el’.
Its value is ‘pytest’
```

**Comment by nixmaniack** [comment]
I see. Here's `ielm` session in my two different emacs versions. 

On **25.1.50.1** 
```
ELISP> (setq python-test-runner 'pytest)
pytest
ELISP> (member 'pytest python-test-runner)
*** Eval error ***  Wrong type argument: listp, pytest
ELISP> (emacs-version)
"GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42))\n of 2016-06-16"
```

But on **24.5.1**

```
ELISP> (setq python-test-runner 'pytest)
pytest
ELISP> (member 'pytest python-test-runner)
nil
ELISP> (emacs-version)
"GNU Emacs 24.5.1 (x86_64-apple-darwin15.0.0, Carbon Version 157 AppKit 1404.13)\n of 2016-06-16 on blackhole.global"
```

I think that should clarify now.

**Comment by cpaulik** [comment]
Ok. Which emacs 25 pretest did you download? I can not find 25.1.50.1 on http://alpha.gnu.org/gnu/emacs/pretest/.

This might be a bug in one of the emacs 25 previews since it works on rc1:

```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (setq python-test-runner 'pytest)
pytest
ELISP> (member 'pytest python-test-runner)
nil
ELISP> (emacs-version)
"GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9)\n of 2016-08-20"
ELISP> 
```

**Comment by nixmaniack** [comment]
I didn't directly download from gnu.org but I let the [`brew`](http://brew.sh/) do the job for me of getting the `HEAD` code and building it. It's been time since I last did the build. I'll try with latest `HEAD` and see if it fixes. 

OTOH, I assume there will be users who will be in similar situation based on the reporting on this thread.

**Comment by nixmaniack** [comment]
I did the rebuild of my emacs to latest `HEAD`. Still same issue. Also I'm not sure how `25.1.50.1
```
ELISP> (setq python-test-runner 'pytest)
pytest
ELISP> (member 'pytest python-test-runner)
*** Eval error ***  Wrong type argument: listp, pytest
ELISP> (emacs-version)
"GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42))\n of 2016-08-20"
```

So the other difference could be OS X vs GNU/Linux?

**Comment by d12frosted** [comment]
@nixmaniack The `Emacs 25.1.50.1` comes from Emacs itself. Other stuff is generated based on your system. But `25.1.50.1` should not differ from GNU/Linux versions. This is HEAD version. If you wish to try `25.1-rc1` use `--devel` option during emacs installation.

```
$ brew install emacs-plus --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --with-spacemacs-icon --devel
```

**Comment by cpaulik** [comment]
After building the emacs master branch I was able to reproduce this. I'll investigate if this is a planned change or should be considered a bug. Meanwhile #6883 should fix it.

**Comment by cpaulik** [comment]
There is a discussion about it at https://lists.gnu.org/archive/html/emacs-devel/2016-01/msg01639.html It seems that there was no consensus but there are these three commits in master

```
d27c807 Re-enable checks in member, memql, delete to complain about non-lists
df5ae7d Revert "Re-enable checks in member, memql, delete to complain about non-lists"
f524e8b Re-enable checks in member, memql, delete to complain about non-lists
```

which enable the checks for that branch. But it seems that it is not planned for emacs 25.

**Comment by nixmaniack** [comment]
@d12frosted I see. I did not know about `--devel`. Thanks for explaining. 

And thanks @cpaulik for investigating and PR! 👍

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
