### ISSUE TITLE
`outline-show-all` void when using `ediff`

### ISSUE THREAD

**Issue by jdnavarro** [syl20bnr/spacemacs#6500]
When trying to use `ediff` through `SPC f e D` I'm getting the error: `Symbol function definition is void: outline-show-all`.

This bug might have been introduced recently. It happened just after I pulled from `develop` today.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm html auto-completion emacs-lisp git github haskell html java markdown osx
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
      scala spell-checking syntax-checking version-control yaml)
```

**Comment by chrismcg** [comment]
I'm seeing this too when I try `SPC f e D`

#### System Info :computer:
- OS: darwin
- Emacs: 25.0.92.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 colors company-mode deft editor-config emacs-lisp elixir elm erlang evil-commentary eyebrowse git github html javascript markdown nginx
 (org :variables org-enable-github-support t)
 osx pandoc pdf-tools perspectives plantuml python react restclient
 (ruby :variables rbenv-installation-dir "/usr/local")
 ruby-on-rails
 (shell :variables shell-default-term-shell "/usr/local/bin/zsh")
 sql spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 unimpaired version-control yaml)
```

**Comment by NJBS** [comment]
Bug introduced by https://github.com/syl20bnr/spacemacs/commit/00a616

PR here https://github.com/syl20bnr/spacemacs/pull/6519

**Comment by syl20bnr** [comment]
Should be fixed in develop thanks to @NJBS

**Comment by xificurC** [comment]
I pulled develop but I'm stil seeing this issue upon `SPC f e D`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 9499e24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(vimscript html javascript helm spacemacs-evil emacs-lisp version-control
           (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30)
           org syntax-checking auto-completion docker evil-commentary shell shell-scripts erc git markdown yaml scala scheme graphviz)
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function outline-show-all)
  outline-show-all()
  run-hooks(ediff-prepare-buffer-hook)
  ediff-setup(#<buffer .spacemacs> "/home/UX/pnagyux/.spacemacs" #<buffer .spacemacs.template> "/home/UX/pnagyux/.emacs.d/core/templates/.spacemacs.template" nil nil nil ((ediff-job-name . ediff-files)) nil)
  ediff-files-internal("/home/UX/pnagyux/.spacemacs" "/home/UX/pnagyux/.emacs.d/core/templates/.spacemacs.template" nil nil ediff-files)
  ediff-files("/home/UX/pnagyux/.spacemacs" "/home/UX/pnagyux/.emacs.d/core/templates/.spacemacs.template")
  spacemacs/ediff-dotfile-and-template()
  call-interactively(spacemacs/ediff-dotfile-and-template nil nil)
  command-execute(spacemacs/ediff-dotfile-and-template)
```

**Comment by syohex** [comment]
`outline-show-all` was introduced at Emacs 25. spacemacs uses `show-all` instead of it or defines alias of it for older Emacs.

**Comment by chrismcg** [comment]
I'm still seeing the same problem on 9499e24 too. I am on 25.0.92.1.

It works if I open an org file first so org mode gets lazy loaded.

**Comment by sthysel** [comment]
Can confirm issue exist in 9499e2.

**Comment by syl20bnr** [comment]
My bad I moved the config to a `post-init` function which removed the fix... I'm not in front of a computer for now so I asked @NJBS to fix my mistake. Sorry!

**Comment by d12frosted** [comment]
I've pushed a fix that work both in Emacs 25 and Emacs 24. Let me know if it's not working for you.

CC @NJBS @syl20bnr @xificurC @chrismcg @sthysel 

NB! There is a critical bug that prevents proper loading - #6523. You can checkout that thread of a temporary workaround.

**Comment by der-Daniel** [comment]
Hi guys,

I had the same problem when trying to complete a `org capture`.
Emacs told me `outline-show-all` is void. I fixed it by setting an alias `(defalias 'outline-show-all 'show-all)`.

Can someone (maybe @d12frosted) give some more details what this is about. Where is the function located and why is it this weird.  
In this topic someone mentioned the `.el` file change from `outline-mode.el` to `outline.el`?

Is this still a bug in Emacs?


My set up:

Ubuntu 16.04  
GNU Emacs 24.5.1
Org-mode version 8.2.10

Cheers
Daniel

**Comment by d12frosted** [comment]
Hey @der-Daniel 

Would be helpful to know your version of Spacemacs (`SPC h d s`). Note that this was fixed in develop, but it's not yet part of `master` branch.

**Comment by der-Daniel** [comment]
I do not use Spacemacs. I use regular GNU Emacs. :sweat_smile:

**Comment by d12frosted** [comment]
@der-Daniel haha, it happens 😸 

Welp, `C-h f` is your friend. You can find where exactly `show-all` is defined as well as `outline-show-all`. 

```
show-all is an alias for ‘outline-show-all’ in ‘outline.el’.

(show-all)

This function is obsolete since 25.1;
use ‘outline-show-all’ instead.

Show all of the text in the buffer.

-----

outline-show-all is an interactive compiled Lisp function in ‘outline.el’.

(outline-show-all)

Show all of the text in the buffer.
```

**Comment by der-Daniel** [comment]
Thanks for this answer.  
Trying to track down this error and disabling some packages, I noticed that this error does not occur with every setting.

Looking again into my `elpa` folder I recognized, that one package (I guess `org-gcal`) installs a version of org, which is different from the built-in one. So there are two conflicting entries in my `load-path`.

What is a nice way to handle such a conflict. I simply deleted the `org` package in the `elpa` folder, so the API calls by `org-gcal` were simply served by the built-in `org-mode`.  
Can I somehow get Emacs to remove entries to dirs like `/usr/share/emcas/lisp/org`? They appear to be loaded what so ever.

**Comment by d12frosted** [comment]
@der-Daniel 

I don't think that removing `/usr/share/emcas/lisp/org` is a good idea. As whenever you reinstall / update Emacs it will be filled again. Usually I make sure that downloaded `org` is before built-in one in `load-path`. And then conflict goes away 😸

**Comment by der-Daniel** [comment]
Hi,

this sounds like a possible work around. But how do you manipulate the `load-path` in such a way.
Is there a `hook` for it?

I mean isn't having a manipulation in my `.emacs` file too late, since the `load-path` is alreay partly built?

Cheers
Daniel

**Comment by TheBB** [comment]
Whatever value `load-path` has when something is loaded is the one that takes effect. It's too late for stuff that is loaded before you set `load-path` but it's early enough for stuff that is loaded after that.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
