### ISSUE TITLE
haskell mode: indentation must be configured? How?

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#706]
haskell-mode was indenting using hi2 and I didn't have problems but with the latest upgrade it doesn't work anymore.
I now get the error:

haskell-mode-suggest-indent-choice: You tried to do an indentation command, but an indentation mode has not been enabled yet.
Run M-x describe-variable haskell-mode-hook for a list of such modes.

I tried but failed to configure the indentation mode. I think this should be documented in the haskell contribution README:
https://github.com/syl20bnr/spacemacs/blob/master/contrib/lang/haskell/README.md

I guess I must enter something in my .spacemacs?

**Comment by bjarkevad** [comment]
If you're using `master`, would you mind trying out `develop`? I think we might have fixed this issue :)

**Comment by emmanueltouzery** [comment]
yes I think you're right. Switching to develop fixed it. I'd rather stay on master however. Is it one commit that I can cherry pick, or should I just overwrite the haskell subfolder with the develop version? Thank you!

**Comment by bjarkevad** [comment]
I'm not really sure what fixed it, but it should hit master soon-ish. You could just overwrite the folder for now :-)

**Comment by syl20bnr** [comment]
The only thing that is fixed in `develop` and not in `master` is a fix for the lazy loading on `helm-c-yasnippet`, do you think it could be the cause ?

**Comment by bjarkevad** [comment]
It sounds a bit strange to me, but I haven't had time to look into it.

**Comment by syl20bnr** [comment]
Seems to be fixed in 0.64.0, reopen it if the issue reappears.

**Comment by emmanueltouzery** [comment]
I'm still seeing it randomly with 0.65.2. Not all the time! In certain situations. Currently I don't know when it happens. Still tracking it down, it's pretty random. Most of the time I'd say it works fine.

**Comment by syl20bnr** [comment]
@imalsogreg encounters the same issue. Seems OK when the haskell layer is the only one in the dotfile. But your experience shows that it should be more complexe than this.

**Comment by emmanueltouzery** [comment]
hmm now it seems reliably broken for me. I don't want to induce you in error: I change my spacemacs config *all the time* at this point. So the breaking/unbreaking may not be random but due to my changing the config. Right now it seems really consistently broken yes. Can't get it to work anymore.

**Comment by byorgey** [comment]
I was encountering this as well.  I finally figured out the problem: I had added
```
(add-hook 'haskell-mode-hook 'haskell-indentation)
```
to my `.emacs`, just like http://projects.haskell.org/pipermail/haskellmode-emacs/2015-April/000202.html said to.  Unfortunately, the correct command is
```
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
```
and there is no indication that anything is wrong if you put the former, other than no indentation mode being turned on.

**Comment by all3fox** [comment]
This issue is present on Arch linux with emacs `24.5.1` and the `emcacs-haskell-mode-git` package from the AUR, which automatically clones the latest master branch. So, the package basically tells the user "configure indentation" and the last line provided by @byorgey does the trick:

```lisp
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
```
into your `~/.emacs` settings file.

**Comment by mrkgnao** [comment]
Can confirm, I'm on Arch with emacs `24.5.11 as well. That line has to be addd to the "initialization hooks" section for it to work. Thought I'd say that for those who are as clueless as I was fifteen minutes back :)
