### ISSUE TITLE
dotspacemacs/user-config not evaluated when running as a daemon

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#7114]
#### Description :octocat:
Commit fd9ac4afce89d15130175d640e37194a8957b2ec causes `dotspacemacs/user-config` to not be evaluated on start when running emacs as a daemon.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

None of the settings in `dotspacemacs/user-config` have been applied.

Unfortunately, I don't see any useful messages in `*Messages*`.

*Expected behaviour:* :heart: :smile:

The settings in `dotspacemacs/user-config` have been applied.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. fd9ac4a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm better-defaults git github
      (shell :variables shell-default-shell 'eshell)
      org
      (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-return-key-behavior nil)
      spell-checking syntax-checking emoji systemd emacs-lisp markdown latex bibtex csv yaml c-c   html haskell go javascript python csv asm
      (rust :variables rust-format-on-save nil))
```

**Comment by TheBB** [comment]
Most likely there is something wrong with your user-config function. Mine is certainly being run, and I'd gather post people's, or we would be buried by reports about this already. Try replacing it with something that does nothing other than printing a message.

**Comment by Stebalien** [comment]
I've already tried that; it doesn't run. However, re-loading the config `SPC f e R` causes it to be run. We're probably not buried in reports because:

1. Most people don't run spacemacs as a daemon.
2. The commit that introduced the bug was pushed last night (reverting this commit reliably fixes the bug).

---

 Anyways, I somehow managed to miss the fact that I had a `*Warnings*` buffer (I usually just look in `*Messages*`) with the following warning:

```
Warning (initialization): An error occurred while loading `/home/steb/.emacs.d/init.el':

Wrong type argument: wholenump, -29

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

I'm not sure how this works but it looks like the new commit assumes that we're either operating in GUI or TUI mode (never as a daemon). The old version used to check `(display-graphic-p)`, the new version doesn't.

**Comment by deb0ch** [comment]
Hum. I removed that because it prevented stuff to be centered when in terminal.

Anybody knows how to fix that ?

Whatever, it is strange that we are not having the error when also in daemon.

**Comment by deb0ch** [comment]
Does https://github.com/deb0ch/spacemacs/commit/11c05c0759b96603a19162fb289761e2dbb4555b fix the problem ?

**Comment by Stebalien** [comment]
@deb0ch No but setting the minimum to 39 does.

Is there no way to check for the existence of a frame?

**Comment by TheBB** [comment]
Can you do as the warning says so we get a backtrace?

**Comment by Stebalien** [comment]
I'm having a bit of a chicken-egg problem. I can't reproduce the problem without enabling daemon mode but, if I pass the `--debug-init` flag, emacs drops into the debugger before it creates the daemon socket (so I can't connect to it to get at the backtrace).

**Comment by Stebalien** [comment]
Nevermind, instead of running in daemon mode, I replaced the call to ` (setq spacemacs-buffer--banner-length (window-width))` with ` (setq spacemacs-buffer--banner-length 0)` (to simulate the lack of a frame).

```
Debugger entered--Lisp error: (wrong-type-argument wholenump -39)
  make-string(-39 9472)
  (concat caption (make-string (+ (- fill-column caption-len 1) hpadding) 9472))
  (if caption (concat caption (make-string (+ (- fill-column caption-len 1) hpadding) 9472)) (make-string fill-column 9472))
  (concat "╭─" (if caption (concat caption (make-string (+ (- fill-column caption-len 1) hpadding) 9472)) (make-string fill-column 9472)) (make-string hpadding 9472) "╮\n" (spacemacs//render-framed-line "" hpadding) (mapconcat (function (lambda (x) (spacemacs//render-framed-line x hpadding))) (split-string (buffer-string) "\n" nil) "") (spacemacs//render-framed-line "" hpadding) "╰" (make-string hpadding 9472) (make-string fill-column 9472) (make-string hpadding 9472) "╯")
  (let* ((hpadding (or hpadding 1)) (fill-column (if width (- width (+ 2 (* 2 hpadding))) fill-column)) (sentence-end-double-space nil) (caption-len (length caption))) (fill-region (point-min) (point-max) (quote justify) (quote nosqueeze)) (concat "╭─" (if caption (concat caption (make-string (+ (- fill-column caption-len 1) hpadding) 9472)) (make-string fill-column 9472)) (make-string hpadding 9472) "╮\n" (spacemacs//render-framed-line "" hpadding) (mapconcat (function (lambda (x) (spacemacs//render-framed-line x hpadding))) (split-string (buffer-string) "\n" nil) "") (spacemacs//render-framed-line "" hpadding) "╰" (make-string hpadding 9472) (make-string fill-column 9472) (make-string hpadding 9472) "╯"))
  (progn (if (not (file-exists-p content)) (insert content) (insert-file-contents content) (goto-char (point-max)) (delete-char -1)) (let* ((hpadding (or hpadding 1)) (fill-column (if width (- width (+ 2 (* 2 hpadding))) fill-column)) (sentence-end-double-space nil) (caption-len (length caption))) (fill-region (point-min) (point-max) (quote justify) (quote nosqueeze)) (concat "╭─" (if caption (concat caption (make-string (+ (- fill-column caption-len 1) hpadding) 9472)) (make-string fill-column 9472)) (make-string hpadding 9472) "╮\n" (spacemacs//render-framed-line "" hpadding) (mapconcat (function (lambda (x) (spacemacs//render-framed-line x hpadding))) (split-string (buffer-string) "\n" nil) "") (spacemacs//render-framed-line "" hpadding) "╰" (make-string hpadding 9472) (make-string fill-column 9472) (make-string hpadding 9472) "╯")))
  (unwind-protect (progn (if (not (file-exists-p content)) (insert content) (insert-file-contents content) (goto-char (point-max)) (delete-char -1)) (let* ((hpadding (or hpadding 1)) (fill-column (if width (- width (+ 2 ...)) fill-column)) (sentence-end-double-space nil) (caption-len (length caption))) (fill-region (point-min) (point-max) (quote justify) (quote nosqueeze)) (concat "╭─" (if caption (concat caption (make-string (+ ... hpadding) 9472)) (make-string fill-column 9472)) (make-string hpadding 9472) "╮\n" (spacemacs//render-framed-line "" hpadding) (mapconcat (function (lambda (x) (spacemacs//render-framed-line x hpadding))) (split-string (buffer-string) "\n" nil) "") (spacemacs//render-framed-line "" hpadding) "╰" (make-string hpadding 9472) (make-string fill-column 9472) (make-string hpadding 9472) "╯"))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if (not (file-exists-p content)) (insert content) (insert-file-contents content) (goto-char (point-max)) (delete-char -1)) (let* ((hpadding (or hpadding 1)) (fill-column (if width (- width ...) fill-column)) (sentence-end-double-space nil) (caption-len (length caption))) (fill-region (point-min) (point-max) (quote justify) (quote nosqueeze)) (concat "╭─" (if caption (concat caption (make-string ... 9472)) (make-string fill-column 9472)) (make-string hpadding 9472) "╮\n" (spacemacs//render-framed-line "" hpadding) (mapconcat (function (lambda ... ...)) (split-string (buffer-string) "\n" nil) "") (spacemacs//render-framed-line "" hpadding) "╰" (make-string hpadding 9472) (make-string fill-column 9472) (make-string hpadding 9472) "╯"))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if (not (file-exists-p content)) (insert content) (insert-file-contents content) (goto-char (point-max)) (delete-char -1)) (let* ((hpadding (or hpadding 1)) (fill-column (if width ... fill-column)) (sentence-end-double-space nil) (caption-len (length caption))) (fill-region (point-min) (point-max) (quote justify) (quote nosqueeze)) (concat "╭─" (if caption (concat caption ...) (make-string fill-column 9472)) (make-string hpadding 9472) "╮\n" (spacemacs//render-framed-line "" hpadding) (mapconcat (function ...) (split-string ... "\n" nil) "") (spacemacs//render-framed-line "" hpadding) "╰" (make-string hpadding 9472) (make-string fill-column 9472) (make-string hpadding 9472) "╯"))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  spacemacs//render-framed-text("/home/steb/.emacs.d/core/info/release-notes/0.105.txt" 0 " Important Notes (Release 0.105.x) ")
  (concat "\n" (spacemacs//render-framed-text file spacemacs-buffer--banner-length caption))
  (let* ((note (concat "\n" (spacemacs//render-framed-text file spacemacs-buffer--banner-length caption)))) (add-to-list (quote spacemacs-buffer--note-widgets) (widget-create (quote text) note)) (funcall additional-widgets))
  (save-excursion (goto-char (point-min)) (search-forward "Search in Spacemacs]") (forward-line) (let* ((note (concat "\n" (spacemacs//render-framed-text file spacemacs-buffer--banner-length caption)))) (add-to-list (quote spacemacs-buffer--note-widgets) (widget-create (quote text) note)) (funcall additional-widgets)))
  spacemacs-buffer//insert-note("/home/steb/.emacs.d/core/info/release-notes/0.105.txt" " Important Notes (Release 0.105.x) " (lambda nil (add-to-list (quote spacemacs-buffer--note-widgets) (widget-create (quote push-button) :tag (propertize "Click here for full change log" (quote face) (quote font-lock-warning-face)) :help-echo "Open the full change log." :action (function (lambda (&rest ignore) (funcall (quote spacemacs/view-org-file) (concat spacemacs-start-directory "CHANGELOG.org") (format "Release %s.x" spacemacs-buffer-version-info) (quote subtree)))) :mouse-face (quote highlight) :follow-link "
"))))
  (let ((widget-func (function (lambda nil (add-to-list (quote spacemacs-buffer--note-widgets) (widget-create (quote push-button) :tag (propertize "Click here for full change log" ... ...) :help-echo "Open the full change log." :action (function ...) :mouse-face (quote highlight) :follow-link "
")))))) (spacemacs-buffer//insert-note file (format " Important Notes (Release %s.x) " spacemacs-buffer-version-info) widget-func))
  spacemacs-buffer//insert-release-note-widget("/home/steb/.emacs.d/core/info/release-notes/0.105.txt")
  (cond ((eq type (quote quickhelp)) (spacemacs-buffer//insert-quickhelp-widget file)) ((eq type (quote release-note)) (spacemacs-buffer//insert-release-note-widget file)) (t))
  spacemacs-buffer/toggle-note("/home/steb/.emacs.d/core/info/release-notes/0.105.txt" release-note)
  (cond (spacemacs-buffer--fresh-install (spacemacs-buffer/toggle-note (concat spacemacs-info-directory "quickhelp.txt") (spacemacs-buffer//insert-note-p (quote quickhelp))) (setq spacemacs-buffer--release-note-version spacemacs-version) (spacemacs/dump-vars-to-file (quote (spacemacs-buffer--release-note-version)) spacemacs-buffer--cache-file)) ((or (not spacemacs-buffer--release-note-version) (version< spacemacs-buffer--release-note-version spacemacs-version)) (spacemacs-buffer/toggle-note (concat spacemacs-release-notes-directory spacemacs-buffer-version-info ".txt") (quote release-note))))
  spacemacs-buffer/display-info-box()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs-buffer/display-info-box) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/steb/.emacs.d/init.el" nil t)  ; Reading at buffer position 1194
  load-with-code-conversion("/home/steb/.emacs.d/init.el" "/home/steb/.emacs.d/init.el" t t)
  load("/home/steb/.emacs.d/init" t t)
  #[0 "\205\262
```

**Comment by TheBB** [comment]
Fixed

**Comment by Stebalien** [comment]
So, I'm really sorry about this train-wreck of a bug report. I should have known better and given you everything up-front/actually read the relevant error message when I found it.

**Comment by TheBB** [comment]
Don't worry about it, actually as Spacemacs bug reports go this one isn't so bad. (Trust me, I get all of them in my inbox.)

**Comment by wbthomason** [comment]
Sorry to necro this thread, but I'm still having this problem. Specifically, I'm trying to toggle a few UI features in dotspacemacs/user-config. I get the correct behavior when I run emacs -nw my_file, but when I'm running emacs in daemon mode and run emacsclient -nw my_file, it's as though user-config hasn't been run. Running SPC f e R makes the UI features toggle on as they should, however. I am being careful to use the toggle-X-on functions instead of just toggle-X. Thus, I'm fairly sure the issue stems from running emacs daemonized. 

If this isn't the appropriate place/format, I apologize. I asked in the Gitter first, but nobody seemed to know.

**Comment by deb0ch** [comment]
Maybe a new issue would be better :smile_cat:
