### ISSUE TITLE
Add support for Facebook Flow language

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#7119]
--------------------------------
**👉   There is a bounty source opened on this issue, click on the badge or go to the associated PR #7208 for more info**

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=37889526)](https://www.bountysource.com/issues/37889526-some-request-support-facebook-flow-language?utm_source=37889526&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Feature list in order to complete this PR and unlcok the bounty:

- [ ] **Auto-completion**
The layer should activate `company-flow` whenever the buffer begins with either of these lines:
    - `// @flow`
    - `/* @flow */`
- [ ] **Syntax Highlighting**
The layer should improve syntax highlighting for `flow`. Right now it's mostly ok in `react-mode` and quite bad in `javascript-mode` (for instance, use of generics `Map<K, V>` breaks the syntax highlighting). There may be some inspiration in `emacs-flow-jsx`, `react-mode` and `typescript-mode`.
- [ ] **Documentation**
The type of current word should be rendered with `eldoc`, bonus points for highlighted `eldoc` like in `typescript`. `flow type-at-pos` should give the type.
- [ ] **Code Navigation**
Using `flow get-def` and `flow find-module` should enable amazing jump to definition functionality. I'd love to have them binded to <kbd>g</kbd> or <kbd>d</kbd> or at least local leader.

------------------------------
*Original message*

Hi guys, would be great if spacemacs could support facebook flow...seems than the tools are availables:

https://github.com/aaronjensen/company-flow
https://github.com/lbolla/emacs-flycheck-flow
https://lbolla.info/blog/2014/11/19/flycheck-checker-for-javascript-flow

flow is similar to typescript but developed by facebook and provides incremental typed javascript, so you can start with plain javascript and then add new types and get a typed/solid code

please check this and let me know if would be possible add it to spacemacs

 ------------------------------

*EDIT: [@syl20bnr] changed title and message body to reflect the bounty source attached to it.*

**Comment by TheBB** [comment]
If there are packages for it, of course it is possible. But someone will have to do the work.

**Comment by jondubin** [comment]
Would this make the most sense as it's own layer, part of the JavaScript layer, or possibly even part of the React layer?

**Comment by cocodrino** [comment]
I think than would be better include its own layer like typescript, which is the most similar layer to flow

**Comment by jdelStrother** [comment]
FWIW I created https://github.com/jdelStrother/dotfiles/tree/master/spacemacs_layers/flow-type for personal use.   I could try and tidy it up into a proper PR, though I'm not sure how much of it is useful to others.

**Comment by jdelStrother** [comment]
I'll try and add company-flow and submit a PR.

**Comment by jdelStrother** [comment]
@cocodrino if you fancy giving it a try, there's a first attempt at this at https://github.com/jdelStrother/spacemacs/tree/flow-type

**Comment by reem** [comment]
@jdelStrother I'm using your layer and the flycheck output works great, but my syntax highlighting is still atrociously broken. Do you know of any solution for this?

**Comment by jdelStrother** [comment]
@reem Hmm, the highlighting is fairly good for me: 

![image](https://cloud.githubusercontent.com/assets/2377/19182965/133ea18e-8c6e-11e6-9f5e-3369f352846c.png)

This is in js2-mode via the javascript layer, it's also good in react-mode.   Where are you seeing problems?

**Comment by cocodrino** [comment]
hello @jdelStrother , sorry for the delay, I'm trying to test it but I get

```bash
An error occurred while post-configuring web-mode in layer flow-type (error: (void-variable react-mode-hook))

and
Error connection time out for melpa repository!
Warning (spacemacs): 
Error connection time out for gnu repository!
Error (use-package): company-flow :init: Symbol’s value as variable is void: company-backends-react-mode

```

I created a folder named flow-types..put the files inside and in my spacemacs configuration add the flow-type layer. Do you know what could be the bug reason?..thank you!

**Comment by jdelStrother** [comment]
@cocodrino it was assuming that you have the react-layer installed.   I've just pushed a fix for that, could you give it another go?

**Comment by reem** [comment]
@jdelStrother turning off js mode warnings (`SPC-m-w`) fixed the syntax highlighting. Thanks for this great layer! Make working with flow much nicer :)

**Comment by cocodrino** [comment]
hi @jdelStrother I was testing the flow layer today but I'm receiving this message

```lisp

[yas] Reloaded everything (snippets will load just-in-time)....
Package iswitchb is obsolete!
Making url-show-status local to  *http 127.0.0.1:41293* while let-bound!
Suspicious state from syntax checker javascript-flow: Checker javascript-flow returned non-zero exit code 64, but no errors from output: flow: unknown option '--respect-pragma'.
Usage: flow check-contents [OPTION]... [FILE]

Runs a flow check on the contents of stdin. If FILE is provided, then
check-contents pretends that the contents of stdin come from FILE

e.g. flow check-contents < foo.js
or   flow check-contents foo.js < foo.js

  --color                           Display terminal output in color. never, always, auto (default: auto)
  --from                            Specify client (for use by editor plugins)
  --help                            This list of options
  --ignore-version                  Ignore the version constraint in .flowconfig
  --json                            Output results in JSON format
  --no-auto-start                   If the server is not running, do not start it; just exit
  --old-output-format               Use old output format (absolute file names, line and column numbers)
  --one-line                        Escapes newlines so that each error prints on one line
  --retries                         Set the number of retries. (default: 3)
  --retry-if-init                   retry if the server is initializing (default: true)
  --root                            Project root directory containing the .flowconfig
  --sharedmemory-dep-table-pow      The exponent for the size of the shared memory dependency table. The default is 17, implying a size of 2^17 bytes
  --sharedmemory-dirs               Directory in which to store shared memory heap (default: /dev/shm/)
  --sharedmemory-hash-table-pow     The exponent for the size of the shared memory hash table. The default is 19, implying a size of 2^19 bytes
  --sharedmemory-log-level          The logging level for shared memory statistics. 0=none, 1=some
  --sharedmemory-minimum-available  Flow will only use a filesystem for shared memory if it has at least these many bytes available (default: 536870912 - which is 512MB)
  --show-all-errors                 Print all errors (the default is to truncate after 50 errors)
  --strip-root                      Print paths without the root
  --temp-dir                        Directory in which to store temp files (default: /tmp/flow/)
  --timeout                         Maximum time to wait, in seconds
  --verbose                         Print verbose info during typecheck
  --verbose-depth                   Recursively print types up to specified depth (default 1, implies --verbose)
  --verbose-indent                  Indent verbose info during typecheck (implies --verbose)

Checker definition probably flawed.
Unable to check for new version.
Mark set


```

and the message appears every time than I type a single character, I've updated flow and flow-bin but the error persists...

do you know what could be the problem here?..thank you!!!

**Comment by cocodrino** [comment]
thanks @jdelStrother I was checking this today and works pretty good, I've disabled the mode warnings as reem did and tern autocomplete, I think than these minor modes must be disable by default

I've only done a few test but it works really good so far...thank you so much!!!...

**Comment by evindor** [comment]
@jdelStrother Thanks for your work! Been using your layer for several weeks.

It would be great to have a nice flow layer, there are just a few steps from here. I had trouble switching to flow completion from tern, would be amazing to have it automatically set as company-backend when flow detected.

Also, I assume it's possible to implement jump to definition as done [here](https://github.com/flowtype/flow-for-emacs/blob/master/flow.el).

Unfortunately, my lisp-fu is not strong enough to add those, so posted a bounty in hopes someone finds time to do it. 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=37889526)](https://www.bountysource.com/issues/37889526-some-request-support-facebook-flow-language?utm_source=37889526&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by lsdafjklsd** [comment]
How do I use this? I've added the flow-type layer to my +lang directory, modified my .spacemacs file to include the layer but nothing is happening in my flow file. Do I need to add additional dependencies? I'm currently using js2-mode. I don't see a minor mode to enable, I got something half working prior to trying this, and for that I would just enable flycheck mode in the file and it worked (but crappy).

**Comment by evindor** [comment]
@lsdafjklsd Some ugly lisp here but this is how I made it work for me, maybe you could find a better way!
```elisp
  (defun company-force-flow ()
    (setq company-backends-js2-mode '(company-flow company-tern
                                                   (company-dabbrev-code company-gtags company-etags company-keywords)
                                                   company-files company-dabbrev))
    (setq company-backends-react-mode '(company-flow company-tern
                                                     (company-dabbrev-code company-gtags company-etags company-keywords)
                                                     company-files company-dabbrev)))

  (add-hook 'js-mode-hook 'company-force-flow)
  (add-hook 'react-mode-hook 'company-force-flow)
```
For me it was tern completion that dominated and was always on top of flow, this hackity hack reversed it and I got back to work. Check your enabled linters in any buffer with `SPC e v`. Check your completion engine, when about to see some suggestions, with `M-x company-diag`.

Also if you use React, put this in your `user-config`:
```elisp
(add-to-list 'magic-mode-alist '("\/\/ @flow\n\nimport React" . react-mode))
```
This will make emacs open a file in react-mode if the file starts with:
```js
// @flow

import React, {Component} from 'react'
//         ^ It doesn't matter what goes after this "t" actually
```

Good luck making it work!

**Comment by evindor** [comment]
Hey everyone in the thread, let's team up on the bounty! Both spacemacs and flow became integral parts of my job. It's a pity such a great editor has the worst support for flow (hottest js typing solution with 10k github stars) among all the others.

With the hacks above, and thanks to @jdelStrother, completion and type-checking mostly work, but there still are quite a few things:
- proper mode hooks so we don't have to hack it around tern in the dotfile
- syntax highlight! It's mostly fine until you begin using type aliases / generics (`export type PayloadCreator<A, B> = (...args: Array<B>) => A` screws highlight till the end of the file)
- Flow can provide insanely good jump-to-definition across files and modules
- Bindings for `get-importers` and `get-imports`
- Type coverage!

**Comment by evindor** [comment]
Please, let's make spacemacs the best editor for modern js development! I'm happy to help however I can, just bumped $50 to the bounty. 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=37889526)](https://www.bountysource.com/issues/37889526-some-request-support-facebook-flow-language?utm_source=37889526&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by ignu** [comment]
i just bumped it too. i just fell in love with Flow and really don't want to have to move to Atom.

**Comment by aaronjensen** [comment]
fwiw, I simply exclude the tern/company-tern package. This is less than ideal if you have/care about non-flow projects.

I could probably change company-flow's prefix function to look for a `.flowconfig`. That way you could have both company-flow and company-tern in your company backends.

**Comment by evindor** [comment]
I just tried the layer for elmlang, it's perfect. Something like this for flow would blow my mind.

**Comment by evindor** [comment]
New goodness in [fresh flow version](https://github.com/facebook/flow/releases/tag/v0.38.0):

> Local find references command: `flow find-refs file line column` - if there is a variable `x` at `file:line:column`, then this command returns the location of `x`'s definition and the location of all reads and writes to `x`.

This would be so perfect to have as `g d` or a local binding.

@ignu Thanks for the contribution!

**Comment by aaronjensen** [comment]
It'd also allow us to write refactoring tools eventually

**Comment by evindor** [comment]
@syohex Could I invite you to have a look at our issue here? Maybe you'll find it interesting to help with. The amount of [open elisp code](https://github.com/syohex?utf8=%E2%9C%93&tab=repositories&q=&type=&language=emacs%20lisp) you wrote is mind-blowing💥!

I hope we'll be able to further raise the bounty!
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=37889526)](https://www.bountysource.com/issues/37889526-some-request-support-facebook-flow-language?utm_source=37889526&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by evindor** [comment]
@justbur Please let me invite you too to have a look at the issue, maybe you know the person who could tackle the task?

**Comment by syohex** [comment]
@evindor What's the problem ? I don't use spacemacs and I have not written JavaScript programming well so far.

**Comment by justbur** [comment]
@evindor I'm not using spacemacs or javascript right now

**Comment by jdelStrother** [comment]
> Local find references command: flow find-refs file line column - if there is a variable x at file:line:column, then this command returns the location of x's definition and the location of all reads and writes to x.
This would be so perfect to have as g d or a local binding.

This isn't really suitable for `gd` though - IME the current `gd` is good enough.   `flow find-refs` gives you a list of places where the current symbol is being used/modified - not sure of the best way of exposing it in spacemacs.   Maybe it should open a quickfix window which lists the different usages of the current symbol, or just highlight them all with the `highlight` library?

**Comment by jdelStrother** [comment]
I hacked together a quick POC for jump-to-definition with `flow get-def` at https://github.com/jdelStrother/spacemacs/tree/flow-type-gd.   It works ok when manually invoking `(flow-type/jump-to-definition)`, though I can't seem to persuade it to work with `gd` - it always seems to just use the regular `dumb-jump-go` handler.   Any suggestions why?

(Also, I've not found many places where it gives better results than dump-jump-go.  Anyone found a good usecase for `flow get-def` ?)

**Comment by evindor** [comment]
For some reason I still have to do crazy hacks in my dotfile to actually push company-flow to the list of company-backends. Just doesn't work out of the box, I get tern completion instead, `M-x company-diag` confirms flow is there, but second in the list. I tried this:
```elisp
(defun company-force-flow ()
  (setq company-backends (remove 'company-tern (add-to-list company-backends 'company-flow)))
  (setq company-backends-js2-mode (remove 'company-tern (add-to-list company-backends 'company-flow)))
  (setq company-backends-react-mode (remove 'company-tern (add-to-list company-backends 'company-flow))))

(add-hook 'js-mode-hook 'company-force-flow)
(add-hook 'react-mode-hook 'company-force-flow)
```
But with no effect, tern is still enabled and still on top of company-backends.
The only thing that helps is that [crazy piece of code mentioned earlier](https://github.com/syl20bnr/spacemacs/issues/7119#issuecomment-273321365), where I override company-backends.

**Comment by aaronjensen** [comment]
@evindor I believe another option is disabling `tern-mode` because `company-tern` checks for that if I'm not mistaken.

**Comment by evindor** [comment]
There is a [pull request for this feature](https://github.com/syl20bnr/spacemacs/pull/7208#issuecomment-274897961), I suggested the list of todos to consider the bounty satisfied.

To recap: The bounty is for improving, and then merging, [this pull request](https://github.com/syl20bnr/spacemacs/pull/7208). Which effectively closes this issue.

**Comment by evindor** [comment]
@cocodrino Could you please update the issue title and first post, so it reflects the pull request, the list of requirements and the bounty? I hope if you update it will also render the new information [on bountysource](https://www.bountysource.com/issues/37889526-some-request-support-facebook-flow-language) 👍

**Comment by evindor** [comment]
@syl20bnr @TheBB Could you please organize this bunch of issues and PRs nicely?

- We got a nice [$220 bounty](https://www.bountysource.com/issues/37889526-some-request-support-facebook-flow-language) on this issue
- We got a PR #7208 with initial take at the task
- The bounty is actually for improving and merging #7208, the [summary of required features](https://github.com/syl20bnr/spacemacs/pull/7208#issuecomment-274897961) is also there in #7208

@syl20bnr @TheBB Could you please add appropriate labels to the issues to generally make it more visible? Anything else you typically do to manage issues?

And many many thanks for your amazing work! 🔮 Spacemacs rules 🚀

**Comment by jedahu** [comment]
FWIW I just added coverage checking to flycheck-flow. https://github.com/lbolla/emacs-flycheck-flow/pull/20

**Comment by syl20bnr** [comment]
@evindor I edited both the issue and the PR and added a label `Bounty $`, let me know if there are others things to add. Thank you.

**Comment by jdelStrother** [comment]
I got `gd` working for jumping to definitions with `flow get-def` at https://github.com/syl20bnr/spacemacs/pull/7208, and have rebased it onto a more recent version of the develop branch.   ( @syl20bnr - Thanks for `spacemacs|add-company-backends`, that cleaned things up a lot.)

**Comment by z3t0** [comment]
Hi all, from what I have read above it seems quite a bit of work has been done on this but the edges still need to be smoothed and some features need to be implemented.

I am completely new to the spacemacs community and have been using it for about 1.5 months without delving too deep into it.

I currently have quite a bit of time and energy, and would like to try and solve this problem because in my opinion Flow should have first class support on spacemacs.

However, this will take a while and I need some direction. I have never coded in Elisp or done anything like this before, so if you could please point me to some good resources and things I would need to learn that would be great.

### Here are some of my questions
1. How do I maintain my own version of spacemacs so that I can locally work on adding a flow layer?
2. What is a good place to ask for help if I get stuck? the irc channel isn't very active and doesn't have records so that is not very ideal. Should I ask on Gitter or..?
3. what are existing tools/solutions that would be a part of the final layer? It was mentioned somewhere that eldoc integration would be important, what are some other similar things?

**Comment by mikeplus64** [comment]
Here's my very unbrilliant solution: use `flycheck-eslint` and set up `eslint-plugin-flowtype-errors`. See https://github.com/amilajack/eslint-plugin-flowtype-errors

**Comment by skattyadz** [comment]
@mikeplus64 very sneaky indeed

**Comment by DenisNeustroev** [comment]
any progress?

**Comment by tbinetruy** [comment]
Hi all :)

Last time I came here I didn't find what I wanted, so I worked on a script that compiles all the info here and that will hopefully help others out there. It should be pretty easy to install but let me know if you need help. 

https://github.com/tbinetruy/config/tree/master/spacemacs/flow

It's very basic, but it suits my needs to now. If anyone wants to help or is aware of a solid spacemacs/flowjs integration, I;ll be happy to switch over. This was a nice getting to know emacs and the elisp though ;p

Cheers,

Thomas

**Comment by duianto** [comment]
A first draft of a `flow-type` layer has been merged into the `develop` branch:
add flow-type layer #10513

But there's a PR open to remove it, with a suggestion to use `javascript + LSP` instead:
Remove flow layer, suggest javascript + LSP #13157

Are there any objections to removing the `flow-type` draft layer?

**Comment by jdelStrother** [comment]
IMO it should be removed, using flow via LSP is a much better experience.

**Comment by smile13241324** [comment]
Flow support is mainly integrated in the current javascript lsp implementations. I have today removed the obsolete standalone flow layer by merging #13157 which also includes some hints in the documentation how to enable them.
