### ISSUE TITLE
some key bindings/behavior changed after upgrade to 0.200.1

### ISSUE THREAD

**Issue by noelyang** [syl20bnr/spacemacs#7380]
never edited my .spacemacs file.
## helm:
- no auto completion for path.
- very hard to ssh to a remote server via helm now as i have to type everything correctly without auto completion
## keybindings:
- closing window SPC w c -> SPC w d 
- magit commit/fetch/push keybindings disappeared, used to be SPC g c, SPC g f, SPC g P

it there an easy way to revert these changes?

**Comment by bmag** [comment]
> - closing window SPC w c -> SPC w d
> - magit commit/fetch/push keybindings disappeared, used to be SPC g c, SPC g f, SPC g P

As expected. Please read [the changelog](https://github.com/syl20bnr/spacemacs/blob/master/CHANGELOG.org).

> it there an easy way to revert these changes?

You can downgrade to the previous version, or you can override those settings in `user-config`.

I did not understand the problem with Helm. When upgrading Spacemacs, don't forget to update your packages and your dotspacemacs file as well. The default template for the dotspacemacs file is always located at `core/templates/.spacemacs.template`. Updating those might fix the Helm issue.

**Comment by vendethiel** [comment]
> I did not understand the problem with Helm.

Well, it seems the fuzzy matching is behaving differently from before. First off, it doesn't highlight the matched parts anymore. Second off, it's far less "fuzzy" (lenient) in what it allows: `AsseM` doesn't match `AssetManager` anymore – you need to type out `AssetM` to find a match. (note: my `dotspacemacs-helm-use-fuzzy` is "correctly" on `'always`)

**Comment by noelyang** [comment]
> As expected. Please read the changelog.
Got it, should have read the changelog first

> When upgrading Spacemacs, don't forget to update your packages and your dotspacemacs file as well.
Just did a full re-install with a brand new dotspacemacs file, still not working.
I found that when switched to neotree buffer then ctrl-x ctrl-f, it worked the same way as before: i could type/select then tab to move into the folder, when deleting a path it would remove all the current folder name.

When in other major mode buffers, ctrl-x ctrl-f requires me typing a lot and the fuzzy match is not fuzzy at all. Also, I need to delete every single character of the current path if I want to explore a upper path.

**Comment by bmag** [comment]
We use `helm-flx` now, and disable fuzzy matching for `C-x C-f` intentionally [here](https://github.com/syl20bnr/spacemacs/blob/v0.200.2/layers/+completion/helm/packages.el#L467). However, the comment says this is only until https://github.com/PythonNut/helm-flx/issues/9 is resolved, and it has been resolved... 
@noelyang can you add the following to `user-config`, and test that it provides fuzzy matching for `C-x C-f` and also doesn't cause a slow down or other issues?
```elisp
(with-eval-after-load 'helm-flx
  (helm-flx-mode -1)
  (setq helm-flx-for-helm-find-files t)
  (helm-flx-mode))
```

As for backspace not deleting whole chunks, I don't know when that started to happen, but it's the same in vanilla helm. In Spacemacs we have `C-l` for "going up" the directory tree in this case.

As for `TAB` not completing, it does complete on my machine. You can also use `C-j`.

**Comment by vendethiel** [comment]
I tried this fix, it does not seem to work for either `C-x C-f` or `C-c p f` (`projectile-find-file`, which is pretty much the only one I use) (it's still not fuzzy)

**Comment by noelyang** [comment]
> @noelyang can you add the following to user-config, and test that it provides fuzzy matching for C-x C-f and also doesn't cause a slow down or other issues?

these lines froze my emacs randomly when pressing ctrl-x ctrl-f

i tried c-j and c-l and it felt quite sensible. it's time to change my habit a little bit.

**Comment by bmag** [comment]
> these lines froze my emacs randomly when pressing ctrl-x ctrl-f

Then it may be that `helm-flx` still has performance problems with `helm-find-files` (but if anyone wants to test it properly, go ahead).

I'm not sure what's going on with the fuzziness, really, but it could be simply that you aren't running the correct helm sources. For example, with `SPC p f` (`helm-projectile-find-file`) I do get fuzzy search, but with `C-c p f` (`projectile-find-file`) the search is not fuzzy.
