### ISSUE TITLE
Unable to return to previous location with C-t when using cscope

### ISSUE THREAD

**Issue by jlombera** [syl20bnr/spacemacs#7666]
#### Description :octocat:
Unable to return to previous location when using cscope.  The `SPC m g ...` commands work correctly to navigate the code, but not able to jumb back in the mark stack.  `C-t` works as expected using other tag tools (tested in a Go (go-guru) project), which makes me think the problem is specific to the cscope layer.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file from a project for which a cscope database exists.
- Use `SPC m g ...` to navigate the code.
- Use `C-t` to return to previous location.

*Observed behaviour:* :eyes: :broken_heart:
No jump to previous location is made when pressing `C-t`, the following message is shown instead: "Marker stack is empty".

*Expected behaviour:* :heart: :smile:
Return to the previous location after pressing `C-t`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. aa3f181)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults c-c   cscope emacs-lisp git github
                 (go :variables go-tab-width 4)
                 html markdown
                 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e" :packages
                       (not mu4e-maildirs-extension))
                 org semantic shell spell-checking syntax-checking systemd version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

#### Backtrace :paw_prints:

**Comment by TheBB** [comment]
`C-o` doesn't work?

**Comment by jflombera** [comment]
Yes, `C-o` works as expected, but its behavior is not the same than the expected behavior of `C-t`.  `C-t` is used to jump back in the "tag" stack (at least in Vim) whereas `C-o` is more general and its "stack" includes jumps performed by different commands (for example, going to the last line in the file (`G`)).

**Comment by TheBB** [comment]
So, does `helm-cscope` not push to this tag stack then? Or is it a Spacemacs problem?

**Comment by TheBB** [comment]
Looks to me like xcscope.el has its own pop mark implementation: https://github.com/dkogan/xcscope.el#keybindings

**Comment by jflombera** [comment]
You are right, directly calling `cscope-pop-mark` has the desired effect (i.e. what `C-t` should do).

I am not sure what the fix should be (new emacs/spacemacs user coming from Vim).  Should this be fixed in spacemacs's cscope layer (properly mapping `C-t` to `cscope-pop-mark`) or in xcscope.el (to use xref, since `C-t` is mapped to `xref-pop-marker-stack`)?

**Comment by TheBB** [comment]
> Should this be fixed in spacemacs's cscope layer (properly mapping `C-t` to `cscope-pop-mark`)

This will break all other uses of `C-t`.

> or in xcscope.el (to use xref, since `C-t` is mapped to `xref-pop-marker-stack`)?

Yes, I added the “Should report upstream” label for a reason. ;-)

**Comment by dubnde** [comment]
I find that if I add `(cscope-setup)` to my configuration, I can then use the cscope keybinding `C-c s u`. Obviously not on muscle memory as `C-t` is.

**Comment by derkling** [comment]
This is a pretty old issue and, AFAIS, the `C-t` binding is still not working as expected by vim users.
Since a long time has passed, is there any news on how to properly implement `C-t` for the cscope layer?
