### ISSUE TITLE
Copying custom variable definitions into .spacemacs is slow and confusing

### ISSUE THREAD

**Issue by marienz** [syl20bnr/spacemacs#7816]
Not using the bug report template as this is not technically a bug, but let me know if you need anything from that template I didn't include.

Commit e699f18 moved custom variable definitions into a file in the cache directory, which gets copied into .spacemacs at startup. I think it would be better if spacemacs loaded the file from the cache directory directly, instead of copying it into a function in .spacemacs at startup and then calling that function. Apart from simpler code, I have two arguments for that:

First, keeping the settings in .spacemacs makes it look like you can copy your customize settings to a different machine by copying .spacemacs (which you could indeed do before this change). But that does not work, because if you change .spacemacs and then (re)start spacemacs it overwrites your changes to `dotspacemacs/emacs-custom-settings` with that machine's cached customize settings. (I simulated this on a single machine by backing up the cache file, customizing some settings, restarting spacemacs to get the changes into .spacemacs, reverting the cache file, touching .spacemacs in case I missed some code that looks at timestamps, then restarting spacemacs. This overwrote my customizations, as expected from glancing at the code).

Second, on my system (with a version-controlled .spacemacs) rewriting it doubles spacemacs startup time. It now takes about 3.2 seconds to start. If I comment out the call to ` spacemacs/write-custom-settings-to-dotfile`, it's 1.3 seconds, which is about what I got before the change. This could probably be made faster somehow, but I don't think it can be made as fast as not rewriting .spacemacs in the first place :)

Suggested alternative: keep setting `custom-file`, remove `spacemacs/write-custom-settings-to-dotfile`, load `custom-file` where `dotspacemacs/emacs-custom-settings` is currently called. Optionally cater to people wanting to version-control custom-file by allowing them to put it somewhere other than the cache directory (not sure at what point in the startup process you need to change it for that to work, but I suspect `dotspacemacs/user-init` would do the trick).

**Comment by dubnde** [comment]
I agree with this issue. It is obviously showing my init file as modified and I have to check all the time to make sure it is just the auto-generated code at the end. Not so much a problem if one's configuration is matured but really creates unnecessary effort. Perhaps specemacs could just load the `.custom-settings` file itself.

I had something like below and prefer to manage my own custom settings
```
(unless (bound-and-true-p custom-file)
  (setq custom-file (concat spacemacs-cache-directory "custom.el")))

(when (file-exists-p custom-file)
  (load custom-file))
```
This allows me to cleanly version control my `.spacemacs.d` folder. Just a thought :smiley:

**Comment by syl20bnr** [comment]
Thank you for the report.

When I implemented it I forgot that I had in mind to use an advice to automatically write back the custom settings to the dotfile whenever Emacs does it. It should fix all the points you mentioned.

**Comment by syl20bnr** [comment]
I just pushed the change to an advice, there now should be no difference with regular custom file.
commit: https://github.com/syl20bnr/spacemacs/commit/6ae2fbc

**Comment by marienz** [comment]
Thanks! That does fix it for me.

**Comment by jupl** [comment]
I don't believe the issue is resolved for me.

I never use Emacs' customize feature. Before this new feature I would use `custom-file` to write custom configurations by Emacs into a file that would never get loaded. Now Spacemacs is modifying my configuration file which I'm not interested in and it becomes an inconvenience as I need to watch out for this file in version control. Even when I remove the code automatically when I update packages, that piece of code is being added back into my configuration.

**Comment by dubnde** [comment]
I agree not resolved. Spacemacs still appends custom configuration if there is updates to packages or packages are installed/uninstalled.

**Comment by mrosset** [comment]
I person right now use my own custom-file logic. specifically to keep emacs customization out of .spacemacs, and it works fine for me.
