### ISSUE TITLE
An error occurred while installing evil-unimpaired (error: (wrong-type-argument arrayp nil))

### ISSUE THREAD

**Issue by canxer314** [syl20bnr/spacemacs#7853]
--> installing package: evil-unimpaired@spacemacs-evil... [4/13]
An error occurred while installing evil-unimpaired (error: (wrong-type-argument arrayp nil))

**Comment by ithamsteri** [comment]
I today have this problem too. I clean install Spacemacs over git. Start Emacs. Select 'vim', 'spacemacs', 'helm' (or 'ivy') and get this problem. Every run Emacs I get error ' evil-unimpaired (error: (wrong-type-argument arrayp nil))'. 2 days ago I no have this problem. ¯\_(ツ)_/¯

**Comment by bmag** [comment]
Usually fixed by: http://spacemacs.org/doc/FAQ#how-to-fix-wrong-type-argument-arrayp-nil-errors-on-startup

**Comment by ithamsteri** [comment]
In next day I try again... and no have problem.

**Comment by CMCDragonkai** [comment]
@bmag Even after deleting that, I still get this error.

**Comment by Nek** [comment]
I had this issue half an hour ago while installing spacemacs from scratch. The problem surfaced around 12:30 AM. Deleting .cache didn't help and I fixed it by setting time to plus one hour manually and resetting it back after the spacemacs installation.

It looks like the problem is still there.
