### ISSUE TITLE
Extra space after helm-completion

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#8316]
#### Description :octocat:
Helm completion prompt adds a extra space after the original letters

#### Reproduction guide :beetle:
- Start Emacs
- open a python shell buffer and triggers a helm completion

Alternatively,
- Open a ELisp file
- Type letter `l`
- `M-x` and `helm-lisp-completion-at-point`

*Observed behaviour:* :eyes: :broken_heart:
There is an extra space after the previously entered letters.

<img width="1255" alt="screen shot 2017-02-06 at 5 17 02 pm" src="https://cloud.githubusercontent.com/assets/3363954/22641172/8e844a10-ec90-11e6-93f5-8551522c5911.png">

![image](https://cloud.githubusercontent.com/assets/3363954/22641261/e5379880-ec90-11e6-8e86-ba93eab3a93f.png)

*Expected behaviour:* :heart: :smile:
There should be no space.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c3afd5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(yaml
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete :disabled-for shell)
 emacs-lisp
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
 (shell :variables shell-default-shell 'eshell shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
 (javascript :variables javascript-disable-tern-port-files nil)
 html git markdown org cscope
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 (python :variables python-enable-yapf-format-on-save t)
 better-defaults
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
 dash php react asm coq semantic)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
From what I see, the extra space is only in the prompt. After you select the completion you want, there is no extra space inserted to the actual buffer.

That said, isn't the extra space just standard Helm behavior for the completion-at-point (a built-in feature, not Company) prompt? I'm pretty sure it is standard Helm behavior.

**Comment by LukeXuan** [comment]
@bmag However if I directly enter some words, the prompt would become "l some" rather than "lsome", which may alters the candidates' order so that I need to choose the second or even below to complete.

**Comment by LukeXuan** [comment]
@bmag I'm not sure about whether it is standard for Helm, maybe it is. I'm just expressing my confusion about this space.

**Comment by bmag** [comment]
It's a prompt where you select a candidate out of several. What's inserted to the shell buffer is the candidate you selected ("lsome"), not the text you entered at the prompt ("l some"). The popup supports fuzzy search (I think), that's why it lets you insert a space at the prompt.

**Comment by LukeXuan** [comment]
What I meant by pictures:

1. The place I press to trigger helm-completion-at-point

![image](https://cloud.githubusercontent.com/assets/3363954/23341336/5c55fa70-fc80-11e6-8def-7bf0d60e66ec.png)

2. What I obtained by enter "h" directly

![image](https://cloud.githubusercontent.com/assets/3363954/23341338/6820477a-fc80-11e6-8f7d-ddef8c55d21d.png)

3. What I expect (by deleting space and enter "h" directly).

![image](https://cloud.githubusercontent.com/assets/3363954/23341343/84a910fc-fc80-11e6-9b7a-f313aa28cd04.png)

@bmag I hope these would illustrate my idea.

**Comment by bmag** [comment]
Thanks for clarifying. Looks like the extra space causes fuzzy search to prioritize `top_height` before `this_is_a_fun` because the "h" occurs in a beginning of a word. The obvious solution is not to insert the extra space in the first place, indeed. I am not sure if this should be fixed in Spacemacs or upstream in Helm (or a Helm-related package).

**Comment by invsblduck** [comment]
Apologies for late bump! Just ran into this learning Spacemacs/Emacs.

I am using`auto-completion` layer, so usually I get the company menu while typing in Insert mode, but if I've dismissed company (or I am re-entering Insert mode from Normal mode) and I press `TAB`, completion at point will use Helm instead. I actually prefer the fuzzy-find of Helm, but the extra space mucks up the flow a bit. :)

If I weren't busy learning 6,000 things about how to use Emacs, I would peek at the elisp. Leaving this comment as a reminder.

**Comment by invsblduck** [comment]
and 364 days later, i have been reminded!  bug still present in master with versions noted in previous comment above (makes sense, since @LukeXuan reported the bug in develop), but... i don't currently have time to investigate.

ps: it's been a great 12 mos with spacemacs! 🥳

**Comment by duianto** [comment]
The bug is unrelated to Spacemacs, because it also occurs with only Emacs and emacs-helm installed:

![2020-09-14_08-30-06](https://user-images.githubusercontent.com/13420573/93051422-bd38cc00-f664-11ea-96cd-4039aff699c5.png)

At the moment the emacs-helm development has stopped:
Helm development is now stalled https://github.com/emacs-helm/helm/issues/2386
https://www.reddit.com/r/emacs/comments/iqytf6/has_the_development_of_helm_stopped/

Maybe the current maintainer will hand over the project to someone else, or maybe it will be forked.

It looks like it's still possible to open issues on https://github.com/emacs-helm/helm/issues
so it should be reported upstream, to make other helm users aware of the space issue.

**Comment by holtzermann17** [comment]
Something similar came up, and I reported it then. It was fixed:
https://github.com/emacs-helm/helm/issues/2274
Optimistically, the fix may give a clue about how to also fix it in the case you're concerned with here?  Haven't checked, and FWIW the behavior I reported has reverted, so the bug should ideally be reported again.  However, in light of the above, maybe we're on our own here for a while.

**Comment by manuel-uberti** [comment]
Hello everyone, there has been a fix for this last night. Could you try again?

**Comment by duianto** [comment]
Thanks for the update.

The `<tab>` (`completion-at-point`)  in `M-x shell` doesn't seem to have a space anymore.

![2020-12-28_19-02-42](https://user-images.githubusercontent.com/13420573/103234210-5f906d00-493f-11eb-8b2e-335056a1dd16.png)

But a space still appears in the helm frame that opens with: `M-x helm-lisp-completion-at-point`

![2020-12-28_19-01-50](https://user-images.githubusercontent.com/13420573/103234217-628b5d80-493f-11eb-9521-728cecbea546.png)

### System Info:
helm-20201228.517
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21
Windows 10 2004

**Comment by gregsgit** [comment]
Thank you, @manuel-uberti !! This has been an annoyance for a while.
