### ISSUE TITLE
File error: Cannot open load file, No such file or directory, bind-map

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#8984]
#### Description :octocat:
Freshly installed spacemacs does not work because of init.el error

#### Reproduction guide :beetle:
- git clone the repo
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
```
Warning (initialization): An error occurred while loading ‘/Users/achikin/.emacs.d/init.el’:

File error: Cannot open load file, No such file or directory, bind-map

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

*Expected behaviour:* :heart: :smile:
Emacs starts without errors

#### Backtrace :paw_prints:
```
Warning (initialization): An error occurred while loading ‘/Users/achikin/.emacs.d/init.el’:

File error: Cannot open load file, No such file or directory, bind-map

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by rebcabin** [comment]
I have exactly the same issue. Brand-new Windows machine, trying to migrate from Mac. I am dead in the water without spacemacs!

**Comment by achikin** [comment]
It looks like some melpa outage. I've retried half an hour later and everything worked as intended.

**Comment by rebcabin** [comment]
I have the same problem a day later :(

**Comment by rebcabin** [comment]
Still have the problem a day later. Run as Admin or not, Master branch or develop branch. Fresh .spacemacs file or custom .spacemacs file.

**Comment by dancar** [comment]
👆  Same here :-\

**Comment by fokoepxg** [comment]
Same here. Cant install spacemacs. Exact same error described above

**Comment by JAremko** [comment]
Sometimes Melpa can lag for days :disappointed: 

I hope it's all ok now?

**Comment by guillermoruizalv** [comment]
For me it works with:
```bash
emacs --insecure
```

**Comment by achikin** [comment]
No further issues.

**Comment by azer** [comment]
This issue is still happening for me, makes it impossible to open Emacs. How did others solve the problem ?

**Comment by rebcabin** [comment]
it just went away for me after a few days, so I assumed it was melpa lag, but didn't prove so.

**Comment by Bost** [comment]
@guillermoruizalv `emacs --insecure` helps indeed.
@achikin The --insecure switch bothers me a lot. IMO we should be able to run emacs securely(!). I propose to reopen this issue.

**Comment by sahilshekhawat** [comment]
Facing the same error,  don't think using ``emacs --insecure`` is a fix. Please reopen the issue.

**Comment by rdjack21** [comment]
Just did a clean install today and have the same issue. while emacs --insecure did allow the install to finish I really don't like that we have to do that to get things to work.

**Comment by paldepind** [comment]
I was trying to install Spacemacs and I experience the same issue. Running Emacs with `--insecure` doesn't help.

**Comment by ShingoFukuyama** [comment]
Thanks to @fokoepxg, `dotspacemacs-elpa-timeout 300` in `.spacemacs` works for me!

**Comment by Bost** [comment]
@ShingoFukuyama you mean like in 5 minutes you mirrored a quarter of elpa and coincidentally that provides for all the elpa packages you use? Well done then, hmm.

**Comment by gcperrin** [comment]
Still an issue as of 9/27

**Comment by benbotwin** [comment]
Still happening today, maybe first run should be insecure by default?

**Comment by theamazingcase** [comment]
Fresh install, same issue on MacOS 10.12.6. Having never used emacs before, this is a rather daunting introduction, and I'm hesitant to use the --insecure flag...

**Comment by ashleylester** [comment]
Happening on Windows 10 with fresh install of Emacs emacs-25.3_1-x86_64. Adding `dotspacemacs-elpa-timeout 300` doesn't work.

**Comment by simendsjo** [comment]
I get a similar error: `File error: Cannot open load file, No such file or directory, up-core`. I've tried increasing the timeout, using both `develop` and `master`, and running `emacs --insecure` on both combinations without any luck.

**Comment by vitorbaptista** [comment]
Just in case others have this error, make sure you delete your `.emacs.d` folder and clone spacemacs again, as the issue with `up-core` was caused by a bug in a package that might still be in your local cache.

**Comment by loxs** [comment]
I had the same problem. Nothing of aforementioned (both here and in the referenced bug) helped.
I nuked my whole .emacs.d/ and that didn't help as well. Finally I ended up fixing it like this:

    M-x install-package RET use-package

I waited for the package to install, then restarted emacs with `--insecure` and finally that helped spacemacs to pull in all required packages, compile them etc.

**Comment by looksworking** [comment]
CentOS, emacs 25.3.1 built from sources, same problem, solved by 
`M-x install-package RET use-package` (thanks @loxs!) 
`--insecure` option is not needed

**Comment by joaocenoura** [comment]
I was hitting the same issue (`File error: Cannot open load file, No such file or directory, bind-map`) when updated spacemacs to `develop` branch + emacs 25. After deleted my old `~/.spacemacs` and restart emacs it fetched packages from melpa successfully.

**Comment by JosXa** [comment]
Same issue as OP on Windows 8 and Windows 10. --insecure option has no effect.

**Comment by tuliogrodrigues** [comment]
I had the same problem because the proxy server was not allowed to connect through https. To solve the problem, in my .spacemacs file I changed the bellow configuration

from 
`dotspacemacs-elpa-https t`
to
`dotspacemacs-elpa-https nil`

**Comment by 941968215** [comment]
Because `.spacemacs` dones't exist, so just: 
```
cp ~/.emacs.d/core/templates/.spacemacs.template ~/.spacemacs
```
Then mkdir layers in `.spacemacs.d` fold
Everything will be  fine

**Comment by kowodo** [comment]
for me solution was commenting out in my init.el following line:
`;;(require 'diminish)                ;; if you use :diminish`

**Comment by jkrasnay** [comment]
For me, the problem was that Emacs was complaining about an insecure Lets Encrypt token from milpa. By setting `dotspacemacs-elpa-timeout 300` I was able to see the error and tell it to proceed.

**Comment by gsunjka** [comment]
I had the same issue. Seems like Emacs for Windows doesn't support TLS out of the box. I downloaded `emacs-25-x86_64-deps.zip` from http://ftp.gnu.org/gnu/emacs/windows/ and extracted it over my existing emacs folders. Afterwards everything worked fine.

**Comment by gluesniffmonkey** [comment]
I am getting this same error on Debian Stretch. 
0.200.13@27.0.50 (spacemacs)
emacs-snapshot --version GNU Emacs 27.0.50

**Comment by azer** [comment]
I'm also experiencing this error.

**Comment by thepulkitagarwal** [comment]
On a fresh install, I got this issue when I chose vim mode + helm. I did a complete reinstall with emacs mode + ivy, and this issue was not there.

**Comment by GroundedSage** [comment]
I'm confused as to how this is still an issue and that I am spending hours trying to find a solution.

**Comment by GroundedSage** [comment]
Following this seemed to do the trick. http://sourabhbajaj.com/mac-setup/Emacs/
Though it concerns me that you have to turn off security to get everything to run.

**Comment by eedahl** [comment]
Same problem

**Comment by adi-007** [comment]
I have the same issue. 
OS: Manjaro 17.1.10 
Emacs version: 26.1 
Spacemacs version: 0.200.13

**Comment by 1-riverfish** [comment]
I met the same question and solved it by changing the timeout from 30 to 300.

**Comment by damon98xp** [comment]
My Solution to this problem:
```
(setq package-user-dir "C:\My_ELPA_DIR")
(package-initialize)
```
After applying the code above, the error message "File mode specification error" disappears.

**Comment by dg01d** [comment]
same problem for me, on a mac. Nothing at all is loaded as a result, so I do not get a spacemacs.

This is nonsensical.

**Comment by csdrane** [comment]
I, also, am experiencing this problem.

**Comment by togakangaroo** [comment]
Happening for me when trying to trigger projectile on a brand new emacs/spacemacs install on a brand new instance of the windows 10 ubuntu subsystem

**Comment by Rizary** [comment]
windows 10 cloning fresh spacemacs all the above solution cannot work

**Comment by finomayato** [comment]
Deleting `elpa` folder my problem has been resolved - `rm -rf .emacs.d/elpa/`. `emacs --insecure` finished with success after that

**Comment by KraevRoot** [comment]
still have this problem

**Comment by isaaczhou** [comment]
Why is this issue closed? Still got this error

**Comment by tkreutz** [comment]
still have this problem on a fresh spacemacs installation. Why is this issue closed ?

**Comment by shelper** [comment]
still have this issue... tried `--insecure` and didnt work. 
tried delete and reinstall, didn't work, 
frustrating :(

**Comment by bradyt** [comment]
Consider if you see the following message, like in the initial issue.

``` elisp
To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Then be sure to try `emacs --debug-init`. That may provide more information to share here. It doesn't look like such a backtrace has been shared in this thread.

**Comment by KraevRoot** [comment]
@bradyt 
[output with --debug-init](https://i.ibb.co/LZyRr9j/image.png)

**Comment by shelper** [comment]
i think it is network related, i used another network, and the problem is gone.

**Comment by bradyt** [comment]
@KraevRoot btw, images of text are not conducive to troubleshooting. If anyone spots a suspicious line to search for, they have to type it out, instead of being able to copy paste text.

**Comment by jerome-diver** [comment]
maybe one day emacs will tell where and which line the problem is from... it will be a big day for emacs life.

**Comment by Compro-Prasad** [comment]
I think it already does jump to specific location of error if you do `M-x toggle-debug-on-error` before reproducing the error. Then you can just click on the backtrace links to jump to the specific location of the error.

**Comment by superzou94** [comment]
It works to me when I delete  ".emacs.d/.cache".
Emacs recompiled everything and everything goes fine.

**Comment by pgauding** [comment]
I moved my .emacs (which was and is symlinked) to .emacs.bak, opened emacs and allowed it to recompile, then moved .emacs.bak back to .emacs. Everything's peachy.

**Comment by nhmacuk** [comment]
Adding the insecure option as mentioned earlier worked for me as well (for my fellow noobs: open terminal and type followed by enter/return: "emacs --insecure")

**Comment by SreenivasVRao** [comment]
Seeing this error still... Any alternatives to --insecure?

**Comment by jerome-diver** [comment]
my alternative way to resolve anything there was to go with Doom.

**Comment by strokyl** [comment]
For me:
```
gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40
```
dit the trick after using ppa:kelleyk/emacs but maybe it would have work before.
I am on ubuntu bionic

**Comment by strokyl** [comment]
Ok on my other PC, on ubuntu disco, same issue solved by:
```
gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40
```

**Comment by jiftle** [comment]
me too.

**Comment by Plaoo** [comment]
> `gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40`

Works!! Thanks

**Comment by jjforsythe** [comment]
Thanks for the answers above. I required a small modification which some people may find useful.

Whilst running the develop branch of Spacemacs from `~/.emacs.d/spacemacs/` (i.e. having modified the `spacemacs-start-directory` variable), I needed to modify the command above to point to `~/.emacs.d/spacemacs/elpa/25.2/develop/gnupg` e.g.

`gpg --homedir ~/.emacs.d/spacemacs/elpa/25.2/develop/gnupg --receive-keys 066DAFCB81E42C40`

Note that this command needs to be updated with the version of Emacs you are running, in place of 25.2 above. Once Spacemacs is running you can also check the `package-user-dir` variable if you want to be completely sure that you are targeting the correct directory.

**Comment by poiulkjhmnbv** [comment]
> gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40

Thanks!!
The spacemacs is able to run on emacs 26.1.

**Comment by xoltar** [comment]
For me the problem was proxies. I was on a work machine, but not using VPN, so proxy info was wrong. Clearing the https_proxy env var fixed it.

**Comment by gamepad-coder** [comment]
**Confirming solution.**

Recipe worked for me: 
https://github.com/syl20bnr/spacemacs/issues/8984#issuecomment-306130164

**System**
OS : Windows 10
Using: WSL2 with a Mintty/WSLtty terminal running Bash

**Overview**
Loading Spacemacs directly into Bash using `emacs -nw`
failed before changing the default `dotspacemacs-elpa-timeout 5`.

Successful install after changing to `dotspacemacs-elpa-timeout 500`, 
same command `emacs -nw` to launch.

**Setup**

1. No preexisting Emacs. No preexisting Spacemacs.
2. Installed emacs using `apt-get install emacs` 
3. Removed `~/.emacs.d`
4. Git cloned spacemacs into `~/.emacs.d`
5. Fresh first launch in WSL2 Bash using `emacs -nw` <br>-> same error as top post.

Then success after I applied this recipe:
`~/spacemacs` : around line 89 : 
Default value is `dotspacemacs-elpa-timeout 5`.
Changed to `dotspacemacs-elpa-timeout 500` (arbitrarily much larger).

Thanks a million. Hoping this helps someone's search results.

**Comment by thecocoa** [comment]
Failing for me today - Ubuntu 20.04.  No exisiting ~/.emacs.d directory.

```emacs -q``` loads vanilla emacs just fine.

emacs -nw gives the following error:
```
Warning (initialization): An error occurred while loading ‘/home/bobrien/.emacs.d/init.el’:

Wrong type argument: stringp, async

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
Have cloned/deleted ~/.emacs.d, recloned at least 4x.  Maybe I'll wait until tomorrow incase it truly is a MELPA problem.
I would suggest, however, that the dotspacemacs-elpa-timeout be increased from 5 to 60.

**Comment by duianto** [comment]
@thecocoa It seems to have been an upstream issue, that's been fixed.
Cannot update packages, because the generated -pkg.el file uses a symbol instead of a string
https://github.com/melpa/melpa/issues/7312

**Comment by zhaozhiwei1992** [comment]
dotspacemacs-elpa-timeout 30
emacs --insecure

works for me, thank

**Comment by Melkor333** [comment]
For those who install spacemacs on windows with `chocolatey`, I had to go to the path `%appdata%` and then change the permissions of the folder `.emacs.d` so that my user has access to that folder. Chocolatey seems to somehow install the folder with administrator only permissions.
